//阿拉伯

module.exports = {
	exitconfirm: 'تأكيد الخروج',
	noexitconfirm: 'عدم التنبية مرة أخرى',
	login: 'دخول',
	loginph: 'البريد الإلكتروني',
	regemail: 'البريد الألكتروني المستخدم للدخول وإعادة تعيين كلمة المرور',
	pwdph: 'كلمة المرور',
	forgotpwd: 'نسيان كلمة المرور',
	reset: 'إعادة تعيين كلمة المرور',
	resetbtn: 'إعادة تعيين  ',
	resetemail: 'البريد الإلكتروني المسجل',
	pwdreset: 'كلمة المرور الجديدة تم إرسالها إلى',
	register: 'تسجيل مستخدم جديد',
	registerbtn: 'تسجيل  ',
	invaliduser: 'كلمة المرور وإسم المستخدم غير صحيحة',
	locate: 'الرئيسية',
	options: 'إعدادات',
	delete: 'مسح',
	logout: 'تسجيل الخروج',
	isempty: 'لا يمكن أن يكون فارغ',
	taken: 'تم تسجيله سابقاً ، الرجاء المحاولة مرة أخرى',
	invalidusername: 'بريدك الإلكتروني غير صحيح',
	failed: 'يوجد خطأ ، الرجاء المحاولة مرة أخرى',
	success: 'ناجح',
	alarm: 'إنذار',
	alarmtitle: 'رسالة إنذار',
	navigate: 'تتبع',
	startnav: 'بدء التتبع',
	sos: 'تفعيل وضع الخطر',
	startmonitor: 'تفعيل مراقبة الصوت',
	locatenow: 'تحديد الموقع الآن',
	confirmlocatesms: 'نحتاج لإرسال رسالة نصية إلى الساعة لنحصل على آخر إحداثيات الموقع ، تأكيد الإرسال؟',
	sms: 'إرسال رسالة نصية',
	history: 'تاريخ تحديد الموقع',
	mylocation: 'موقعي',
	kidlocation: 'موقع الطفل',
	startpoint: 'نقطة البداية',
	endpoint: 'المكان المقصود',
	addwatch: 'إضافة جهاز',
	add: 'إضافة  ',
	markasread: 'جعله كمقروء',
	morephonenumbers: 'رقم الهاتف',
	recivesmsalert: 'تنبيه تحديد الموقع',
	setupfence: 'المنطقة الآمنة',
	setupfence1: 'المنزل ',
	setupfence2: 'المدرسة',
	modifypwd: 'تعديل كلمة المرور',
	feedback: 'إفادة ',
	about: 'عن ',
	back: 'رجوع',
	imei: '',
	ownername: 'إسم الطفل',
	petname:'اسم حيوان أليف',
	simid: 'رقم هاتف الجهاز',
	simcountrycode:  'Country Code',
	soscountrycode:  'Country Code',
	phonenumbers: 'ارقام هواتف وضع الخطر',
	locateinterval: 'الفترة الزمنية للحصول على موقع الطفل',
	avatartxt: 'الصورة الرمزية',
	historyalarm: 'تاريخ الإنذارات',
	save: 'حفظ',
	oldpwd: 'كلمة المرور القديمة',
	newpwd: 'كلمة المرور الجديد ',
	submit: 'اقترح',
	invalidimei: '',
	dupaddwatch: 'لقد أضفت هذه الساعة سابقاً',
	confirmremovedevice: 'هل أنت متأكد من حذف هذه الساعة ؟ لن تصلك أي رسائل من هذه الساعة مستقبلاً',
	cancel: 'إلغاء ',
	from: 'اختيار مصدر الصورة',
	fromlib: 'استوديو الصور',
	fromcamera: 'إلتقاط صورة',
	invalidoldpwd: 'كلمة المرور القديمة غير صحيحة',
	undefined: 'غير محدد',
	fencename: 'الإسم',
	radius: 'نصف القطر',
	meter: '',
	centerpoint: 'نقطة الإرتكاز',
	send: 'إرسال  ',
	to: 'إلى',
	text: 'رسالة نصية',
	sms2send: 'تحتاج إلى إرسال رسالة نصية إلى ساعة اليد',
	cancelsend: 'حسنا ، سيتم الإرسال لاحقاً',
	alarmemail: 'تنبية عبر البريد الإلكتروني',
	viewinmap: 'عرض على الخريطة',
	exitnav: 'إنهاء التتبع',
	loadingtext: 'تحميل',
	locatefailed: 'غير قادر على تحديد الهاتف ، الرجاء تمكينه من إعدادات التطبيق',
	alarm1: 'الدخول إلى المنطقة الآمنة',
	alarm4: 'الخروج من المنطقة الآمنة',
	alarm2: 'إنذار بالطواريء',
	alarm8: 'إنذار بإنخفاض البطارية',
	alarm32: 'Watch detached',
	alarm64: 'إنذار السرعة',
	noalarm: 'عدم قراءة التنبيهات للآن',
	time: 'الوقت',
	address: 'العنوان',
	search: 'بحث ',
	nodata: 'لا يوجد بيانات',
	sosnumbers: 'أرقام الإتصال بالطواريء',
	whitelistnumbers: 'الأرقام المسموح لها بالإتصال بساعة اليد',
	deldevice: 'احذف هذا الجهاز',
	editprofile: 'اضغط لتعديل الملف الشخصي',
	phonenumbers: 'أرقام الهواتف',
	batterymode: 'تحديد الطريقة',
	emergencymode: 'إستخدام الوضع الآمن بتحديد الموقع كل 5 دقائق',
	savingmode: 'استخدام وضع توفير الطاقة بتحديد الموقع كل 10 دقائق',
	systemsetting: 'إعدادات النظام',
	youradvice: 'نصائح وشكاوي',
	timezone: 'منطقة الوقت',
	notificationtitle: 'منبه ساعة كيرف',
	lastestlocation: 'اخر موقع ',
	device_lang:  'Watch Language',
	volume:  'Watch Volume',
	usedst:  'Daylight saving time',
	socketmodeoff:  'Power saving mode',
	childpoweroff: 'الطفل يستطيع إيقاف الطاقة',
	retrieving: 'استرجاع',
	smsbyapp: 'بعض الاحداث تستدعي ارسال أمر نصي بواسطة هاتفك ، قد يتم إحتساب رسوم أضافية من المشغل',
	days2exipre: 'الأيام المتبقية لإنتهاء الصلاحية',
	exipred: 'ساعة اليد هذه إنتهت صلاحيتها',
	monthmsgremain: 'الرسائل الممكن إرسالها لهذا الشهر',
	isadding: 'هذه الساعة مضافة ، الرجاء المحاولة لاحقاً',
	alertsms: 'إرسال رسالة نصية للتنبيه',
	verifycodemsg: 'يجب سؤال المستخدم {}, عن رمز التحقق . هو/هي بإمكانه فتح التطبيق -> اعدادات-> (ساعة اليد)-> رمز التحقق',
	verifycode: 'رمز التحقق',
	verifycodetip: 'رمز التحقق تم إستخدامه للتحقق من مستخدم لإضافة ساعة اليد هذه ، الرجاء عرض رمز التحقق هذا فقط عندما يحدده المستخدم',
	version: 'الإصدار',
	ok: 'حسنا',
	done: 'فعله',
	cancel: 'إلغاء',
	msgcancelled: 'رسالة إلغاء',
	confirmpassword: 'تأكيد كلمة السر',
	confirmpasswordnotequal: 'تأكيد كلمة السر يجب أن نفس كلمة المرور',
	gps: 'GPS',
	tower: 'محطة قاعدة',
	wifi: 'واي فاي',
	phonetype0: 'آخر',
	phonetype1: 'الآب',
	phonetype2: 'أم',
	phonetype3: 'جدة',
	phonetype4: 'جد',
	phonetype5: 'زميل الدراسة',
	phonetype: 'اكتب',
	name: 'اسم',
	reenter: 'الرجاء إعادة إدخال',
	minichat: 'الأصوات',
	sendvoice: 'عقد والكلام',
	pulltorefresh: 'سحب لتحديث',
	me: 'أنا',
	unread: 'غير مقروء',
	holdtip: 'عقد والكلام، الحد الأقصى للطول 10 ثانية',
	voicetoolarge: 'يتجاوز صوت 10 ثانية، يرجى تسجيل مرة أخرى',
	novoice: 'لا أصوات حتى الآن',
	sending: 'إرسال...',
	recording: 'إعادة ترميز ... {الوقت}, ثانية (ق)',
	preparing: 'إستعد...',
	watchalarm: 'إنذار',
	watchalarmdetail: 'إعداد منبه',
	morning: 'مساء',
	afternoon: 'صباحا',
	today: 'اليوم',
	everyday: 'كل يوم',
	repeat: 'كرر',
	day0: 'شمس',
	day1: 'الإثنين',
	day2: 'الثلاثاء',
	day3: 'تزوج',
	day4: 'الخميس',
	day5: 'الجمعة',
	day6: 'السبت',
	alarm16: 'صوت جديد',
	confirmdeletealarm: 'تأكيد لحذف هذا التنبيه',
	noalarms: 'لا توجد أية إنذارات بعد، انقر على إضافة',
	smart: 'ذكي',
	starttime: 'وقت البدء',
	endtime: 'نهاية الوقت',
	contain: 'يحتوي',
	mynumber: 'رقم هاتفي',
	appqrcode: 'التطبيق رمز الاستجابة السريعة',
	dialbackno: 'رقم الهاتف لطلب العودة',
	moreadvancedsetting:  'Advanced Settings',
	hideself:  'Airplane Mode',
	hideselfdetail:  'Airplane Mode Settings',
	hideselfbegin:  'Start time:',
	hideselfend:  'End time:',
	nohidetimers: 'Add Airplane Mode Settings',
	invalidendtime: 'End time need greater than start time',
	enable: 'Open',
	twotimerconflict: 'Clash with following times：',

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  'New version',
	later:  'Later',
	upgrade:  'Upgrade',
	uptodate:  'Up to date',
	checkingupdate:  'Checking update...',


	disconnectedtips: 'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',

	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"أصدقاء الطفل",
	Nameoflocator:"اسم محدد الموقع",
	LocatorNumber:"رقم محدد",
    
    DeviceCode:"إصدار الجهاز",
	DeviceName:"اسم الجهاز",
    SpeedAlarm:"مسرعة الإنذار",
    ActivePositioningMode:"وضع تحديد الموقع النشط",
    DeviceNotFeature:"لا يدعم الجهاز هذه الميزة",
    RebootDevice:"إعادة تشغيل الجهاز",
    ResetDevice:"استعادة إعدادات المصنع",
    timeInterval:"الفاصل الزمني",
	IncludingPositioning:'يحتوي محطة قاعدة',
	Whether:'اذا كان هناك',
	Obtain:"الحصول على",
	Device:"جهاز",
	Transmission:"تم إرسالها إلى",
	PasswordRese:"فشل إعادة ضبط كلمة المرور. حاول مرة اخرى",
	GatorUseName:"",
    NameWatchShown:"الاسم الذي يظهر في الساعة",
    successfulActivation:"إعداد بنجاح",
	activationFailed: "إعداد دون جدوى",
	antiTheft:"وظيفة مكافحة السرقة",

}