//保加利亚语

module.exports = {
	exitconfirm: 'Потвърдете изход',
	noexitconfirm: 'Отново свикнал сигнал',
	login: 'Влизане',
	loginph: 'Email',
	regemail: 'Email използва се за вход и възстановите паролата си',
	pwdph: 'Парола',
	forgotpwd: 'Забравена парола?',
	reset: 'Нулиране на паролата',
	resetbtn: 'Нулиране',
	resetemail: 'Вашият регистриран Email',
	pwdreset: 'Новата парола беше изпратена на',
	register: 'Регистрирайте нов потребител',
	registerbtn: 'Регистрирайте се',
	invaliduser: 'Неправилно потребителско име и парола',
	locate: 'У дома',
	options: 'Settings',
	delete: 'Изтривам',
	logout: 'Излез От Профила Си',
	isempty: ' Не мога празна',
	taken: ' е бил регистриран, моля, опитайте с друг',
	invalidusername: 'Вашият имейл е невалиден',
	failed: 'Нещо не е наред, моля опитайте отново',
	success: 'успех',
	alarm: 'Аларма',
	alarmtitle: 'Алармени съобщения',
	navigate: 'Придвижване',
	startnav: 'Start Navigate',
	sos: 'Активирайте SOS режим',
	startmonitor: 'Активирайте Voice Monitor',
	locatenow: 'Намерете сега',
	confirmlocatesms: 'Трябва да изпратим текст, за да гледате, за да получите най-новата локация, потвърдете, за да изпратите?',
	sms: 'Изпратете SMS',
	history: 'История на местоположенията',
	mylocation: 'Моето местоположение',
	kidlocation: 'Kids Местоположение',
	startpoint: 'Отправна Точка',
	endpoint: 'Дестинация',
	addwatch: 'Добави оборудване',
	add: 'Добави',
	markasread: 'Маркирай Като Прочетено',
	morephonenumbers: 'Телефонни номера',
	recivesmsalert: 'Уведомление Alert',
	setupfence: 'Safezone',
	setupfence1: 'У дома',
	setupfence2: 'Училище',
	modifypwd: 'Промяна на парола',
	feedback: 'Обратна връзка',
	about: 'Около',
	back: 'Обратно',
	imei: 'IMEI',
	ownername: 'Child Име',
	petname:"името на животното",
	simid: 'оборудване Phone Number',
	simcountrycode:  'Country Code',
	soscountrycode:  'Country Code',
	phonenumbers: 'SOS телефонни номера',
	locateinterval: 'Time Interval на Първи Kid Позиция (М)',
	avatartxt: 'Въплъщение',
	historyalarm: 'История Alarm',
	save: 'Save',
	oldpwd: 'Стара Парола',
	newpwd: 'Нова Парола',
	submit: 'Подайте',
	invalidimei: 'Невалиден IMEI номер',
	dupaddwatch: 'Вие сте добавили този часовник',
	confirmremovedevice: 'Сигурни ли сте, че искате да премахнете този часовник? Вие няма да получавате съобщения от този часовник.',
	cancel: 'Отказ',
	from: 'Изберете Photo Източник',
	fromlib: 'Photo Library',
	fromcamera: 'Снимай',
	invalidoldpwd: 'Old Password не е правилна.',
	undefined: 'Неопределен',
	fencename: 'Име',
	radius: 'Радиус',
	meter: 'м',
	centerpoint: 'Center Point',
	send: 'Изпращам',
	to: 'Към',
	text: 'Текст',
	sms2send: 'Трябва да изпратите текстово да си часовник:',
	cancelsend: 'OK, аз ще го изпратите по-късно',
	alarmemail: 'Alarm Email',
	viewinmap: 'Виж в карта',
	exitnav: 'Exit Navigation',
	loadingtext: 'товарене',
	locatefailed: 'Не може да се намери телефон, моля да го разрешите в настройките за приложения',
	alarm1: 'Въведете Safe Zone',
	alarm4: 'Няма Safe Zone',
	alarm2: 'Аварийна сигнализация',
	alarm8: 'Low аларма батерията',
	alarm32: 'Watch detached',
	alarm64: 'Аларма за скорост',
	noalarm: 'Все още не можете да променяте аларми',
	time: 'Време',
	address: 'Адрес',
	search: 'Търсене',
	nodata: 'Няма Данни',
	sosnumbers: 'Номерата за спешни повиквания',
	whitelistnumbers: 'Бял списък може да се обадите часовник',
	deldevice: 'Изтрийте това устройство',
	editprofile: 'Изберете за промяна на профил',
	phonenumbers: 'Телефонни номера',
	batterymode: 'Намерете Mode',
	emergencymode: 'Safe Mode: Намерете за 5 минути',
	savingmode: 'Battery Saving Mode: Намерете за 10 минути',
	systemsetting: 'System Setting',
	youradvice: 'всякакви съвети, всеки се оплакват ...',
	timezone: 'Часова Зона',
	notificationtitle: 'Gator Watch Alarm',
	lastestlocation: 'Последни Намерете',
	device_lang:  'Watch Language',
	volume:  'Watch Volume',
	usedst:  'Daylight saving time',
	socketmodeoff:  'Power saving mode',
	childpoweroff: 'Детето може да се изключи захранването',
	retrieving: 'Изтегляне на ...',
	smsbyapp: 'Някои действия трябва да изпратите кратко команда текст, за да гледате от телефона си, това може да генерира комуникация такса.',
	days2exipre: ' ден (и) да е изтекъл',
	exipred: 'Този часовник е изтекла',
	monthmsgremain: 'Съобщения могат да изпращат този месец',
	isadding: ' е добавянето на този часовник, моля опитайте по-късно',
	alertsms: 'Изпратете SMS Когато Alarm',
	verifycodemsg: 'Трябва да попитате за употреба {}, за проверка на код. той / тя може да отвори АРР> Setting -> [Гледане] -> Проверка на кода',
	verifycode: 'Проверка на кода',
	verifycodetip: 'Проверка на кода, използван за проверка на потребителя, за да добавите този часовник, моля предложи този код само когато идентифицира потребителя.',
	version: 'версия',
	ok: 'ДОБРЕ',
	done: 'свършен',
	cancel: 'Отказ',
	msgcancelled: 'Съобщението анулиране',
	confirmpassword: 'Потвърди парола',
	confirmpasswordnotequal: 'Потвърди парола следва същите като Password',
	gps: 'GPS',
	tower: 'Base Station',
	wifi: 'Wifi',
	phonetype0: 'друг',
	phonetype1: 'баща',
	phonetype2: 'майка',
	phonetype3: 'баба',
	phonetype4: 'дядо',
	phonetype5: 'съученик',
	phonetype: 'Тип',
	name: 'име',
	reenter: 'Моля, въведете отново',
	minichat: 'Voices',
	sendvoice: 'Задръжте и Говори',
	pulltorefresh: 'Издърпайте да освежите',
	me: 'мен',
	unread: 'непрочетени',
	holdtip: 'Задръжте и Говори, макс дължина 10 секунди',
	voicetoolarge: 'Voice надвишава 10 секунди, моля запишете отново',
	novoice: 'Все още няма гласове',
	sending: 'Изпращане на ...',
	recording: 'Прекодиране ... {time}  време секунди (и)',
	preparing: 'Приготви се...',
	watchalarm: 'аларма',
	watchalarmdetail: 'Alarm Setting',
	morning: 'AM',
	afternoon: 'PM',
	today: 'днес',
	everyday: 'Всеки ден',
	repeat: 'повторение',
	day0: 'слънце',
	day1: 'Mon',
	day2: 'Tue',
	day3: 'Wed',
	day4: 'Thu',
	day5: 'Fri',
	day6: 'Sat',
	alarm16: 'New Voice',
	confirmdeletealarm: 'Потвърдете да изтриете тази аларма',
	noalarms: 'Не аларми, все още, щракнете, за да добавите',
	smart: 'умен',
	starttime: 'Начален час',
	endtime: 'End Time',
	contain: 'Съдържа',
	mynumber: 'Моят телефонен номер',
	appqrcode: 'App QR Code',
	dialbackno: 'Телефонен номер за набиране обратно',
	moreadvancedsetting:  'Advanced Settings',
	hideself:  'Airplane Mode',
	hideselfdetail:  'Airplane Mode Settings',
	hideselfbegin:  'Start time:',
	hideselfend:  'End time:',
	nohidetimers: 'Add Airplane Mode Settings',
	invalidendtime: 'End time need greater than start time',
	enable: 'Open',
	twotimerconflict: 'Clash with following times：',

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  'New version',
	later:  'Later',
	upgrade:  'Upgrade',
	uptodate:  'Up to date',
	checkingupdate:  'Checking update...',

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Приятели на детето",
	Nameoflocator:"Име на локатора",
	LocatorNumber:"Номер на локатора",
    
    DeviceCode:"Версия на устройството",
	DeviceName: "име на устройството",
    SpeedAlarm: "Ускоряване на алармата",
    ActivePositioningMode: "Активен режим на позициониране",
    DeviceNotFeature: "Устройството не поддържа тази функция",
    RebootDevice: "Рестартиране на устройството",
    ResetDevice: "Възстановяване на фабричните настройки",
    timeInterval: "интервал",
	IncludingPositioning:'Съдържа Base Station',
	Whether:'Дали има',
	Obtain:"Снабдете",
	Device:"приспособление",
	Transmission:"е изпратено до",
	PasswordRese:"Неуспешно възстановяване на паролата. Моля, опитайте отново",
	GatorUseName:"",
    NameWatchShown:"Името е показано на часовника",
    successfulActivation:"Настройте успешно",
	activationFailed: "Настройка безуспешно",
  antiTheft:"функция против кражба",
  
  systolic :'Систолично кръвно налягане',
diastolic:'Диастолично кръвно налягане',
power:'мощност',
pulseRate:'Пулсова честота',
oxygenSaturation:'Насищане на кръвта с кислород',
WeakPerfusion:'Индекс на слаба перфузия',
temperature:'Телесна температура',
healthSettings:'Настройки за здравето',
thermometer:'термометър',
oximeter:'оксиметър',
sphygmomanometer:'сфигмоманометър',
son:'син',
daughter:'дъщеря',
spouse:'Съпруг и съпруга',
ordinaryAlarm:'Обикновена аларма',
takeMedicine:'Вземете лекарство',
drinkWater:'Пийте вода',
sedentaryReminder:'Заседнало напомняне',
testReminder:'Напомняне за тест',
}