//希腊语

module.exports = {
	exitconfirm: 'Επιβεβαίωση εξόδου',
	noexitconfirm: 'Ειδοποίηση Συνηθισμένος ξανά',
	login: 'Σύνδεση',
	loginph: 'Email',
	regemail: 'Email χρησιμοποιείται για να συνδεθείτε και να επαναφέρετε τον κωδικό πρόσβασής σας',
	pwdph: 'Κωδικός',
	forgotpwd: 'Ξεχάσατε τον κωδικό?',
	reset: 'Επαναφέρετε τον κωδικό πρόσβασης',
	resetbtn: 'Επαναφορά',
	resetemail: 'Εγγεγραμμένο email σας',
	pwdreset: 'Ο νέος σας κωδικός έχει αποσταλεί',
	register: 'Εγγραφή νέου χρήστη',
	registerbtn: 'Εγγραφή',
	invaliduser: 'Λάθος όνομα χρήστη και τον κωδικό πρόσβασης',
	locate: 'Σπίτι',
	options: 'Ρυθμίσεις',
	delete: 'Διαγραφή',
	logout: 'Αποσύνδεση',
	isempty: ' δεν μπορούν άδειο',
	taken: ' έχει καταχωρηθεί, δοκιμάστε μια άλλη',
	invalidusername: 'Το email σας δεν είναι έγκυρο',
	failed: 'Κάτι λάθος, παρακαλώ προσπαθήστε ξανά',
	success: 'επιτυχία',
	alarm: 'Συναγερμός',
	alarmtitle: 'Μηνύματα συναγερμού',
	navigate: 'Πλοηγηθείτε',
	startnav: 'Έναρξη Πλοήγηση',
	sos: 'Ενεργοποιήστε τη λειτουργία SOS',
	startmonitor: 'Ενεργοποίηση φωνής Monitor',
	locatenow: 'Εντοπίστε Τώρα',
	confirmlocatesms: 'Πρέπει να στείλουμε το κείμενο να προσέξετε για να πάρει τελευταίες τοποθεσία, επιβεβαιώνουν την αποστολή',
	sms: 'Αποστολή SMS',
	history: 'Τοποθεσία Ιστορία',
	mylocation: 'Η τοποθεσία μου',
	kidlocation: 'Παιδιά Τοποθεσία',
	startpoint: 'Αφετηρία',
	endpoint: 'Προορισμός',
	addwatch: 'Προσθήκη συσκευής',
	add: 'Προσθήκη',
	markasread: 'Σημείωσε Ως Διαβασμένο',
	morephonenumbers: 'Τηλέφωνα',
	recivesmsalert: 'Alert Γνωστοποίηση',
	setupfence: 'SafeZone',
	setupfence1: 'Σπίτι',
	setupfence2: 'Σχολείο',
	modifypwd: 'Τροποποίηση Κωδικού',
	feedback: 'Ανατροφοδότηση',
	about: 'Σχετικά με',
	back: 'Πίσω',
	imei: 'IMEI',
	ownername: 'Παιδί Όνομα',
	petname:"Το όνομα του σκύλου",
	simid: 'Τηλέφωνο συσκευής',
	simcountrycode:  'Country Code',
	soscountrycode:  'Country Code',
	phonenumbers: 'SOS Τηλέφωνα',
	locateinterval: 'Χρονικό διάστημα του πάρει Kid Θέσης (Μ)',
	avatartxt: 'Avatar',
	historyalarm: 'Ιστορία Συναγερμός',
	save: 'Σώσει',
	oldpwd: 'Παλιος Κωδικος',
	newpwd: 'Νέος Κωδικός',
	submit: 'Υποβολή',
	invalidimei: 'Μη έγκυρος αριθμός IMEI',
	dupaddwatch: 'Έχετε προσθέσει αυτό το ρολόι',
	confirmremovedevice: 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το ρολόι Δεν θα λαμβάνετε μηνύματα από αυτό το ρολόι.',
	cancel: 'Ακύρωση',
	from: 'Επιλέξτε Φωτογραφία Πηγή',
	fromlib: 'Photo Library',
	fromcamera: 'Βγάλε μια φωτογραφία',
	invalidoldpwd: 'Παλιά Ο κωδικός πρόσβασης δεν είναι σωστή.',
	undefined: 'Απροσδιόριστος',
	fencename: 'Όνομα',
	radius: 'Ακτίνα',
	meter: 'm',
	centerpoint: 'Center Point',
	send: 'Αποστολή',
	to: 'Να',
	text: 'Κείμενο',
	sms2send: 'Θα πρέπει να στείλετε ένα μήνυμα κειμένου με το ρολόι σας:',
	cancelsend: 'Εντάξει, θα το στείλετε αργότερα',
	alarmemail: 'Συναγερμός Email',
	viewinmap: 'Δείτε το στο χάρτη',
	exitnav: 'Έξοδος πλοήγησης',
	loadingtext: 'φόρτωση',
	locatefailed: 'Ανίκανος να εντοπίσουν το τηλέφωνό σας, Παρακαλούμε ενεργοποιήστε το στις ρυθμίσεις της εφαρμογής',
	alarm1: 'Εισάγετε Safe Zone',
	alarm4: 'Από Safe Zone',
	alarm2: 'Επείγουσα συναγερμού',
	alarm8: 'Συναγερμός χαμηλής μπαταρίας',
	alarm32: 'Watch detached',
	alarm64: 'Συναγερμός ταχύτητας',
	noalarm: 'Δεν αδιάβαστη συναγερμούς ακόμα',
	time: 'Ώρα',
	address: 'Διεύθυνση',
	search: 'Έρευνα',
	nodata: 'Χωρίς Δεδομένα',
	sosnumbers: 'Οι αριθμοί κλήσης έκτακτης ανάγκης',
	whitelistnumbers: 'WHITELIST να καλέσετε το ρολόι',
	deldevice: 'Διαγράψτε αυτήν τη συσκευή',
	editprofile: 'Κάντε κλικ να επεξεργαστείτε το προφίλ',
	phonenumbers: 'Τηλέφωνα',
	batterymode: 'Εντοπίστε Λειτουργία',
	emergencymode: 'Safe Mode: Εντοπίστε σε 5 λεπτά',
	savingmode: 'Λειτουργία εξοικονόμησης μπαταρίας: Εντοπίστε σε 10 λεπτά',
	systemsetting: 'Ρύθμιση Συστήματος',
	youradvice: 'οποιαδήποτε συμβουλή, οποιοδήποτε παράπονο ...',
	timezone: 'Ζώνη Ώρας',
	notificationtitle: 'Gator ρολόι συναγερμών',
	lastestlocation: 'Τελευταία Εντοπισμός',
	device_lang:  'Watch Language',
	volume:  'Watch Volume',
	usedst:  'Daylight saving time',
	socketmodeoff:  'Power saving mode',
	childpoweroff: 'Παιδί μπορείτε να απενεργοποιήσετε',
	retrieving: 'Ανάκτηση ...',
	smsbyapp: 'Μερικά μέτρα πρέπει να στείλουν σύντομο κείμενο εντολή για να παρακολουθήσετε από το τηλέφωνό σας, αυτό μπορεί να δημιουργήσει τέλη επικοινωνίας.',
	days2exipre: ' ημέρα (s) για να λήξει',
	exipred: 'Αυτό το ρολόι έχει λήξει',
	monthmsgremain: 'Τα μηνύματα μπορεί να στείλει αυτό το μήνα',
	isadding: ' Είναι προσθέτοντας αυτό το ρολόι, παρακαλώ δοκιμάστε αργότερα',
	alertsms: 'Αποστολή SMS Όταν Συναγερμός',
	verifycodemsg: 'Θα πρέπει να ρωτήσετε το χρήστη {}, για την επαλήθευση κώδικα. αυτός / αυτή μπορεί να ανοίξει ΑΡΡ> Περιβάλλον -> [Ρολόι] -> Επιβεβαίωση κωδικού',
	verifycode: 'Επαλήθευση Κωδικού',
	verifycodetip: 'Επιβεβαίωση κωδικού που χρησιμοποιείται για την επαλήθευση των χρηστών για να προσθέσετε αυτό το ρολόι, παρακαλούμε να προσφέρουν αυτόν τον κωδικό μόνο όταν εντοπιστεί το χρήστη.',
	version: 'Έκδοση',
	ok: 'ΕΝΤΆΞΕΙ',
	done: 'Έγινε',
	cancel: 'Ακύρωση',
	msgcancelled: 'μήνυμα ακυρώσεις',
	confirmpassword: 'Επιβεβαίωση Κωδικού',
	confirmpasswordnotequal: 'Επιβεβαίωση κωδικού σε περίπτωση που η ίδια όπως Κωδικού',
	gps: 'GPS',
	tower: 'Σταθμού Βάσης',
	wifi: 'Wi-Fi',
	phonetype0: 'Άλλα',
	phonetype1: 'Πατέρας',
	phonetype2: 'Μητέρα',
	phonetype3: 'γιαγιά',
	phonetype4: 'Παππούς',
	phonetype5: 'Συμμαθητής',
	phonetype: 'Τύπος',
	name: 'Όνομα',
	reenter: 'Παρακαλώ εισάγετε ξανά',
	minichat: 'φωνές',
	sendvoice: 'Κρατήστε και Μίλα',
	pulltorefresh: 'Τραβήξτε για να ανανεώσετε',
	me: 'Μου',
	unread: 'Αδιάβαστος',
	holdtip: 'Κρατήστε και Μίλα, μέγιστο μήκος 10 δευτερόλεπτα',
	voicetoolarge: 'Φωνή υπερβαίνει τα 10 δευτερόλεπτα, καταγράφει και πάλι',
	novoice: 'Δεν υπάρχουν ακόμα φωνές',
	sending: 'Αποστολή ...',
	recording: 'Η εκ νέου κωδικοποίηση ... {time}  δευτερόλεπτα (s)',
	preparing: 'Ετοιμάσου...',
	watchalarm: 'Τρομάζω',
	watchalarmdetail: 'Ρύθμιση συναγερμού',
	morning: 'AM',
	afternoon: 'PM',
	today: 'Σήμερα',
	everyday: 'Καθε μερα',
	repeat: 'Επαναλαμβάνω',
	day0: 'Ήλιος',
	day1: 'Mon',
	day2: 'Τρ',
	day3: 'Νυμφεύω',
	day4: 'Πεμ',
	day5: 'Παρ',
	day6: 'Σάβ',
	alarm16: 'νέα Voice',
	confirmdeletealarm: 'Επιβεβαίωση να διαγράψετε αυτό το συναγερμό',
	noalarms: 'Δεν συναγερμούς ακόμα, κάντε κλικ στο κουμπί για να προσθέσετε',
	smart: 'Έξυπνος',
	starttime: 'Ωρα ΕΝΑΡΞΗΣ',
	endtime: 'Ώρα λήξης',
	contain: 'περιέχει',
	mynumber: 'Ο αριθμός τηλεφώνου μου',
	appqrcode: 'App QR Code',
	dialbackno: 'Αριθμό τηλεφώνου για να καλέσετε πίσω',

	moreadvancedsetting:  'Advanced Settings',
	hideself:  'Airplane Mode',
	hideselfdetail:  'Airplane Mode Settings',
	hideselfbegin:  'Start time:',
	hideselfend:  'End time:',
	nohidetimers: 'Add Airplane Mode Settings',
	invalidendtime: 'End time need greater than start time',
	enable: 'Open',
	twotimerconflict: 'Clash with following times：',

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',
	
	newappversion:  'New version',
	later:  'Later',
	upgrade:  'Upgrade',
	uptodate:  'Up to date',
	checkingupdate:  'Checking update...',

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Οι φίλοι του παιδιού",
	Nameoflocator:"Όνομα εντοπισμού",
	LocatorNumber:"Αριθμός εντοπισμού",
    
    DeviceCode:"Έκδοση συσκευής",
	DeviceName: "όνομα συσκευής",
    SpeedAlarm: "Επιτάχυνση συναγερμού",
    ActivePositioningMode: "Ενεργή λειτουργία εντοπισμού θέσης",
    DeviceNotFeature: "Η συσκευή δεν υποστηρίζει αυτή τη λειτουργία",
    RebootDevice: "Επανεκκίνηση συσκευής",
    ResetDevice: "Επαναφορά εργοστασιακών ρυθμίσεων",
    timeInterval: "διάστημα",
	IncludingPositioning:'περιέχει Σταθμού Βάσης',
	Whether:'Είτε υπάρχει',
	Obtain:"Αποκτώ",
	Device:"συσκευή",
	Transmission:"έχει σταλεί σε",
	PasswordRese:"Η επαναφορά κωδικού πρόσβασης απέτυχε. ΠΑΡΑΚΑΛΩ προσπαθησε ξανα",
	GatorUseName:"",
    NameWatchShown:"Όνομα που εμφανίζεται στο ρολόι",
    successfulActivation:"ρυθμίστηκε με επιτυχία",
	activationFailed: "ανεγέρθηκε ανεπιτυχώς",
	antiTheft:"αντικλεπτική λειτουργία",
}