//英语

module.exports = {
	exitconfirm: 'Confirm exit',
	noexitconfirm: 'Won\'t alert again',
	login: 'Login',
	loginph: 'Email',
	regemail: 'Email used to login and reset your password',
	pwdph: 'Password',
	forgotpwd: 'Forgot password?',
	reset: 'Reset password',
	resetbtn: 'Reset',
	resetemail: 'Your registered Email',
	pwdreset: 'new password was sent to ',
	register: 'Register new user',
	registerbtn: 'Register',
	invaliduser: 'Incorrect username and password',
	locate: 'Home',
	options: 'Settings',
	delete: 'Delete',
	logout: 'Logout',
	isempty: ' can not be empty',
	emailinvalid: ' Email is invalid',
	loginfailed: ' Login failed',
	taken: ' has been registered ,please try another',
	invalidusername: 'Your email is invalid',
	failed: 'Something went wrong. Please try again',
	success: 'Success',
	alarm: 'Alarm',
	alarmtitle: 'Alarms',
	navigate: 'Navigate',
	startnav: 'GO',
	sos: 'Activate SOS',
	startmonitor: 'Activate Voice Monitor',
	locatenow: 'Locate Now',
	confirmlocatesms: 'A SMS needs to be sent to the watch to update location. Confirm?',
	sms: 'Send SMS',
	history: 'Location History',
	mylocation: 'My Location',
	kidlocation: 'Kid\'s Location',
	startpoint: 'Starting Point',
	endpoint: 'Destination',
	addwatch: 'Add device',
	add: 'Add',
	markasread: 'Mark As Read',
	morephonenumbers: 'Phone Numbers',
	recivesmsalert: 'Alert Notification',
	setupfence: 'Safezones',
	setupfence1: 'Home',
	setupfence2: 'School',
	modifypwd: 'Modify Password',
	feedback: 'Feedback',
	about: 'About',
	back: 'Back',
	imei: 'IMEI',
	ownername: 'Child\'s Name',
	petname:"pet's Name",
	simid: 'Device Phone Number',
	simcountrycode: 'Country Code',
	soscountrycode: 'Country Code',
	phonenumbers: 'SOS Phone Numbers',
	locateinterval: 'Time Interval For Location Updates(M)',
	avatartxt: 'Photo',
	historyalarm: 'Alarm History',
	save: 'Save',
	oldpwd: 'Old Password',
	newpwd: 'New Password',
	submit: 'Submit',
	invalidimei: 'Invalid IMEI Number',
	dupaddwatch: 'You have successfully added this watch',
	confirmremovedevice: 'Are you sure you want to remove this watch? You will not receive any further messages from this watch.',
	cancel: 'Cancel',
	from: 'Select Photo Source',
	fromlib: 'Photo Library',
	fromcamera: 'Take a Photo',
	invalidoldpwd: 'Old Password is incorrect.',
	undefined: 'Undefined',
	fencename: 'Name',
	radius: 'Radius',
	meter: 'm',
	centerpoint: 'Center Point',
	send: 'Send',
	to: 'To',
	text: 'Text',
	sms2send: 'You need to send a text to your watch:',
	cancelsend: 'OK, I will send it later',
	alarmemail: 'Email Alerts',
	viewinmap: 'View in Map',
	exitnav: 'Exit Navigation',
	loadingtext: 'loading',
	locatefailed: 'Unable to locate the phone. Please enable it in app settings',
	alarm1: 'Enter ',
	alarm4: 'Out of ',
	alarm2: 'SOS Alert',
	alarm8: 'Low battery',
	alarm32: 'Watch detached',
	alarm64: 'Speed alarm',
	noalarm: 'No New Alerts',
	time: 'Time',
	address: 'Address',
	search: 'Search',
	nodata: 'No Data',
	sosnumbers: 'Emergency Call Numbers',
	whitelistnumbers: 'Whitelist Numbers',
	deldevice: 'Delete this device',
	editprofile: 'Go To Edit Profile',
	phonenumbers: 'Phone Numbers',
	batterymode: 'Locate Mode',
	emergencymode: 'Safe Mode:Location Updates Every 5 Minutes',
	savingmode: 'Battery Saving Mode:Location Updates Every 10 Minutes',
	systemsetting: 'System Setting',
	youradvice: '',
	timezone: 'Timezone (GMT)',
	notificationtitle: 'Gator Watch Alarm',
	lastestlocation: 'Latest Location',
	device_lang: 'Watch Language',
	volume: 'Watch Volume',
	usedst: 'Daylight saving time',
	socketmodeoff: 'Power saving mode',
	childpoweroff: 'Allow Child To Turn Watch Off',
	retrieving: 'Retrieving Now',
	smsbyapp: 'Some functions on the app require you to send an SMS to the watch. Please note you may incur additional network charges.',
	days2exipre: ' day(s) to expired',
	exipred: 'This watch has expired',
	monthmsgremain: 'Messages can send this month',
	isadding: ' is adding this watch, please try later',
	alertsms: 'Send SMS When SOS Activated',
	verifycodemsg: 'You should ask user {}, for verification code. Go to app->Setting->[Watch]->Verification Code',
	verifycode: ' Verification Code',
	verifycodetip: 'Use Verification Code to authorize other Gator App users to add this watch',
	version: 'Version',
	ok: 'OK',
	done: 'Done',
	cancel: 'Cancel',
	msgcancelled: 'Message cancelled',
	confirmpassword: 'Confirm Password',
	confirmpasswordnotequal: 'Password do not match, please try again',
	gps: 'GPS',
	tower: 'Base Stations',
	wifi: 'Wifi',
	phonetype0: 'Other',
	phonetype1: 'Father',
	phonetype2: 'Mother',
	phonetype3: 'Grandma',
	phonetype4: 'Grandpa',
	phonetype5: 'Classmate',
	phonetype: 'Relation',
	name: 'Name',
	reenter: 'Please re-enter',
	minichat: 'Voicemail',
	sendvoice: 'Hold and Record',
	pulltorefresh: 'Pull to refresh',
	me: 'Me',
	unread: 'UnRead',
	holdtip: 'Hold and Record,max length 10 seconds',
	voicetoolarge: 'Voice exceeds 10 seconds,please record again',
	novoice: 'No voice messages',
	sending: 'Sending...',
	recording: 'Recording...{time} seconds(s)',
	preparing: 'Get ready...',
	watchalarm: 'Alarm',
	watchalarmdetail: 'Alarm Setting',
	morning: 'AM',
	afternoon: 'PM',
	today: 'Today',
	everyday: 'Everyday',
	repeat: 'Repeat',
	day0: 'Sun',
	day1: 'Mon',
	day2: 'Tue',
	day3: 'Wed',
	day4: 'Thu',
	day5: 'Fri',
	day6: 'Sat',
	alarm16: 'New Voice Message',
	confirmdeletealarm: 'Confirm to delete this alarm',
	noalarms: 'No alarms yet,click to add',
	smart: 'Smart',
	starttime: 'Start Time',
	endtime: 'End Time',
	contain: 'Including',
	mynumber: 'My phone number',
	appqrcode: 'App QRCode',
	dialbackno: 'Phone number to dial back',
	notsupported: 'Your watch does not support voice',
	moreadvancedsetting: 'Advanced Settings',
	hideself: 'Airplane Mode',
	hideselfdetail: 'Airplane Mode Settings',
	hideselfbegin: 'Start time:',
	hideselfend: 'End time:',
	nohidetimers: 'Add Airplane Mode Settings',
	invalidendtime: 'End time need greater than start time',
	enable: 'Activate',
	twotimerconflict: 'Clash with following times：',

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion: 'New version',
	later: 'Later',
	upgrade: 'Upgrade',
	uptodate: 'Up to date',
	checkingupdate: 'Checking update...',

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
	commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',
	
	friends:"Child\'s friends",
	Nameoflocator:"Name of locator",
	LocatorNumber:"Locator number",
    
    DeviceCode:"Disponebla versio",
	DeviceName: "device name",
    SpeedAlarm: "Speeding Alarm",
    ActivePositioningMode: "Active Positioning Mode",
    DeviceNotFeature: "The device does not support this feature",
    RebootDevice: "Device restart",
    ResetDevice: "Restore factory settings",
    timeInterval: "interval",
	IncludingPositioning:'Including Base Stations',
	Whether:'Whether there is',
	Obtain:"Obtain",
	Device:"Device",
	Transmission:"has been sent to",
	PasswordRese:"Password reset failed. Please try again",
	GatorUseName:"",
    NameWatchShown:"Name shown on watch",
    successfulActivation:"Set up successfully",
	activationFailed: "Set up unsuccessfully",
	antiTheft:"anti-theft function",
	
}