//世界语

module.exports = {
	exitconfirm: 'Konfirmi eliro',
	noexitconfirm: 'Kunvenejo alarmas denove',
	login: 'Salutnomo',
	loginph: 'Retpoŝto',
	regemail: 'Retpoŝto uzis por ensaluti kaj reagordi vian pasvorton',
	pwdph: 'Pasvorto',
	forgotpwd: 'Forgesis pasvorton?',
	reset: 'Reset pasvorton',
	resetbtn: 'Restarigi',
	resetemail: 'Via registrita Retpoŝto',
	pwdreset: 'Via nova pasvorto estis sendita al',
	register: 'Registri novan uzanton',
	registerbtn: 'Register',
	invaliduser: 'Malĝustan uzulnomon kaj pasvorton',
	locate: 'Hejmo',
	options: 'Agordoj',
	delete: 'Forigi',
	logout: 'Elsaluti',
	isempty: ' neniom malplena',
	taken: ' estis registritaj, bonvolu provi alian',
	invalidusername: 'Via retpoŝta estas nevalida',
	failed: 'Io malĝustas, bonvolu provi denove',
	success: 'sukceso',
	alarm: 'Alarmo',
	alarmtitle: 'Alarmo Mesaĝoj',
	navigate: 'Navigi',
	startnav: 'Komenco navigi',
	sos: 'Aktivigi SOS reĝimo',
	startmonitor: 'Aktivigi Voĉo Monitoro',
	locatenow: 'Lokalizi Nun',
	confirmlocatesms: 'Ni devas sendi tekston rigardi akiri lasta situo, konfirmi sendi?',
	sms: 'Send SMS',
	history: 'Situo Historio',
	mylocation: 'Mia Loko',
	kidlocation: 'Infanoj Loko',
	startpoint: 'Komencante Punkton',
	endpoint: 'Destination',
	addwatch: 'Aldoni aparaton',
	add: 'Aldoni',
	markasread: 'Mark Kiel Legi',
	morephonenumbers: 'Telefono Nombroj',
	recivesmsalert: 'Garde Anoncon',
	setupfence: 'Safezone',
	setupfence1: 'Hejmo',
	setupfence2: 'Lernejo',
	modifypwd: 'Modifi Pasvorto',
	feedback: 'Retroefiko',
	about: 'Pri',
	back: 'Reen',
	imei: 'IMEI',
	ownername: 'Infano Nomo',
	petname:"Nome do animal",
	simid: 'Ekipaĵo Telefonnumero',
	simcountrycode:  'Country Code',
	soscountrycode:  'Country Code',
	phonenumbers: 'SOS Phone Nombroj',
	locateinterval: 'Tempo Intertempo de Getting Kid Pozicio (M)',
	avatartxt: 'Avatar',
	historyalarm: 'Historio Alarmo',
	save: 'Konservi',
	oldpwd: 'Malnova Pasvorto',
	newpwd: 'Novaj Pasvorto',
	submit: 'Afiŝu',
	invalidimei: 'Nevalida IMEI Numero',
	dupaddwatch: 'Vi aldonis tiun horloĝon',
	confirmremovedevice: 'Ĉu vi vere volas forigi tiun horloĝon? Vi ne ricevos ajnan mesaĝojn de ĉi tiu horloĝo.',
	cancel: 'Rezignu',
	from: 'Elektu Foto Fonto',
	fromlib: 'Foto Biblioteko',
	fromcamera: 'Prenu foton',
	invalidoldpwd: 'Malnova pasvorto ne ĝustas.',
	undefined: 'Nedifinita',
	fencename: 'Nomo',
	radius: 'Radiuso',
	meter: 'm',
	centerpoint: 'Centro Punkto',
	send: 'Sendu',
	to: 'Por',
	text: 'Teksto',
	sms2send: 'Vi devas sendi tekston al via servo:',
	cancelsend: 'OK, mi sendos ĝin poste',
	alarmemail: 'Alarmo Retpoŝto',
	viewinmap: 'Vidi en mapo',
	exitnav: 'Eliro Navigado',
	loadingtext: 'ŝarĝo',
	locatefailed: 'Nekapabla lokalizi la telefonon, Bonvolu aktivigi ĝin en app agordojn',
	alarm1: 'Eniri Safe Zone',
	alarm4: 'Ek Safe Zone',
	alarm2: 'Kriz Alarmo',
	alarm8: 'Malalta pilo alarmo',
	alarm32: 'Watch detached',
	alarm64: 'Rapida alarmo',
	noalarm: 'Neniu nelegita alarmoj ankoraŭ',
	time: 'Tempo',
	address: 'Adreso',
	search: 'Serĉo',
	nodata: 'Neniu Datumo',
	sosnumbers: 'Kriz Alvoko Nombroj',
	whitelistnumbers: 'Whitelist povas nomi Watch',
	deldevice: 'Forigu ĉi tiun aparaton',
	editprofile: 'Click To Redaktu Profilo',
	phonenumbers: 'Telefono Nombroj',
	batterymode: 'Lokalizi Mode',
	emergencymode: 'Sekura Mode: Loki en 5 minutoj',
	savingmode: 'Kuirilaro Ŝparado Mode: Loki en 10 minutoj',
	systemsetting: 'Sistemo Agordo',
	youradvice: 'ajna konsilo, neniu plendas ...',
	timezone: 'Horzonon',
	notificationtitle: 'Gator Watch Alarmo',
	lastestlocation: 'Plej Loki',
	device_lang:  'Watch Language',
	volume:  'Watch Volume',
	usedst:  'Daylight saving time',
	socketmodeoff:  'Power saving mode',
	childpoweroff: 'Child Can Power Off',
	retrieving: 'Ekprenante ...',
	smsbyapp: 'Iuj ago devas sendi mallongan tekston komando rigardi per via telefono, Tio povas generi komunikado kotizon.',
	days2exipre: ' tago (j) al kadukaj',
	exipred: 'Ĉi tiu horloĝo ĝi eksvalidiĝis',
	monthmsgremain: 'Mesaĝoj povas sendi ĉimonate',
	isadding: ' estas aldonante tiun horloĝon, bonvolu provi poste',
	alertsms: 'Sendi SMS Kiam Alarmo',
	verifycodemsg: 'Vi devus demandi uzanto {}, por kontroli kodon. li / ŝi povas malfermi app-> Agordo -> [Watch] -> Kontroli Kodo',
	verifycode: 'Kontroli Kodo',
	verifycodetip: 'Kontroli Kodo uzata por kontroli uzanto aldoni tiun horloĝon, bonvolu proponi ĉi kodo nur kiam uzanto identigita.',
	version: 'versio',
	ok: 'OK',
	done: 'Donacu',
	cancel: 'Rezignu',
	msgcancelled: 'Mesaĝo nuligita',
	confirmpassword: 'konfirmi Pasvorton',
	confirmpasswordnotequal: 'Konfirmi Pasvorton devus la sama kiel Pasvorto',
	gps: 'GPS',
	tower: 'bazo Stacidomo',
	wifi: 'Wifi',
	phonetype0: 'aliaj',
	phonetype1: 'patro',
	phonetype2: 'patrino',
	phonetype3: 'Grandma',
	phonetype4: 'avo',
	phonetype5: 'kompan-kompano',
	phonetype: 'Tipo',
	name: 'nomo',
	reenter: 'Bonvolu re-eniri',
	minichat: 'voĉoj',
	sendvoice: 'Tenu kaj Speak',
	pulltorefresh: 'Pull refreŝigi',
	me: 'min',
	unread: 'nelegita',
	holdtip: 'Tenu kaj Speak, maks longo 10 sekundoj',
	voicetoolarge: 'Voĉo superas 10 sekundojn, bonvolu gravuri denove',
	novoice: 'Neniu voĉoj ankoraŭ',
	sending: 'Sendante ...',
	recording: 'Recoding ... {time}  sekundoj (s)',
	preparing: 'Preparu...',
	watchalarm: 'alarmo',
	watchalarmdetail: 'alarmo Setting',
	morning: 'AM',
	afternoon: 'PM',
	today: 'hodiaŭ',
	everyday: 'Ĉiutage',
	repeat: 'Ripetu',
	day0: 'suno',
	day1: 'Mon',
	day2: 'tue',
	day3: 'Wed',
	day4: 'Thu',
	day5: 'fri',
	day6: 'Sat',
	alarm16: 'nova Voĉo',
	confirmdeletealarm: 'Konfirmi forviŝi ĉi alarmo',
	noalarms: 'Neniu alarmoj ankoraŭ, klaku aldoni',
	smart: 'inteligenta',
	starttime: 'Start Time',
	endtime: 'fino Tempo',
	contain: 'enhavas',
	mynumber: 'Mia telefonnumero',
	appqrcode: 'App QR Kodo',
	dialbackno: 'Telefonnumero diski reen',
	moreadvancedsetting:  'Advanced Settings',
	hideself:  'Airplane Mode',
	hideselfdetail:  'Airplane Mode Settings',
	hideselfbegin:  'Start time:',
	hideselfend:  'End time:',
	nohidetimers: 'Add Airplane Mode Settings',
	invalidendtime: 'End time need greater than start time',
	enable: 'Open',
	twotimerconflict: 'Clash with following times：',

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  'New version',
	later:  'Later',
	upgrade:  'Upgrade',
	uptodate:  'Up to date',
	checkingupdate:  'Checking update...',

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
	commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Amikoj de infano",
	Nameoflocator:"Nomo de lokigilo",
	LocatorNumber:"Lokigilo nombro",
    
    DeviceCode:"Disponebla versio",
	DeviceName: "nomo de aparato",
    SpeedAlarm: "Rapida Alarmo",
    ActivePositioningMode: "Aktiva Pozicia Modo",
    DeviceNotFeature: "La aparato ne subtenas ĉi tiun funkcion",
    RebootDevice: "Device restart",
    ResetDevice: "Restarigi fabrikajn agordojn",
    timeInterval: "intervalo",
	IncludingPositioning:'enhavas bazo Stacidomo',
	Whether:'Ĉu ekzistas',
	Obtain:"Akiri",
	Device:"mekanismo",
	Transmission:"estis sendita al",
	PasswordRese:"Pasvorto reset malsukcesis. Bonvolu reprovi",
	GatorUseName:"",
    NameWatchShown:"Nomo montrita en servo",
    successfulActivation:"starigis sukcese",
	activationFailed: "starigis malsukcese",
	antiTheft:"kontraŭtrova funkcio",
}