//西班牙语
module.exports = {
	exitconfirm: '¿Confirmar salida?',
	noexitconfirm: 'No volver a enviar alerta',
	login: 'Iniciar Sesión',
	loginph: 'Email',
	regemail: 'Email utilizado para iniciar sesión y reiniciar su contraseña',
	pwdph: 'Contraseña',
	forgotpwd: '¿Has olvidado tu contraseña?',
	reset: 'Reiniciar la contraseña',
	resetbtn: 'Reiniciar ',
	resetemail: 'E-mail registrado',
	pwdreset: 'Tu nueva contraseña ha sido enviada a',
	register: 'Registrar nuevo usuario',
	registerbtn: 'Registrarse',
	invaliduser: 'Nombre de usuario y contraseña incorrectos',
	locate: 'Inicio',
	options: 'Ajustes',
	delete: 'Borrar',
	logout: 'Cerrar Sesión',
	isempty: 'no puede vaciar',
	taken: 'ya se ha registrado, por favor, prueba con otro',
	invalidusername: 'tu email es inválido',
	failed: 'Error, por favor inténtalo de nuevo',
	success: 'éxito',
	alarm: 'Alarma',
	alarmtitle: 'Mensajes de alarma',
	navigate: 'Navegar',
	startnav: 'Ir',
	sos: 'Activar el modo de SOS',
	startmonitor: 'Activar control de voz',
	locatenow: 'Localizar ahora',
	confirmlocatesms: 'Tenemos que enviar un SMS al reloj para actualizar su localización , confirmamos el envió?',
	sms: 'Enviar SMS',
	history: 'Historial',
	mylocation: 'Mi ubicación',
	kidlocation: 'Ubicación niño',
	startpoint: 'Punto de inicio',
	endpoint: 'Destino',
	addwatch: 'Agregar dispositivo',
	add: 'Añadir',
	markasread: 'Marcar como Leído',
	morephonenumbers: 'Números de teléfono',
	recivesmsalert: 'Notificación de alerta',
	setupfence: 'Zona Segura',
	setupfence1: 'Casa',
	setupfence2: 'Colegio',
	modifypwd: 'Modificar la contraseña',
	feedback: 'Comentarios',
	about: 'Info',
	back: 'Atrás',
	imei: 'IMEI',
	ownername: 'Nombre del Niño',
	simid: 'Teléfono Equipo',
	simcountrycode:  'Código pais',
	soscountrycode:  'Código país',
	phonenumbers: 'Números SOS ',
	locateinterval: 'Intervalo de tiempo para localizar la posición (M)',
	avatartxt: 'Avatar',
	historyalarm: 'Historial de alertas',
	save: 'Guardar',
	oldpwd: 'Antigua contraseña',
	newpwd: 'Nueva Contraseña',
	submit: 'Enviar',
	invalidimei: 'Número IMEI inválido ',
	dupaddwatch: 'Has añadido este reloj',
	confirmremovedevice: '¿Confirmas que quieres eliminar este reloj? No recibirá ningún mensaje de este reloj.',
	cancel: 'Cancelar',
	from: 'Seleccionar Foto',
	fromlib: 'Galería',
	fromcamera: 'Sacar foto',
	invalidoldpwd: 'Esta contraseña no es correcta.',
	undefined: 'Indefinido',
	fencename: 'Nombre',
	radius: 'Radio',
	meter: 'm',
	centerpoint: 'Punto Central',
	send: 'Enviar',
	to: 'A',
	text: 'Texto',
	sms2send: 'Necesita enviar un texto a su reloj:',
	cancelsend: 'Bien, voy a enviarlo más tarde',
	alarmemail: 'Alerta por correo electrónico',
	viewinmap: 'Ver en el mapa',
	exitnav: 'Salir de Navegación',
	loadingtext: 'cargando',
	locatefailed: 'No se puede localizar el teléfono, por favor activa esta configuración en la app',
	alarm1: 'Introducir una zona segura',
	alarm4: 'Fuera de la zona segura',
	alarm2: 'Alerta de Emergencia',
	alarm8: 'Alerta de batería baja',
	alarm32: 'Reloj desconectado',
	alarm64: 'Alarma de velocidad',
	noalarm: 'No existen alertas',
	time: 'Tiempo',
	address: 'Dirección',
	search: 'Búsqueda',
	nodata: 'Sin Datos',
	sosnumbers: 'Números de Emergencia de llamada',
	whitelistnumbers: 'Números autorizados a llamar al reloj',
	deldevice: 'Eliminar este reloj',
	editprofile: 'Haga clic para editar el perfil',
	phonenumbers: 'Números de teléfono',
	batterymode: 'Modo Localizar',
	emergencymode: 'Modo seguro: Localiza en 5 minutos',
	savingmode: 'Modo de ahorro de batería: Actualiza cada 10 minutos',
	systemsetting: 'Configuración del sistema',
	youradvice: 'tu consejo/ queja ...',
	timezone: 'Zona horaria',
	notificationtitle: 'Gator reloj de alarma',
	lastestlocation: 'Últimas localizaciones',
	device_lang:  'Idioma del reloj',
	volume:  'Volumen del reloj',
	usedst:  'Horario de verano',
	socketmodeoff:  'Modo ahorro',
	childpoweroff: 'Autorizar niño apagar reloj',
	retrieving: 'Recuperando ...',
	smsbyapp: 'Algunas funciones requieren enviar un SMS al reloj esto genera un gasto adicional.',
	days2exipre: ' día (s) para expiración',
	exipred: 'Este reloj ya no existe',
	monthmsgremain: 'mensajes pueden enviar este mes',
	isadding: ' esta añadiendo este reloj, por favor intenta más tarde',
	alertsms: 'Enviar SMS cuando el SOS esta activado',
	verifycodemsg: 'Pide al usuario {}, el  código de verificación. Abrir app-> Configuración -> [Reloj] -> Código de verificación',
	verifycode: 'Código De verificación',
	verifycodetip: 'Utilizar el código de verificación para autorizar otro usuario a añadir este reloj, por favor comunicar este código sólo cuando el usuario este identificado.',
	version: 'versión',
	ok: 'OK',
	done: 'Hecho',
	cancel: 'cancelar',
	msgcancelled: 'Mensaje cancelado',
	confirmpassword: 'Confirmar contraseña',
	confirmpasswordnotequal: 'las contraseñas no coinciden, intentarlo de nuevo',
	gps: 'GPS',
	tower: 'Estación base',
	wifi: 'Wifi',
	phonetype0: 'Otro',
	phonetype1: 'Padre',
	phonetype2: 'Madre',
	phonetype3: 'abuela',
	phonetype4: 'Abuelo',
	phonetype: 'Relación',
	name: 'Nombre',
	reenter: 'Por favor, vuelve a introducir',
	minichat: 'Buzón de voz',
	sendvoice: 'Mantener pulsado y Hablar',
	pulltorefresh: 'Deslizar hacía arriba para actualizar',
	me: 'Yo',
	unread: 'No leído',
	holdtip: 'Mantener pulsado y Hablar, duración max de 10 segundos',
	voicetoolarge: 'Mensaje supera los 10 segundos, por favor graba de nuevo',
	novoice: 'No hay mensajes',
	sending: 'Enviando...',
	recording: 'Grabando ... {time}  segundos (s)',
	preparing: 'Preparate...',
	watchalarm: 'Alarma',
	watchalarmdetail: 'Ajuste de alarma',
	morning: 'AM',
	afternoon: 'PM',
	today: 'hoy',
	everyday: 'Cada día',
	repeat: 'Repetir',
	day0: 'Domingo',
	day1: 'Lunes',
	day2: 'Martes',
	day3: 'Miércoles',
	day4: 'Jueves',
	day5: 'Viernes',
	day6: 'Sabado',
	alarm16: 'Nuev mensaje',
	confirmdeletealarm: 'Confirmar eliminar esta alarma',
	noalarms: 'No hay alarmas aún, haz clic para añadir',
	smart: 'Smart',
	starttime: 'Hora de inicio',
	endtime: 'Hora de finalización',
	contain: 'contiene',
	mynumber: 'Mi número de teléfono',
	appqrcode: 'App Código QR',
	dialbackno: 'Número de teléfono para marcar de vuelta',
	moreadvancedsetting:  'Ajustes avanzados',
	hideself:  'Modo Avión',
	hideselfdetail:  'Ajustes modo Avion',
	hideselfbegin:  'Hora de inicio:',
	hideselfend:  'Hora final',
	nohidetimers: 'Añdir ajustes modo avion',
	invalidendtime: 'Hora final tiene que ser más tarde que hora de inicio',
	enable: 'Activar',
	twotimerconflict: 'las horas siguientes no coinciden',
	homewifisetting: 'Ajustes zona WiFi',
	homewificomments: "Por favour selecciona un punto de acceso WiFi en tu zona segura. Si el WiFi no aparece en la lista siguiente, click \'Cancelar\'",
	accuracy: 'Accuracy',
	newappversion:  "Nueva version",
	later:  "Mas tarde",
	upgrade:  "actualizar",
	uptodate:  "actualizado",
	checkingupdate:  "Comprobando actualización...",
	disconnectedtips:  "Conectando al servidor por facvor espera...",
	uploadfailed: "Error de descarga",
	lightbulb: "Light bulb",
	invalid: "Incorrecto",
	phonelistisfull: "Limite de números de teléfono alcanzado",
	serverinternalerror: "error interno de servidor",
	addwatchtimeout: "Límite de tiempo alcanzado Añadir reloj",
	deletewatchtimeout: "Límite de tiempo alcanzado Suprimir reloj",
	registertimeout: "Límite de tiempo alcanzado para registrase",
	registerfailed: "Error de registración",
	failed: "error",
	timeout: "límite de tiempo alcanzado",
	activedevice: "conectar reloj",
	familynumbernotfound: "número de teléfono no encontrado",
	updating: "Actualizando...",
	disablewifilocation: "Desactivar localizacion WiFi",
	locatenowtips: "Haz click para actualizar la localización del usuario. Tendrá que enviar un SMS al reloj.",
	confirmsendsmstoactive: "El reloj se ha desconectado temporalmente del servidor. Enviar un SMS para forzarlo a enviar la localización inmediatamente",
	inputfencename: "Entrar nombre zona segura",
	agreeprivacypolicy: "Se declara conforme con ",
	privacypolicytitle: "Politica de privacidad",
	passwordruletips: "Las contraseñas necesitan tener por lo menos 8 caracteres e incluir un número, una mayúscula y una minúscula ",
	passworderror: "error contraseña!",
	passworderror5: "Has entrado una contraseña incorrecta, por favor inténtalo de nuevo en un minuto",
	addAccount:"Añadir permisos de administradores",
	notAccount:"No autorizado!",
	overlimitNumber: "Limite superado para añadir número",
    Pleaseconfirm:"Please confirm",
    commonsecret: "The password is the same, please retype",
    phonetype5: "Compañero clase",
    petname:"Nombre de la mascota",
	friends:"Amigos del niño",
	Nameoflocator:"Nombre del localizador",
	LocatorNumber:"Número localizador",
    
    DeviceCode:"Versión del dispositivo",
    DeviceName: "nombre del dispositivo",
    SpeedAlarm: "Alarma de exceso de velocidad",
    ActivePositioningMode: "Modo de posicionamiento activo",
    DeviceNotFeature: "El dispositivo no es compatible con esta función",
    RebootDevice: "Reinicio del dispositivo",
    ResetDevice: "Restaurar configuración de fábrica",
    timeInterval: "intervalo",
	IncludingPositioning:'contiene Estación base',
	Whether:'Si existe',
	Obtain:"Obtener",
	Device:"dispositivo",
	Transmission:"ha sido enviado a",
	PasswordRese:"Error al restablecer la contraseña. Inténtalo de nuevo",
	GatorUseName:"",
    NameWatchShown:"Nombre mostrado en el reloj",
    successfulActivation:"configurar con éxito",
	activationFailed: "configurar sin éxito",
  antiTheft:"función antirrobo",
  
  systolic :'Presión arterial sistólica',
diastolic:'Presión arterial diastólica',
power:'Poder',
pulseRate:'Frecuencia de pulso',
oxygenSaturation:'Saturación de oxígeno en sangre',
WeakPerfusion:'Índice de perfusión débil',
temperature:'Temperatura corporal',
healthSettings:'Ajustes de salud',
thermometer:'Termómetro',
oximeter:'Oxímetro',
sphygmomanometer:'Esfigmomanómetro',
son:'Hijo',
daughter:'Hija',
spouse:'Esposo y esposa',
ordinaryAlarm:'Alarma ordinaria',
takeMedicine:'Tomar medicina',
drinkWater:'Beber agua',
sedentaryReminder:'Recordatorio sedentario',
testReminder:'Recordatorio de prueba',
}
