//芬兰语

module.exports = {
	exitconfirm: 'Vahvista exit',
	noexitconfirm: 'Wont hälytys uudelleen',
	login: 'Kirjaudu',
	loginph: 'Sähköposti',
	regemail: 'Email käytetään kirjautua sisään ja palauttaa salasanan',
	pwdph: 'Salasana',
	forgotpwd: 'Unohtuiko salasana?',
	reset: 'Nollaa salasana',
	resetbtn: 'Asettaa uudelleen',
	resetemail: 'Rekisteröidyn sähköpostin',
	pwdreset: 'Uusi salasanasi on lähetetty',
	register: 'Rekisteröidy uusi käyttäjä',
	registerbtn: 'Rekisteröidy',
	invaliduser: 'Väärä käyttäjätunnus ja salasana',
	locate: 'Koti',
	options: 'Asetukset',
	delete: 'Poistaa',
	logout: 'Kirjaudu ulos',
	isempty: ' ei voi tyhjä',
	taken: ' on rekisteröity, kokeile toista',
	invalidusername: 'Sähköpostiosoitteesi on virheellinen',
	failed: 'Jotain vikaa, yritä uudelleen',
	success: 'menestys',
	alarm: 'Hälytys',
	alarmtitle: 'Hälytys Viestit',
	navigate: 'Navigoida',
	startnav: 'Start Siirry',
	sos: 'Aktivoi SOS-tila',
	startmonitor: 'Aktivoi puheenseuranta',
	locatenow: 'Etsi nyt',
	confirmlocatesms: 'Meidän täytyy lähettää tekstiviestejä katsomaan saada uusimmat sijainnin, vahvista lähettää?',
	sms: 'Lähetä tekstiviesti',
	history: 'Sijainti Historia',
	mylocation: 'Oma sijainti',
	kidlocation: 'Lapset Sijainti',
	startpoint: 'Lähtökohta',
	endpoint: 'Määränpää',
	addwatch: 'Lisää laite',
	add: 'Lisätä',
	markasread: 'Merkitse luetuksi',
	morephonenumbers: 'Puhelinnumerot',
	recivesmsalert: 'Alert Ilmoitus',
	setupfence: 'Safezone',
	setupfence1: 'Koti',
	setupfence2: 'Koulu',
	modifypwd: 'Muokkaa salasana',
	feedback: 'Palaute',
	about: 'Noin',
	back: 'Takaisin',
	imei: 'IMEI',
	ownername: 'Lapsi Name',
	petname:"lemmikin Name",
	simid: 'laitteet puhelinnumero',
	simcountrycode:  'Country Code',
	soscountrycode:  'Country Code',
	phonenumbers: 'SOS Puhelinnumerot',
	locateinterval: 'Time Interval of Getting Kid kannan (M)',
	avatartxt: 'Avatar',
	historyalarm: 'Historia Hälytys',
	save: 'Tallenna',
	oldpwd: 'Vanha salasana',
	newpwd: 'Uusi salasana',
	submit: 'Esittää',
	invalidimei: 'Virheellinen IMEI Number',
	dupaddwatch: 'Olet lisännyt tämän rannekellon',
	confirmremovedevice: 'Oletko varma, että haluat poistaa tämän katsella? Et saa viestit tämän kellon.',
	cancel: 'Peruuttaa',
	from: 'Valitse Photo Source',
	fromlib: 'Photo Library',
	fromcamera: 'Take a Photo',
	invalidoldpwd: 'Vanha salasana ei ole oikein.',
	undefined: 'Määrittelemätön',
	fencename: 'Nimi',
	radius: 'Säde',
	meter: 'm',
	centerpoint: 'Center Point',
	send: 'Lähettää',
	to: 'To',
	text: 'Teksti',
	sms2send: 'Sinun täytyy lähettää tekstin kellosi:',
	cancelsend: 'OK, minä lähetän sen myöhemmin',
	alarmemail: 'Hälytys Sähköposti',
	viewinmap: 'Näkymä Kartta',
	exitnav: 'Exit Navigation',
	loadingtext: 'lastaus',
	locatefailed: 'Ei löydy puhelimeen, Salli sen sovelluksen asetukset',
	alarm1: 'Anna Safe Zone',
	alarm4: 'Out of Safe Zone',
	alarm2: 'Emergency Hälytys',
	alarm8: 'Alhainen pariston hälytys',
	alarm32: 'Watch detached',
	alarm64: 'Nopeuden hälytys',
	noalarm: 'Ei lukemattomia hälytyksiä vielä',
	time: 'Aika',
	address: 'Osoite',
	search: 'Haku',
	nodata: 'No Data',
	sosnumbers: 'Hätäpuhelu Numbers',
	whitelistnumbers: 'Valkoinen lista voi soittaa kelloa',
	deldevice: 'Poista tämä laite',
	editprofile: 'Klikkaa muokkaaminen Profiilin',
	phonenumbers: 'Puhelinnumerot',
	batterymode: 'Etsi tila',
	emergencymode: 'Vikasietotila: Etsi 5 minuutissa',
	savingmode: 'Battery Saving Mode: Etsi 10 minuutissa',
	systemsetting: 'Järjestelmän asetukset',
	youradvice: 'mitään neuvoja, mitä tahansa valittaa ...',
	timezone: 'Timezone',
	notificationtitle: 'Gator Watch Alarm',
	lastestlocation: 'Viimeisimmät Etsi',
	device_lang:  'Watch Language',
	volume:  'Watch Volume',
	usedst:  'Daylight saving time',
	socketmodeoff:  'Power saving mode',
	childpoweroff: 'Lapsi voi vallan Off',
	retrieving: 'Haetaan ...',
	smsbyapp: 'Jotkut toimet täytyy lähettää lyhyitä komennon katsella puhelimesi, tämä saattaa synnyttää viestintää maksu.',
	days2exipre: ' päivä (t) vanhentuneet',
	exipred: 'Tämä kello on vanhentunut',
	monthmsgremain: 'Viestit voidaan lähettää tässä kuussa',
	isadding: ' on lisätä tämän katsella, yritä myöhemmin',
	alertsms: 'Lähetä tekstiviesti Kun hälytys',
	verifycodemsg: 'Sinun pitäisi kysyä käyttäjältä {}, for tarkistaa koodia. Hän / hän voi avata App> Setting -> [Watch] -> Vahvista koodi',
	verifycode: 'Vahvista koodi',
	verifycodetip: 'Vahvistuskoodi avulla tarkistetaan käyttäjä voi lisätä tämän katsella, ota tarjoavat tätä koodia vain silloin, kun käyttäjä tunnistetaan.',
	version: 'versio',
	ok: 'OK',
	done: 'tehty',
	cancel: 'peruuttaa',
	msgcancelled: 'viesti peruutettu',
	confirmpassword: 'Vahvista Salasana',
	confirmpasswordnotequal: 'Vahvista salasana olisi sama kuin Salasana',
	gps: 'GPS',
	tower: 'Base Station',
	wifi: 'Wifi',
	phonetype0: 'Iba',
	phonetype1: 'Ama',
	phonetype2: 'Ina',
	phonetype3: 'Lola',
	phonetype4: 'Lolo',
	phonetype5: 'Classmate',
	phonetype: 'Uri',
	name: 'pangalan',
	reenter: 'Mangyaring ipasok muli ang',
	minichat: 'Tinig',
	sendvoice: 'Pindutin ng matagal at ang Magsalita',
	pulltorefresh: 'Hilahin upang i-refresh',
	me: 'sa akin',
	unread: 'hindi pa nababasa',
	holdtip: 'Pindutin ng matagal at ang Magsalita, max na haba ng 10 segundo',
	voicetoolarge: 'Lumampas Voice 10 segundo, paki-record muli',
	novoice: 'Wala pang mga tinig',
	sending: 'Nagpapadala ...',
	recording: 'Recoding ... {time}  segundo (s)',
	preparing: 'Maghanda...',
	watchalarm: 'Alarm',
	watchalarmdetail: 'Setting Alarm',
	morning: 'AM',
	afternoon: 'PM',
	today: 'sa araw na ito',
	everyday: 'Araw-araw',
	repeat: 'Ulitin',
	day0: 'Sun',
	day1: 'Mon',
	day2: 'Tue',
	day3: 'Wed',
	day4: 'Huwebes',
	day5: 'Biyernes',
	day6: 'Sat',
	alarm16: 'New Voice',
	confirmdeletealarm: 'Kumpirmahin tanggalin alarm na ito',
	noalarms: 'Walang mga alarma pa, i-click upang magdagdag ng',
	smart: 'Smart',
	starttime: 'Oras ng Simula',
	endtime: 'Katapusan ng oras',
	contain: 'naglalaman',
	mynumber: 'Ang numero ng aking telepono',
	appqrcode: 'QR Code App',
	dialbackno: 'Ang numero ng telepono upang i-dial muli',
	moreadvancedsetting:  'Advanced Settings',
	hideself:  'Airplane Mode',
	hideselfdetail:  'Airplane Mode Settings',
	hideselfbegin:  'Start time:',
	hideselfend:  'End time:',
	nohidetimers: 'Add Airplane Mode Settings',
	invalidendtime: 'End time need greater than start time',
	enable: 'Open',
	twotimerconflict: 'Clash with following times：',

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  'New version',
	later:  'Later',
	upgrade:  'Upgrade',
	uptodate:  'Up to date',
	checkingupdate:  'Checking update...',

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Lapsen ystävät",
	Nameoflocator:"Locatorin nimi",
	LocatorNumber:"Locator-numero",
    
    DeviceCode:"Laiteversio",
	DeviceName: "laitteen nimi",
    SpeedAlarm: "Ylinopeushälytys",
    ActivePositioningMode: "Aktiivinen paikannustila",
    DeviceNotFeature: "Laite ei tue tätä toimintoa",
    RebootDevice: "Laitteen uudelleenkäynnistys",
    ResetDevice: "Palauta tehdasasetukset",
    timeInterval: "aikaväli",
	IncludingPositioning:'naglalaman Base Station',
	Whether:'Onko olemassa',
	Obtain:"Saada",
	Device:"laite",
	Transmission:"on lähetetty",
	PasswordRese:"Salasanan nollaus epäonnistui. Yritä uudelleen",
	GatorUseName:"",
    NameWatchShown:"Nimi näytetään kellossa",
    successfulActivation:"onnistunut",
	activationFailed: "asetettu epäonnistumaan",
  antiTheft:"varkaudenesto",
  
  systolic :'Systolinen verenpaine',
diastolic:'Diastolinen verenpaine',
power:'teho',
pulseRate:'Syke',
oxygenSaturation:'Veren happikylläisyys',
WeakPerfusion:'Heikko perfuusioindeksi',
temperature:'Kehon lämpötila',
healthSettings:'Terveysasetukset',
thermometer:'lämpömittari',
oximeter:'oksimetri',
sphygmomanometer:'verenpainemittari',
son:'poika',
daughter:'tytär',
spouse:'Aviomies ja vaimo',
ordinaryAlarm:'Tavallinen hälytys',
takeMedicine:'Ota lääkettä',
drinkWater:'Juo vettä',
sedentaryReminder:'Istumakohtainen muistutus',
testReminder:'Testimuistutus',
}