//法语

module.exports = {		
	exitconfirm: "Quitter l'App?",	
	noexitconfirm: "Ne plus m'alerter",	
	login: "Se connecter",	
	loginph: "E-mail",	
	regemail: "E-mail utilisé pour vous connecter et réinitialiser votre mot de passe",	
	pwdph: "Mot de passe",	
	forgotpwd: "Mot de passe oublié?",	
	reset: "Réinitialiser le mot de passe",	
	resetbtn: "Réinitialiser",	
	resetemail: "Adresse e-mail enregistrée",	
	pwdreset: "Votre nouveau mot de passe a été envoyé à ",	
	register: "Enregistrer un nouvel utilisateur",	
	registerbtn: "Enregistrer",	
	invaliduser: "Nom d'utilisateur ou mot de passe incorrect",	
	locate: "Accueil",	
	options: "Paramètres",	
	delete: "Supprimer",	
	logout: "Déconnexion",	
	isempty: "ne peut être vide",	
	taken: "existe déjà. Essayer une autre adresse e-mail.",	
	invalidusername: "Format d'adresse e-mail incorrect",	
	failed: "Erreur, veuillez réessayer",	
	success: "Confirmé",	
	alarm: "Alerte",	
	alarmtitle: "Notification",	
	navigate: "Navigation",	
	startnav: "Lancer la navigation",	
	sos: "Activer le mode SOS",	
	startmonitor: "Activer la surveillance vocale",	
	locatenow: "Localiser",	
	confirmlocatesms: "Il faut envoyer un sms vers la montre pour obtenir le dernier emplacement. Confirmez vous cet envoi?",	
	sms: "Envoyer un SMS",	
	history: "Historique de géolocalisation",	
	mylocation: "Mon emplacement",	
	kidlocation: "Géolocalisation",	
	startpoint: "Point de départ",	
	endpoint: "Destination",	
	addwatch: "Ajouter un appareil",	
	add: "Ajouter",	
	markasread: "Marquer comme lu",	
	morephonenumbers: "Numéros de téléphone",	
	recivesmsalert: "Historique des notifications",	
	setupfence: "Périmètre de sécurité",	
	setupfence1: "Maison",	
	setupfence2: "Ecole",	
	modifypwd: "Modifier le mot de passe",	
	feedback: "Vos commentaires",	
	about: "A propos de",	
	back: "Retour",	
	imei: "IMEI",	
	ownername: "Prénom de l'enfant",	
	simid: "Numéros de téléphone des Équipement",	
	simcountrycode:  "Indicatif pays",	
	soscountrycode:  "Indicatif pays",	
	phonenumbers: "Numéros de téléphone SOS ",	
	locateinterval: "Intervalle de temps pour relever la position de la montre",	
	avatartxt: "Avatar",	
	historyalarm: "Historique des notifications",	
	save: "Sauvegarder",	
	oldpwd: "Ancien mot de passe",	
	newpwd: "Nouveau mot de passe",	
	submit: "Soumettre",	
	invalidimei: "Numéro IMEI incorrect",	
	dupaddwatch: "Cette montre a été ajoutée",	
	confirmremovedevice: "Êtes-vous certain de vouloir supprimer cette montre? Vous ne recevrez plus aucun message de cette montre!",	
	cancel: "Annuler",	
	from: "Sélectionner la source de la photo",	
	fromlib: "Bibliothèque de photos",	
	fromcamera: "Prendre une photo",	
	invalidoldpwd: "L'ancien mot de passe n'est pas correct",	
	undefined: "Non défini",	
	fencename: "Nom",	
	radius: "Périmètre",	
	meter: "m",	
	centerpoint: "Point central",	
	send: "Envoyer",	
	to: "à",	
	text: "Texte",	
	sms2send: "Vous devez envoyer un SMS à votre montre :",	
	cancelsend: "D'accord, je l'enverrai plus tard",	
	alarmemail: "E-mail d'alerte",	
	viewinmap: "Voir la carte",	
	exitnav: "Quitter la navigation",	
	loadingtext: "Chargement",	
	locatefailed: "Impossible de localiser la montre. Vérifier les paramètres de l'App.",	
	alarm1: "Dans le périmètre de sécurité",	
	alarm4: "Sorti(e) du périmètre de sécurité",	
	alarm2: "Alerte",	
	alarm8: "Batterie faible",	
	alarm32: 'Montre déconnectée',	
	alarm64: 'Alarme de vitesse',
	noalarm: "Pas de notification non lue",	
	time: "Heure",	
	address: "Adresse",	
	search: "Chercher",	
	nodata: "Pas de donnée",	
	sosnumbers: "Numéros d'appel d'urgence",	
	whitelistnumbers: "Liste des numéros autorisés à appeler la montre",	
	deldevice: "Supprimer cette montre",	
	editprofile: "Cliquer pour éditer le profile",	
	phonenumbers: "Numéros de téléphone",	
	batterymode: "Paramètres de localisation",	
	emergencymode: "Périmètre de sécurité : localiser toutes les 5 minutes",	
	savingmode: "Economie d'énergie : localiser toutes les 10 minutes",	
	systemsetting: "Paramètres sytème",	
	youradvice: "Un conseil, une suggestion…",	
	timezone: "Fuseau horaire",	
	notificationtitle: "Notification Montre Gator",	
	lastestlocation: "Dernière géolocalisation",	
	device_lang:  "Langue de la montre",	
	volume:  "Volume de la montre",	
	usedst:  "Horaire d'été",	
	socketmodeoff:  "Mode économie d'énergie",	
	childpoweroff: "Permettre enfant éteindre montre",	
	retrieving: "Récupère les données…",	
	smsbyapp: "Il est possible que l'App envoie certaines informations à la montre. Cela peut engendrer des coûts de communication.",	
	days2exipre: "jour(s) avant expiration",	
	exipred: "Cette montre n'est plus enregistrée",	
	monthmsgremain: "Nombre maximum de sms autorisés ce mois",	
	isadding: "est en train d'ajouter cette montre. Essayer plus tard.",	
	alertsms: "Envoyer un SMS en cas d'alerte",	
	verifycodemsg: "Demander à l'utilisateur {}, son code de vérification disponible dans Paramètres puis Profil de {, ",	
	verifycode: "Code de vérification ",	
	verifycodetip: "Code de vérification permettant à l'utilisateur d'ajouter cette montre. A ne fournir à l'utilisateur qu'une fois celui-ci identifié.",	
	version: "version",	
	ok: "d'accord",	
	done: "Terminé",	
	cancel: "annuler",	
	msgcancelled: "message annulé",	
	confirmpassword: "Confirmez le mot de passe",	
	confirmpasswordnotequal: "Mauvais mot de passe,  réessayer",	
	gps: "GPS",	
	tower: "Station de base",	
	wifi: "Wifi",	
	phonetype0: "Autre",	
	phonetype1: "Père",	
	phonetype2: "Mère",	
	phonetype3: "Grandmère",	
	phonetype4: "Grandpère",	
	phonetype: "Type",	
	name: "Nom",	
	reenter: "S'il vous plaît entrer de nouveau",	
	minichat: "Message vocal",	
	sendvoice: "Maintenir appuyé et enregistrer",	
	pulltorefresh: "Glisser vers le haut pour rafraîchir",	
	me: "Moi",	
	unread: "Non lu",	
	holdtip: "Maintenir appuyé et parler, longueur maxi 10 secondes",	
	voicetoolarge: "Message vocal dépasse 10 secondes, s'il vous plaît enregistrer à nouveau",	
	novoice: "Pas de message vocal",	
	sending: "Envoi...",	
	recording: "Recodage ... {time}  secondes (s)",	
	preparing: "En cours...",	
	watchalarm: "Alarme",	
	watchalarmdetail: "Réglage de l'alarme",	
	morning: "matin",	
	afternoon: "après-midi",	
	today: "Aujourd'hui",	
	everyday: "Tous les jours",	
	repeat: "Répéter",	
	day0: "dimanche",	
	day1: "lundi",	
	day2: "mardi",	
	day3: "mercredi",	
	day4: "jeudi",	
	day5: "vendredi",	
	day6: "samedi",	
	alarm16: "Nouveau message vocal",	
	confirmdeletealarm: "Confirmer pour supprimer cette alarme",	
	noalarms: "Pas encore d'alarme, cliquez pour ajouter",	
	smart: "smart",	
	starttime: "Heure de début",	
	endtime: "Heure de fin",	
	contain: "contient",	
	mynumber: "Mon numéro de téléphone",	
	appqrcode: "App QR Code",	
	dialbackno: "Numéro de téléphone à recomposer",	
	moreadvancedsetting:  "Paramètres avancés",	
	hideself:  "Mode avion",	
	hideselfdetail:  "Paramètres mode avion",	
	hideselfbegin:  "Heure de début:",	
	hideselfend:  "Heure de fin:",	
	nohidetimers: "Ajouter les paramètres Mode avion",	
	invalidendtime: "Heure de fin doit être postérieure à l' heure de début",	
	enable: "Activer",	
	twotimerconflict: "Conflit avec les heures suivantes：",	
		
	homewifisetting: 'Paramètres Zone WiFi',	
	homewificomments: "Veuillez sélectionner un point d'accès wifi dans votre zone de sécurité. Si le wifi n'apparait pas dans la liste ci-dessous,cliquez sur \'Annuler\'",	
	accuracy: 'Précision',	
		
	newappversion:  "Nouvelle version",	
	later:  "Plus tard",	
	upgrade:  "Actualiser",	
	uptodate:  "A jour",	
	checkingupdate:  "Vérifier mise à jour ...",	
		
	disconnectedtips:  'Se connecte au serveur, veuillez patienter...',	
	uploadfailed: 'Erreur de mise à jour',	
	lightbulb: 'Ampoule',	
	invalid: 'Invalide',	
	phonelistisfull: 'La liste de numéros de téléphone est pleine',	
	serverinternalerror: 'Erreur interne serveur',	
	addwatchtimeout: 'Délai ajout montre dépassé',	
	deletewatchtimeout: 'Délai effacer montre dépassé',	
	registertimeout:  "Délai s'enregistrer dépassé",	
	registerfailed: "Echec d'enregistrement ",	
	failed: 'échec',	
	timeout: 'délai dépassé',	
	activedevice: 'connecter la montre',	
	familynumbernotfound: 'numéro de téléphone non trouvé',	
	updating: 'Actualisation...',	
		
	disablewifilocation: "Désactiver la localisation wifi",	
	locatenowtips: "Appuyer pour actualiser la localisation de l'utilisateur. Vous devrez envoyer une SMS à la montre.",	
	confirmsendsmstoactive: "Montre temporairement déconnectée du serveur. Envoyer un SMS pour la forcer à envoyer une localisation immédiatement",	
	inputfencename: 'Entrer le nom de la zone de sécurité',	
		
	agreeprivacypolicy: 'Vous vous engagez à ',	
	privacypolicytitle: 'Politique de confidentialité',	
	passwordruletips: 'Mot de passe doit compter 8 charactères et doit inclure un numéro, une minuscule et une majuscule',	
	passworderror:'erreur mot de passe!',	
	passworderror5:'Vous avez entré un mot de passe incorrect, veuillez réessayer dans une minute',	
		
	addAccount:'Ajouter les permissions des administrateurs',	
	notAccount:'Accès non autorisé',	
	overlimitNumber: 'Nombre essais saisie numéro dépassé',
    
    Pleaseconfirm:"Please confirm",
    commonsecret: "The password is the same, please retype",
    phonetype5: "Camarade de classe",
    petname:"nom d'animal",
	friends:"Les amis de l'enfant",
	Nameoflocator:"Nom du localisateur",
	LocatorNumber:"Numéro de localisateur",
    
    DeviceCode:"Version de l'appareil",
	DeviceName: "nom de périphérique",
    SpeedAlarm: "Speeding Alarm",
    ActivePositioningMode: "Mode de positionnement actif",
    DeviceNotFeature: "Le périphérique ne supporte pas cette fonctionnalité",
    RebootDevice: "Redémarrage du périphérique",
    ResetDevice: "Restaurer les réglages d'usine",
    timeInterval: "intervalle",
	IncludingPositioning:'contient Station de base',
	Whether:"S'il existe",
	Obtain:"Obtenir",
	Device:"dispositif",
	Transmission:"a été envoyé à",
	PasswordRese:"La réinitialisation du mot de passe a échoué. Veuillez réessayer",
	GatorUseName:"",
    NameWatchShown:"Nom affiché sur la montre",
    successfulActivation:"mis en place avec succès",
	activationFailed: "mis en place sans succès",
  antiTheft:"fonction anti-vol",
  
  systolic :'Pression artérielle systolique',
diastolic:'Pression artérielle diastolique',
power:'Puissance',
pulseRate:"Taux d'impulsion",
oxygenSaturation:'Saturation en oxygène du sang',
WeakPerfusion:'Indice de perfusion faible',
temperature:'Température corporelle',
healthSettings:'Paramètres de santé',
thermometer:'Thermomètre',
oximeter:'Oxymètre',
sphygmomanometer:'Sphygmomanomètre',
son:'Fils',
daughter:'Fille',
spouse:'Mari et femme',
ordinaryAlarm:'Alarme ordinaire',
takeMedicine:'Prenez des médicaments',
drinkWater:"Buvez de l'eau",
sedentaryReminder:'Rappel sédentaire',
testReminder:'Rappel de test',
}