//爱尔兰语

module.exports = {
	exitconfirm: "Deimhnigh scoir",
	noexitconfirm: "Wont airdeall arís",
	login: "Logáil isteach",
	loginph: "Ríomhphost",
	regemail: "Ríomhphost úsáidtear chun logáil isteach agus do phasfhocal a athshocrú",
	pwdph: "Pasfhocal",
	forgotpwd: "Focal faire dearmadta agat?",
	reset: "Focal faire a athshocrú",
	resetbtn: "Athshocraigh",
	resetemail: "Do Ríomhphost cláraithe",
	pwdreset: "Cuireadh do phasfhocal nua chuig",
	register: "Cláraigh úsáideoir nua",
	registerbtn: "Cláraigh",
	invaliduser: "Ainm úsáideora mícheart agus do phasfhocal",
	locate: "Baile",
	options: "Socruithe",
	delete: "Scrios",
	logout: "Logout",
	isempty: " Ní féidir folamh",
	taken: " bhí cláraithe, le do thoil bain triail eile",
	invalidusername: "Tá do r-phost neamhbhailí",
	failed: "Rud éigin mícheart, le do thoil bain triail eile as",
	success: "rath",
	alarm: "Aláraim",
	alarmtitle: "Teachtaireachtaí Aláraim",
	navigate: "Navigate",
	startnav: "Tosaigh Navigate",
	sos: "Gníomhachtaigh Mód SOS",
	startmonitor: "Gníomhachtaigh Guth Monatóireacht",
	locatenow: "Aimsigh Anois",
	confirmlocatesms: "Ní mór dúinn an téacs a sheoladh chun féachaint a fháil suíomh is déanaí, a dhearbhú a sheoladh?",
	sms: "Seol SMS",
	history: "Suíomh Stair",
	mylocation: "Mo Suíomh",
	kidlocation: "Kids Suíomh",
	startpoint: "Ag tosú Point",
	endpoint: "Ceann Scríbe",
	addwatch: "Cuir gléas leis",
	add: "Cuir",
	markasread: "Marcáil Mar Léigh",
	morephonenumbers: "Uimhreacha Teileafóin",
	recivesmsalert: "Fógra Airdeall",
	setupfence: "Safezone",
	setupfence1: "Baile",
	setupfence2: "Scoil",
	modifypwd: "Athraigh Pasfhocal",
	feedback: "Aiseolas",
	about: "Maidir",
	back: "Ar ais",
	imei: "IMEI",
	ownername: "Ainm leanbh",
	petname:"Ainm peata",
	simid: "Fón gléas",
	simcountrycode:  "Country Code",
	soscountrycode:  "Country Code",
	phonenumbers: "Uimhreacha Teileafóin SOS",
	locateinterval: "Am Eatramh de Dul Seasamh Kid (M)",
	avatartxt: "Avatar",
	historyalarm: "Aláraim Stair",
	save: "Sábháil",
	oldpwd: "Sean Pasfhocal",
	newpwd: "Pasfhocal nua",
	submit: "Cuir isteach",
	invalidimei: "Neamhbhailí Uimhir IMEI",
	dupaddwatch: "Tá tú Chuir an clog",
	confirmremovedevice: "An bhfuil tú cinnte gur mian leat seo a bhaint faire? Ní bheidh tú aon teachtaireachtaí ón faire.",
	cancel: "Cealaigh",
	from: "Roghnaigh Photo Foinse",
	fromlib: "Leabharlann Grianghraf",
	fromcamera: "Glac Grianghraf",
	invalidoldpwd: "Níl an Sean Pasfhocal ceart.",
	undefined: "Undefined",
	fencename: "An t-ainm",
	radius: "Ga",
	meter: "m",
	centerpoint: "Pointe Ionad",
	send: "Seol",
	to: "Chun",
	text: "Téacs",
	sms2send: "Ní mór duit a téacs a sheoladh chuig do faire:",
	cancelsend: "OK, beidh mé a sheoladh níos déanaí",
	alarmemail: "Aláraim Ríomhphoist",
	viewinmap: "Féach ar Léarscáil",
	exitnav: "Nascleanúint Scoir",
	loadingtext: "luchtú",
	locatefailed: "Ní féidir a aimsiú ar an teileafón, le do thoil a chumasú dó i suímh app",
	alarm1: "Iontráil Crios Sábháilte",
	alarm4: "As Crios Sábháilte",
	alarm2: "Aláraim Éigeandála",
	alarm8: "Aláraim ceallraí Íseal",
	alarm32: 'Watch detached',
	alarm64: 'Aláraim luas',
	noalarm: "Uimh aláraim gan léamh go fóill",
	time: "Am",
	address: "Seoladh",
	search: "Cuardaigh",
	nodata: "Níl sonraí",
	sosnumbers: "Uimhreacha Glao Éigeandála",
	whitelistnumbers: "Is féidir le whitelist glaoch faire",
	deldevice: "Scrios an gléas seo",
	editprofile: "Cliceáil Próifíl Chun Cuir",
	phonenumbers: "Uimhreacha Teileafóin",
	batterymode: "Aimsigh Mód",
	emergencymode: "Mód Sábháilte: Aimsigh i 5 nóiméad",
	savingmode: "Shábháil Mód Battery: Aimsigh i 10 nóiméad",
	systemsetting: "Socrú Córas",
	youradvice: "aon chomhairle, aon gearán a ...",
	timezone: "Crios ama",
	notificationtitle: "Gator Féach Aláraim",
	lastestlocation: "Déanaí Aimsigh",
	device_lang:  "Watch Language",
	volume:  "Watch Volume",
	usedst:  "Daylight saving time",
	socketmodeoff:  "Power saving mode",
	childpoweroff: "An féidir leanbh Cumhacht Off",
	retrieving: "Aisghabháil ...",
	smsbyapp: "Gníomh éigin is gá a sheoladh ordú téacs gearr chun féachaint le do ghuthán, Is féidir an táille cumarsáide a ghiniúint.",
	days2exipre: " lá (í) in éag",
	exipred: "Tá an clog in éag",
	monthmsgremain: "Is féidir teachtaireachtaí a sheoladh an mhí seo",
	isadding: " Tá cur an clog, le do thoil bain triail ina dhiaidh sin",
	alertsms: "Seol SMS Nuair Aláraim",
	verifycodemsg: "Ba chóir duit a iarraidh úsáideora {}, do cód a fhíorú. Is féidir leis / léi a oscailt app-> leagan síos -> [Watch] -> Fíoraigh Cód",
	verifycode: "Fíoraigh Cód",
	verifycodetip: "Fíoraigh Cód úsáid úsáideoir a fhíorú a chur leis an clog, le do thoil a thairiscint an cód ach amháin nuair a aithnítear úsáideoir.",
	version: "leagan",
	ok: "OK",
	done: "Arna dhéanamh",
	cancel: "Cealaigh",
	msgcancelled: "Teachtaireacht ceal",
	confirmpassword: "Deimhnigh Pasfhocal",
	confirmpasswordnotequal: "Deimhnigh Pasfhocal Ba chóir mar Pasfhocal gcéanna",
	gps: "GPS",
	tower: "Base Stáisiún",
	wifi: "wifi",
	phonetype0: "eile",
	phonetype1: "athair",
	phonetype2: "máthair",
	phonetype3: "Mhamó",
	phonetype4: "Grandpa",
	phonetype5: 'Aicme ranga',
	phonetype: "cineál",
	name: "ainm",
	reenter: "Tabhair faoi dul isteach arís",
	minichat: "guthanna",
	sendvoice: "Coinnigh agus Abair",
	pulltorefresh: "Tarraingt a athnuachan",
	me: "Me",
	unread: "neamhléite",
	holdtip: "Coinnigh agus Labhairt, max fad 10 soicind",
	voicetoolarge: "Guth níos mó ná 10 soicind, le do thoil taifead arís",
	novoice: "Níl aon guthanna go fóill",
	sending: "Seoladh ...",
	recording: "Recoding ... {time}  am soicind (s)",
	preparing: "Faigh réidh ...",
	watchalarm: "aláraim",
	watchalarmdetail: "aláraim Socrú",
	morning: "AM",
	afternoon: "PM",
	today: "Sa lá atá inniu",
	everyday: "Gach lá",
	repeat: "Déan",
	day0: "Sun",
	day1: "mon",
	day2: "Tue",
	day3: "Wed",
	day4: "thu",
	day5: "Aoine",
	day6: "Sat",
	alarm16: "New Guth",
	confirmdeletealarm: "Deimhnigh seo a scriosadh aláram",
	noalarms: "Níl aon aláraim go fóill, cliceáil a chur leis",
	smart: "cliste",
	starttime: "Am tosaithe",
	endtime: "deireadh Am",
	contain: "tá",
	mynumber: "Mo uimhir theileafóin",
	appqrcode: "App QR Code",
	dialbackno: "Uimhir Fón a dhiailiú ar ais",
	moreadvancedsetting:  "Advanced Settings",
	hideself:  "Airplane Mode",
	hideselfdetail:  "Airplane Mode Settings",
	hideselfbegin:  "Start time:",
	hideselfend:  "End time:",
	nohidetimers: "Add Airplane Mode Settings",
	invalidendtime: "End time need greater than start time",
	enable: "Open",
	twotimerconflict: "Clash with following times：",

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  "New version",
	later:  "Later",
	upgrade:  "Upgrade",
	uptodate:  "Up to date",
	checkingupdate:  "Checking update...",

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Cairde an linbh",
	Nameoflocator:"Ainm locator",
	LocatorNumber:"Uimhir locálaí",
    
    DeviceCode:"Leagan an ghléas",
	DeviceName: "ainm an ghléas",
    SpeedAlarm: "Luaitear Aláraim",
    ActivePositioningMode: "Mód Seasamh Gníomhach",
    DeviceNotFeature: "Ní thacaíonn an gléas leis an ngné seo",
    RebootDevice: "Atosú Gléas",
    ResetDevice: "Socruithe sa mhonarcha a athchóiriú",
    timeInterval: "eatramh",
	IncludingPositioning:'tá Base Stáisiún',
	Whether:'Cibé an bhfuil',
	Obtain:"Fuair",
	Device:"gléas",
	Transmission:"curtha chuig",
	PasswordRese:"Theip ar athshocrú pasfhocal. Arís, le d'thoil",
	GatorUseName:"",
    NameWatchShown:"Ainm a thaispeántar ar faire",
    successfulActivation:"a bunaíodh go rathúil",
	activationFailed: "níor éirigh leis",
	antiTheft:"feidhm frith-goid",
}