//印尼语

module.exports = {
	exitconfirm: "Konfirmasi keluar",
	noexitconfirm: "Tidak akan waspada lagi",
	login: "Masuk",
	loginph: "Email",
	regemail: "Email digunakan untuk login dan mereset password Anda",
	pwdph: "Kata sandi",
	forgotpwd: "Lupa kata sandi?",
	reset: "Ulang kata sandi",
	resetbtn: "Atur ulang",
	resetemail: "Email yang terdaftar",
	pwdreset: "Password baru Anda telah dikirim ke",
	register: "Daftarkan pengguna baru",
	registerbtn: "Daftar",
	invaliduser: "Username dan password yang salah",
	locate: "Rumah",
	options: "Pengaturan",
	delete: "Hapus",
	logout: "Keluar",
	isempty: " tidak bisa kosong",
	taken: " telah terdaftar, silakan coba yang lain",
	invalidusername: "Email Anda tidak valid",
	failed: "Sesuatu yang salah, silakan coba lagi",
	success: "sukses",
	alarm: "Alarm",
	alarmtitle: "Pesan Alarm",
	navigate: "Arahkan",
	startnav: "Mulai Arahkan",
	sos: "Mengaktifkan modus SOS",
	startmonitor: "Aktifkan Suara Memantau",
	locatenow: "Cari Sekarang",
	confirmlocatesms: "Kita perlu untuk mengirim pesan teks untuk menonton untuk mendapatkan lokasi terbaru, pastikan untuk mengirim?",
	sms: "Kirim SMS",
	history: "Sejarah Lokasi",
	mylocation: "Lokasi saya",
	kidlocation: "Anak Lokasi",
	startpoint: "Titik Pangkal",
	endpoint: "Tujuan",
	addwatch: "Tambahkan perangkat",
	add: "Menambahkan",
	markasread: "Tandai Sebagai Membaca",
	morephonenumbers: "Nomor Telepon",
	recivesmsalert: "Pemberitahuan peringatan",
	setupfence: "SafeZone",
	setupfence1: "Rumah",
	setupfence2: "Sekolah",
	modifypwd: "Memodifikasi Sandi",
	feedback: "Masukan",
	about: "Tentang",
	back: "Kembali",
	imei: "IMEI",
	ownername: "Nama Anak",
	petname:"Nama binatang peliharaan",
	simid: "Ponsel perangkat",
	simcountrycode:  "Country Code",
	soscountrycode:  "Country Code",
	phonenumbers: "SOS Nomor Telepon",
	locateinterval: "Waktu Interval Mendapatkan Posisi Kid (M)",
	avatartxt: "Avatar",
	historyalarm: "Sejarah Alarm",
	save: "Simpan",
	oldpwd: "Password Lama",
	newpwd: "Kata Sandi Baru",
	submit: "Menyerahkan",
	invalidimei: "Nomor IMEI tidak valid",
	dupaddwatch: "Anda telah menambahkan jam tangan ini",
	confirmremovedevice: "Apakah Anda yakin ingin menghapus menonton ini? Anda tidak akan menerima pesan dari jam tangan ini.",
	cancel: "Membatalkan",
	from: "Pilih Sumber Foto",
	fromlib: "Foto Perpustakaan",
	fromcamera: "Mengambil foto",
	invalidoldpwd: "Old Password tidak benar.",
	undefined: "Undefined",
	fencename: "Nama",
	radius: "Radius",
	meter: "m",
	centerpoint: "Center Point",
	send: "Mengirim",
	to: "Untuk",
	text: "Teks",
	sms2send: "Anda perlu mengirim pesan teks ke jam Anda:",
	cancelsend: "OK, saya akan mengirimkannya nanti",
	alarmemail: "Alarm Email",
	viewinmap: "Lihat di Peta",
	exitnav: "Keluar Navigasi",
	loadingtext: "pemuatan",
	locatefailed: "Tidak dapat menemukan telepon, Aktifkan dalam pengaturan aplikasi",
	alarm1: "Masukkan Zona Aman",
	alarm4: "Keluar dari Zona Aman",
	alarm2: "Alarm Darurat",
	alarm8: "Alarm baterai rendah",
	alarm32: 'Watch detached',
	alarm64: 'Kecepatan alarm',
	noalarm: "Tidak ada yang belum dibaca alarm belum",
	time: "Waktu",
	address: "Alamat",
	search: "Pencarian",
	nodata: "Tidak Ada Data",
	sosnumbers: "Nomor Panggilan Darurat",
	whitelistnumbers: "WhiteList dapat menghubungi menonton",
	deldevice: "Hapus perangkat ini",
	editprofile: "Klik Untuk Mengedit Profil",
	phonenumbers: "Nomor Telepon",
	batterymode: "Cari Modus",
	emergencymode: "Safe Mode: Cari di 5 menit",
	savingmode: "Baterai Saving Mode: Cari dalam 10 menit",
	systemsetting: "Pengaturan sistem",
	youradvice: "saran, komplain ...",
	timezone: "Zona Waktu",
	notificationtitle: "Gator Perhiasan Alarm",
	lastestlocation: "Terbaru Cari",
	device_lang:  "Watch Language",
	volume:  "Watch Volume",
	usedst:  "Daylight saving time",
	socketmodeoff:  "Power saving mode",
	childpoweroff: "Anak Bisa Matikan",
	retrieving: "Mengambil ...",
	smsbyapp: "Beberapa tindakan perlu mengirim perintah teks singkat untuk menonton melalui telepon Anda, ini dapat menghasilkan biaya komunikasi.",
	days2exipre: " hari (s) to expired",
	exipred: "Jam tangan ini telah berakhir",
	monthmsgremain: "Pesan dapat mengirim bulan ini",
	isadding: " adalah menambahkan menonton ini, coba lagi nanti",
	alertsms: "Kirim SMS Ketika alarm",
	verifycodemsg: "Anda harus meminta pengguna {}, untuk memverifikasi kode. dia / dia bisa membuka app-> Setting -> [Watch] -> Verifikasi Kode",
	verifycode: "Kode Verifikasi",
	verifycodetip: "Verifikasi Kode yang digunakan untuk memverifikasi pengguna untuk menambahkan jam ini, silakan menawarkan kode ini hanya bila pengguna diidentifikasi.",
	version: "versi",
	ok: "OKE",
	done: "matang",
	cancel: "membatalkan",
	msgcancelled: "pesan dibatalkan",
	confirmpassword: "Konfirmasi sandi",
	confirmpasswordnotequal: "Konfirmasi Sandi harus sama dengan Sandi",
	gps: "GPS",
	tower: "Base Station",
	wifi: "Wifi",
	phonetype0: "Lain",
	phonetype1: "Ayah",
	phonetype2: "Ibu",
	phonetype3: "Nenek",
	phonetype4: "Kakek",
	phonetype5: 'Teman sekelas',
	phonetype: "Mengetik",
	name: "Nama",
	reenter: "Masukkan kembali silahkan",
	minichat: "suara",
	sendvoice: "Tahan dan Bicara",
	pulltorefresh: "Tarik untuk menyegarkan",
	me: "Saya",
	unread: "belum dibaca",
	holdtip: "Tahan dan Bicara, max panjang 10 detik",
	voicetoolarge: "Suara melebihi 10 detik, silahkan merekam lagi",
	novoice: "Tidak ada suara belum",
	sending: "Mengirim ...",
	recording: "Pengodean ulang ... {time}  waktu detik (s)",
	preparing: "Bersiap...",
	watchalarm: "Alarm",
	watchalarmdetail: "Pengaturan alarm",
	morning: "AM",
	afternoon: "PM",
	today: "Hari ini",
	everyday: "Setiap hari",
	repeat: "Ulangi",
	day0: "Matahari",
	day1: "mon",
	day2: "Sel",
	day3: "Mengawinkan",
	day4: "Thu",
	day5: "Fri",
	day6: "Sat",
	alarm16: "baru Voice",
	confirmdeletealarm: "Konfirmasi untuk menghapus alarm ini",
	noalarms: "Belum ada alarm, klik untuk menambahkan",
	smart: "Cerdas",
	starttime: "Waktu mulai",
	endtime: "Akhir waktu",
	contain: "berisi",
	mynumber: "Nomor telepon saya",
	appqrcode: "App QR Kode",
	dialbackno: "Nomor telepon untuk dial kembali",
	moreadvancedsetting:  "Advanced Settings",
	hideself:  "Airplane Mode",
	hideselfdetail:  "Airplane Mode Settings",
	hideselfbegin:  "Start time:",
	hideselfend:  "End time:",
	nohidetimers: "Add Airplane Mode Settings",
	invalidendtime: "End time need greater than start time",
	enable: "Open",
	twotimerconflict: "Clash with following times：",

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',
	
	newappversion:  "New version",
	later:  "Later",
	upgrade:  "Upgrade",
	uptodate:  "Up to date",
	checkingupdate:  "Checking update...",

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Teman-teman anak-anak",
	Nameoflocator:"Nama pelacak",
	LocatorNumber:"Nomor lokator",
    
    DeviceCode:"Versi perangkat",
	DeviceName: "nama perangkat",
    SpeedAlarm: "Mempercepat Alarm",
    ActivePositioningMode: "Mode Pemosisian Aktif",
    DeviceNotFeature: "Perangkat tidak mendukung fitur ini",
    RebootDevice: "Restart perangkat",
    ResetDevice: "Mengembalikan pengaturan pabrik",
    timeInterval: "interval",
	IncludingPositioning:'berisi Base Station',
	Whether:'Apakah ada',
	Obtain:"Mendapatkan",
	Device:"alat",
	Transmission:"telah dikirim ke",
	PasswordRese:"Reset kata sandi gagal. Silakan coba lagi",
	GatorUseName:"",
    NameWatchShown:"Nama ditampilkan di jam tangan",
    successfulActivation:"berhasil diatur",
	activationFailed: "pengaturan tidak berhasil",
  antiTheft:"fungsi anti-pencurian",
  
  systolic :'Tekanan darah sistolik',
diastolic:'Tekanan darah diastolik',
power:'Kekuasaan',
pulseRate:'Denyut nadi',
oxygenSaturation:'Saturasi oksigen darah',
WeakPerfusion:'Indeks Perfusi Lemah',
temperature:'Suhu tubuh',
healthSettings:'Pengaturan kesehatan',
thermometer:'Termometer',
oximeter:'Oksimeter',
sphygmomanometer:'Sphygmomanometer',
son:'Nak',
daughter:'Anak perempuan',
spouse:'Suami dan istri',
ordinaryAlarm:'Alarm biasa',
takeMedicine:'Minum obat',
drinkWater:'Minumlah air',
sedentaryReminder:'Pengingat menetap',
testReminder:'Pengingat ujian',
  
}