//意大利语
module.exports = {
    exitconfirm: "Conferma uscita?",
    noexitconfirm: "non confermare uscita",
    login: "Login",
    loginph: "Email",
    regemail: "E-mail utilizzato per il login e reimpostare la password",
    pwdph: "Password",
    forgotpwd: "Password dimenticata?",
    reset: "Resettare la password",
    resetbtn: "Reset",
    resetemail: "La email di registrazione",
    pwdreset: "La tua nuova password è stata inviata",
    register: "Registrazione nuovo utente",
    registerbtn: "Register",
    invaliduser: "utente non riconosciuto",
    locate: "Localizzare",
    options: "Impostazioni",
    delete: "Cancellare",
    logout: "Uscire",
    isempty: " vuoto",
    taken: " è stato registrato, si prega di provare con un altro",
    invalidusername: "Il tuo indirizzo email non è valido",
    failed: "Qualcosa non va, riprova",
    success: "successo",
    alarm: "Allarme",
    alarmtitle: "Messaggi di allarme",
    navigate: "Navigare",
    startnav: "Inizio Navigazione",
    sos: "Attivare la modalità SOS",
    startmonitor: "Attiva Monitor Voice",
    locatenow: "Individuare Ora",
    confirmlocatesms: "Abbiamo bisogno di inviare messaggi di testo a guardare per le ultime posizione, confermiamo l'invio?",
    sms: "Invia SMS",
    history: "Cronologia delle posizioni",
    mylocation: "La Mia Posizione",
    kidlocation: "Posizione Bimbi",
    startpoint: "Punto Di Partenza",
    endpoint: "Destinazione",
    addwatch: "Aggiungi dispositivo",
    add: "Aggiungere",
    markasread: "Segna Come Letto",
    morephonenumbers: "Numero Di Telefono",
    recivesmsalert: "Ricevere Notifica ",
    setupfence: "Zona Sicura",
    setupfence1: "Casa",
    setupfence2: "Scuola",
    modifypwd: "Modificare la password",
    feedback: "feedback",
    about: "Di",
    back: "Indietro",
    imei: "IMEI",
    ownername: "Nome del bambino",
    simid: "Telefono dispositivo",
    simcountrycode:  "Prefisso Internazionale",
    soscountrycode:  "Prefisso Internazionale",
    phonenumbers: "Numeri di telefono SOS",
    locateinterval: "Intervallo di tempo di ottenere Posizione Bimbo (M)",
    avatartxt: "Avatar",
    historyalarm: "Cronologia allarmi",
    save: "Salva",
    oldpwd: "Vecchia Password",
    newpwd: "Nuova Password",
    submit: "Presentare",
    invalidimei: "Numero IMEI invalido",
    dupaddwatch: "Hai aggiunto questo orologio",
    confirmremovedevice: "Sei sicuro di voler rimuovere questo orologio? Non riceverai nessun messaggio per questo orologio.",
    cancel: "Cancellare",
    from: "Selezionare Foto Fonte",
    fromlib: "Photo Library",
    fromcamera: "Fai una foto",
    invalidoldpwd: "Vecchia password non è corretta.",
    undefined: "Indefinito",
    fencename: "Nome",
    radius: "Raggio",
    meter: "m",
    centerpoint: "Center Point",
    send: "Inviare",
    to: "A",
    text: "Testo",
    sms2send: "È necessario inviare un testo per l'orologio:",
    cancelsend: "OK, lo manderò in un secondo momento",
    alarmemail: "Allarme Email",
    viewinmap: "Visualizza Mappa",
    exitnav: "Uscita Navigazione",
    loadingtext: "caricamento",
    locatefailed: "Impossibile individuare il telefono, Si prega di abilitare nelle impostazioni di app",
    alarm1: "Inserisci Safe Zone",
    alarm4: "Fuori Safe Zone",
    alarm2: "Allarme di emergenza",
    alarm8: "Allarme batteria",
    alarm32: 'Watch detached',
    alarm64: 'Allarme di velocità',
    noalarm: "Ancora nessun allarme da leggere",
    time: "Tempo",
    address: "Indirizzo",
    search: "Ricerca",
    nodata: "Nessun Dato",
    sosnumbers: "I numeri di emergenza di chiamata",
    whitelistnumbers: "WhiteList può chiamare orologio",
    deldevice: "Eliminare questo orologio",
    editprofile: "Fai clic per modificare il profilo",
    phonenumbers: "Numero Di Telefono",
    batterymode: "Individuare modalità",
    emergencymode: "Modalità provvisoria: Individuare in 5 minuti",
    savingmode: "Modalità di risparmio della batteria: Individuare in 10 minuti",
    systemsetting: "System Setting",
    youradvice: "qualche consiglio, ogni lamentano ...",
    timezone: "Fuso Orario",
    notificationtitle: "Gator Guarda allarme",
    lastestlocation: "Ultime Individuare",
    device_lang:  "Watch Language",
    volume:  "Watch Volume",
    usedst:  "Daylight saving time",
    socketmodeoff:  "Power saving mode",
    childpoweroff: "Bambino possibile spegnere",
    retrieving: "Recupero ...",
    smsbyapp: "Alcune azioni necessarie inviare il comando breve testo di guardare dal telefono, questo può generare tassa di comunicazione.",
    days2exipre: " giorno (s) per scaduto",
    exipred: "Questo orologio è scaduto",
    monthmsgremain: "I messaggi possono trasmettere questo mese",
    isadding: " è l'aggiunta di questo orologio, si prega di riprovare più tardi",
    alertsms: "Invia SMS alert",
    verifycodemsg: "Si dovrebbe chiedere all'utente {}, per verificare il codice. lui / lei può aprire app-> Impostazioni -> [Guarda] -> Verifica il codice",
    verifycode: "Verificare Codice",
    verifycodetip: "Verifica il codice utilizzato per verificare all utente di aggiungere questo orologio, si prega di offrire questo codice solo quando lutente identificato.",
    version: "versione",
    ok: "OK",
    done: "Fatto",
    cancel: "annullare",
    msgcancelled: "messaggio cancellato",
    confirmpassword: "Conferma password",
    confirmpasswordnotequal: "Password on uguale",
    gps: "GPS",
    tower: "Stazione base",
    wifi: "Wifi",
    phonetype0: "Altro",
    phonetype1: "Padre",
    phonetype2: "Madre",
    phonetype3: "Nonna",
    phonetype4: "Nonno",
    phonetype: "Tipo",
    name: "Nome",
    reenter: "Inserisci nuovamente",
    minichat: "voci",
    sendvoice: "Hold e Speak",
    pulltorefresh: "Tirare per aggiornare",
    me: "Me",
    unread: "Non letto",
    holdtip: "Hold e Parla, lunghezza max 10 secondi",
    voicetoolarge: "Voce supera i 10 secondi, si prega di registrare di nuovo",
    novoice: "Non ci sono ancora voci",
    sending: "Invio ...",
    recording: "Ricodifica ... {time}  secondi di tempo (s)",
    preparing: "Preparati...",
    watchalarm: "Allarme",
    watchalarmdetail: "Impostazione Allarme",
    morning: "AM",
    afternoon: "PM",
    today: "Oggi",
    everyday: "Ogni giorno",
    repeat: "Ripetere",
    day0: "Sole",
    day1: "Mon",
    day2: "mar",
    day3: "mer",
    day4: "gio",
    day5: "Fri",
    day6: "Sat",
    alarm16: "new Voice",
    confirmdeletealarm: "Conferma per eliminare questo allarme",
    noalarms: "Nessun allarme ma, fare clic per aggiungere",
    smart: "Intelligente",
    starttime: "Ora di inizio",
    endtime: "Fine del tempo",
    contain: "contiene",
    mynumber: "Il mio numero di telefono",
    appqrcode: "App QR Code",
    dialbackno: "Numero di telefono per richiamare",
    moreadvancedsetting:  "Impostazioni avanzate",
    hideself:  "Airplane Mode",
    hideselfdetail:  "Airplane Mode Settings",
    hideselfbegin:  "Start time:",
    hideselfend:  "End time:",
    nohidetimers: "Add Airplane Mode Settings",
    invalidendtime: "End time deve essere piu' lungo di start time",
    enable: "Open",
    twotimerconflict: "Conflitto con seguenti tempi",
    homewifisetting: "Zona WiFi impostazioni",
    homewificomments: "Selezionare il punto di accesso WiFi access usato nella safe zone. Se WiFi non è mostrato nella list giù, perfavore clicca \'Cancel\'",
    accuracy: 'Accuracy',
    newappversion:  "Nuova versione",
    later:  "Più tardi",
    upgrade:  "Upgrade",
    uptodate:  "Aggiornato",
    checkingupdate:  "Checking update...",
    disconnectedtips:  'Connessione al server, attendere...',
    uploadfailed: 'Upload failed',
    lightbulb: 'Light bulb',
    invalid: 'Invalido',
    phonelistisfull: 'Rubrica piena',
    serverinternalerror: 'Server errore interno',
    addwatchtimeout: 'Add watch timeout',
    deletewatchtimeout: 'Delete watch timeout',
    registertimeout: 'Register timeout',
    registerfailed: 'Register failed',
    failed: 'failed',
    timeout: 'timeout',
    activedevice: 'connect watch',
    familynumbernotfound: 'phone number not found',
    updating: 'Updating...',
    disablewifilocation: 'Disabile WiFi location',
    locatenowtips: "Premere per aggiornare la location dell'utente. Ciò richiede l'invio di un messaggio SMS all'orologio.",
    confirmsendsmstoactive: 'Orologio temporaneamente disconnesso dal server. Inviare un SMS per inviare location immediatamente.' ,
    inputfencename: 'Entrare Safezone Nome',
    agreeprivacypolicy: 'Acconsenti alla privacy policy ',
    privacypolicytitle: 'Privacy Policy',
    passwordruletips: 'Password deve avere almento 8 caratteri e deve includere un numero, uno minuscolo e uno maiuscolo.',
    passworderror:'password errore!',
    passworderror5:'Password input errore è oltre il limite, riprova fra un minuto',
    addAccount:' Aggiungere administrator permesso',
    notAccount:'No autorità!',
    overlimitNumber: 'Aggiunta numero sorpassa limite ',
    Pleaseconfirm:"Please confirm",
    petname:"il nome del cane",
    phonetype5: 'compagno di classe',
    commonsecret: 'The password is the same, please retype',
	friends:"Amici di Child",
	Nameoflocator:"Nome del localizzatore",
	LocatorNumber:"Numero di localizzatore",
    
    DeviceCode:"Versione del dispositivo",
    DeviceName: "nome del dispositivo",
    SpeedAlarm: "Allarme eccesso di velocità",
    ActivePositioningMode: "Active Positioning Mode",
    DeviceNotFeature: "Il dispositivo non supporta questa funzionalità",
    RebootDevice: "Device restart",
    ResetDevice: "Ripristina le impostazioni di fabbrica",
    timeInterval: "intervallo",
    IncludingPositioning:'contiene Stazione base',
    Whether:"Se c'è",
    Obtain:"Ottenere",
    Device:"dispositivo",
    Transmission:"è stato inviato a",
    PasswordRese:"Ripristino password fallito. Per favore riprova",
    GatorUseName:"",
    NameWatchShown:"Nome mostrato sull'orologio",
    successfulActivation:"istituito con successo",
    activationFailed: "impostare senza successo",
    antiTheft:"funzione antifurto",

    systolic :'Pressione arteriosa sistolica',
diastolic:'Pressione sanguigna diastolica',
power:'potere',
pulseRate:'Frequenza cardiaca',
oxygenSaturation:'Saturazione di ossigeno nel sangue',
WeakPerfusion:'Indice di perfusione debole',
temperature:'Temperatura corporea',
healthSettings:'Impostazioni di salute',
thermometer:'termometro',
oximeter:'ossimetro',
sphygmomanometer:'sfigmomanometro',
son:'figlio',
daughter:'figlia',
spouse:'Marito e moglie',
ordinaryAlarm:'Allarme ordinario',
takeMedicine:'Prendi la medicina',
drinkWater:'Bevi acqua',
sedentaryReminder:'Promemoria sedentario',
testReminder:'Promemoria del test',

}