//哈萨克语

module.exports = {
    exitconfirm: "Шығу растаңыз",
    noexitconfirm: "Кәдімгі ескерту қайтадан",
    login: "Кіру",
    loginph: "Email",
    regemail: "Парольді логин және қалпына келтіру үшін пайдаланылады Email",
    pwdph: "Пароль",
    forgotpwd: "Құпия сөзді ұмыттыңыз ба?",
    reset: "Құпия сөзді қалпына келтіру",
    resetbtn: "Reset",
    resetemail: "Сіздің тіркелген Email",
    pwdreset: "Сіздің жаңа пароліңіз жіберілді",
    register: "Жаңа қолданушыны Тіркеу",
    registerbtn: "Регистр",
    invaliduser: "Қате пайдаланушы аты мен құпия сөз",
    locate: "Үй",
    options: "Параметрлер",
    delete: "Жою",
    logout: "Шығу",
    isempty: " бос мүмкін емес",
    taken: " тіркелген, басқа көріңіз",
    invalidusername: "Сіздің электрондық пошта жарамсыз болып табылады",
    failed: "Бір нәрсе емес, қайталап көріңіз",
    success: "табыс",
    alarm: "Дабыл",
    alarmtitle: "Alarm Messages",
    navigate: "Navigate",
    startnav: "Бастау Navigate",
    sos: "SOS режимін іске қосыңыз",
    startmonitor: "Дауыстық Monitor іске қосыңыз",
    locatenow: "Енді табыңыз",
    confirmlocatesms: "Біз жіберуге растау, соңғы орнын алу үшін көруге мәтінді жіберу қажет?",
    sms: "SMS жіберу",
    history: "Орналасқан жері тарихы",
    mylocation: "Менің жері",
    kidlocation: "Балалар жері",
    startpoint: "Point бастап",
    endpoint: "Destination",
    addwatch: "Құрылғыны қосыңыз",
    add: "Қосу",
    markasread: "Оқылған деп белгілеу",
    morephonenumbers: "Телефон Numbers",
    recivesmsalert: "Alert хабарлама",
    setupfence: "Safezone",
    setupfence1: "Үй",
    setupfence2: "Мектеп",
    modifypwd: "Пароль өзгерту",
    feedback: "Кері байланыс",
    about: "Туралы",
    back: "Артқа",
    imei: "IMEI",
    ownername: "Балалар атауы",
    petname:"питомца зовут",
    simid: "Құрылғы телефоны",
    simcountrycode:  "Country Code",
    soscountrycode:  "Country Code",
    phonenumbers: "SOS Phone Numbers",
    locateinterval: "Kid Position алу уақыты Interval (M)",
    avatartxt: "Аватар",
    historyalarm: "Тарих Alarm",
    save: "Сақтау",
    oldpwd: "Ескі Құпия Сөз",
    newpwd: "Жаңа Құпия Сөз",
    submit: "Жіберу",
    invalidimei: "Жарамсыз IMEI нөмірі",
    dupaddwatch: "Сіз бұл сағаттар қосты",
    confirmremovedevice: "Сіз бұл сағаттар жойғыңыз келгені рас па? Сіз бұл сергек кез келген хабарларды алуға болады.",
    cancel: "Күшін жою",
    from: "Фото көзін таңдаңыз",
    fromlib: "Фото Кітапхана",
    fromcamera: "Суретке түсіру",
    invalidoldpwd: "Ескі Пароль дұрыс емес.",
    undefined: "Undefined",
    fencename: "Ат",
    radius: "Радиус",
    meter: "м",
    centerpoint: "Орталығы Point",
    send: "Жіберу",
    to: "Қарай",
    text: "Мәтін",
    sms2send: "Сіз өзіңіздің көру үшін мәтінді жолдау қажет:",
    cancelsend: "OK, Мен оны кейінірек жіберуге болады",
    alarmemail: "Alarm Email",
    viewinmap: "Картасына қарау",
    exitnav: "Exit Навигация",
    loadingtext: "тиеу",
    locatefailed: "Телефонды табылмады, бағдарлама параметрлерін оны жандандырады",
    alarm1: "Қауіпсіз аймаққа енгізіңіз",
    alarm4: "Қауіпсіз аймақ Out",
    alarm2: "Төтенше Alarm",
    alarm8: "Төмен батарея дабыл",
    alarm32: 'Watch detached',
    alarm64: 'Жылдамдық дабылы',
    noalarm: "Әлі жоқ оқылмаған дабыл",
    time: "Уақыт",
    address: "Мекен-жай",
    search: "Іздеу",
    nodata: "Мәліметтер жоқ",
    sosnumbers: "Төтенше Call Numbers",
    whitelistnumbers: "Рұқсатты сағаттар қоңырау шалуға болады",
    deldevice: "Бұл құрылғыны өшіріңіз",
    editprofile: "Бейінді редакциялау басыңыз",
    phonenumbers: "Телефон Numbers",
    batterymode: "Mode табыңыз",
    emergencymode: "Қауіпсіз режимі: 5 минут табыңыз",
    savingmode: "Батарея қуатын үнемдеу режиміне: 10 минут табыңыз",
    systemsetting: "System Setting",
    youradvice: "кез келген кеңес, кез келген шағым ...",
    timezone: "Timezone",
    notificationtitle: "Gator Watch Alarm",
    lastestlocation: "Соңғы табыңыз",
    device_lang:  "Watch Language",
    volume:  "Watch Volume",
    usedst:  "Daylight saving time",
    socketmodeoff:  "Power saving mode",
    childpoweroff: "Балалар өшіріп аласыз",
    retrieving: "Алынуда ...",
    smsbyapp: "Кейбір іс-қимыл Бұл байланыс қаламақы генерациялау мүмкін, сіздің телефон арқылы көруге қысқа мәтіндік жіберу пәрменін қажет.",
    days2exipre: " мерзімі өткен күн (лар)",
    exipred: "Бұл сағаттар мерзімі өтіп кеткен",
    monthmsgremain: "Хабарлар осы айда жібере аласыз",
    isadding: " Бұл сағаттар қосу, кейінірек көріңіз",
    alertsms: "Қашан Alarm SMS жіберу",
    verifycodemsg: "Сіз тексеру коды бойынша {}, пайдаланушы сұрауы тиіс. ол / ол app- ашуға болады> орнату -> [Watch] -> кодексі тексеріңіз",
    verifycode: "Кодексті тексеріңіз",
    verifycodetip: "Кодекс осы сағаттар қосу үшін пайдаланушыны тексеру үшін пайдаланылатын тексеру, пайдаланушы анықталған кезде ғана осы кодты ұсынады өтінеміз.",
    version: "нұсқа",
    ok: "ЖАҚСЫ",
    done: "Дайын",
    cancel: "күшін жою",
    msgcancelled: "Хабарлама күші жойылған",
    confirmpassword: "Құпия сөзді Растау",
    confirmpasswordnotequal: "Пароль сөзді растау, сол сияқты керек",
    gps: "ЖАҺАНДЫҚ ПОЗИЦИЯЛАУ ЖҮЙЕСІ",
    tower: "Base Station",
    wifi: "Wifi",
    phonetype0: "басқа",
    phonetype1: "әке",
    phonetype2: "ана",
    phonetype3: "әжесі",
    phonetype4: "атасы",
    phonetype5: 'Сыныптастар',
    phonetype: "түрі",
    name: "ат",
    reenter: "Қайта енгізіңіз",
    minichat: "Voices",
    sendvoice: "Ұстап тұрып, Speak",
    pulltorefresh: "Жаңарту үшін тартыңыз",
    me: "маған",
    unread: "оқылмаған",
    holdtip: "10 секунд ұстап тұрыңыз және Speak, макс ұзындығы",
    voicetoolarge: "Дауыстық 10 секунд асып, қайтадан жазып сұраймыз",
    novoice: "Әлі ешқандай дауыс",
    sending: "Жіберу ...",
    recording: "Перекодирование ... {time}  секунд (лар)",
    preparing: "Дайын Get ...",
    watchalarm: "дабыл",
    watchalarmdetail: "Дабыл орнату",
    morning: "А.М.",
    afternoon: "Премьер-Министр",
    today: "бүгін",
    everyday: "Күн сайын",
    repeat: "қайталау",
    day0: "күн",
    day1: "Mon",
    day2: "Сс",
    day3: "Ср",
    day4: "Бс",
    day5: "Жм",
    day6: "Sat",
    alarm16: "Жаңа Voice",
    confirmdeletealarm: "Осы дабылды жою үшін растаңыз",
    noalarms: "Әлі жоқ дабыл, қосу үшін басыңыз",
    smart: "Smart",
    starttime: "Бастау уақыты",
    endtime: "End Time",
    contain: "Құрамында",
    mynumber: "Менің телефон нөмірі",
    appqrcode: "App QR Code",
    dialbackno: "Кері теру Телефон нөмірі",

    moreadvancedsetting:  "Advanced Settings",
    hideself:  "Airplane Mode",
    hideselfdetail:  "Airplane Mode Settings",
    hideselfbegin:  "Start time:",
    hideselfend:  "End time:",
    nohidetimers: "Add Airplane Mode Settings",
    invalidendtime: "End time need greater than start time",
    enable: "Open",
    twotimerconflict: "Clash with following times：",

    homewifisetting: 'Zone WiFi Settings',
    homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
    accuracy: 'Accuracy',

    newappversion:  "New version",
    later:  "Later",
    upgrade:  "Upgrade",
    uptodate:  "Up to date",
    checkingupdate:  "Checking update...",

    disconnectedtips:  'Connecting to server, please wait...',
    uploadfailed: 'Upload failed',
    lightbulb: 'Light bulb',
    invalid: 'Invalid',
    phonelistisfull: 'The phone number list is full',
    serverinternalerror: 'Server internal error',
    addwatchtimeout: 'Add watch timeout',
    deletewatchtimeout: 'Delete watch timeout',
    registertimeout: 'Register timeout',
    registerfailed: 'Register failed',
    failed: 'failed',
    timeout: 'timeout',
    activedevice: 'connect watch',
    familynumbernotfound: 'phone number not found',
    updating: 'Updating...',

    disablewifilocation: 'Disable WiFi location',
    locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
    confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
    inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
    agreeprivacypolicy: 'You hereby agree to ',
    privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
    passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
    passworderror:'password error!',
    passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

    addAccount:'Add administrator permissions',
    notAccount:'No authority!',
    overlimitNumber: 'Add number overlimit',

    friends:"Баланың достары",
    Nameoflocator:"Локатордың атауы",
    LocatorNumber:"Локатор нөмірі",
    
    DeviceCode:"Құрылғы нұсқасы",
    DeviceName: "құрылғы атауы",
    SpeedAlarm: "Сигналды тездету",
    ActivePositioningMode: "Белсенді орналасу режимі",
    DeviceNotFeature: "Құрылғы бұл мүмкіндікті қолдамайды",
    RebootDevice: "Құрылғыны қайта іске қосу",
    ResetDevice: "Зауыт параметрлерін қалпына келтіру",
    timeInterval: "аралық",
    IncludingPositioning:'Құрамында Base Station',
    Whether:'Бар болса да',
    Obtain:"Қол жеткізіңіз",
    Device:"құрылғы",
    Transmission:"жіберілді",
    PasswordRese:"Құпия сөзді қалпына келтіру сәтсіз аяқталды. Әрекетті қайталап көріңіз",
    GatorUseName:"",
    NameWatchShown:"Аты сағатта көрсетілген",
    successfulActivation:"сәтті орнату",
    activationFailed: "сәтсіз орнату",
    antiTheft:"ұрлыққа қарсы функция",
}