//拉丁语

module.exports = {
	exitconfirm: "Confirmare exitum inveniunt",
	noexitconfirm: "Solent iterum alert",
	login: "Login",
	loginph: "Email",
	regemail: "Email AD usus es tesserae et reset",
	pwdph: "Password",
	forgotpwd: "Forgot password?",
	reset: "Reset password",
	resetbtn: "Reset",
	resetemail: "Email your registered",
	pwdreset: "Was sent to your new password",
	register: "Register new user",
	registerbtn: "Register",
	invaliduser: "Incorrect Password",
	locate: "Domum",
	options: "Occasus",
	delete: "Delete",
	logout: "Logout",
	isempty: " non inanis",
	taken: " fuerit profiterentur Conare",
	invalidusername: "Your email invalida",
	failed: "Aliquid deliqueris Aliquam",
	success: "success",
	alarm: "Terror",
	alarmtitle: "Terror Messages",
	navigate: "Navigate",
	startnav: "Start Navigate",
	sos: "Activate modum SOS",
	startmonitor: "Monitor activate Voice",
	locatenow: "Nunc locate",
	confirmlocatesms: "Ut situm latest vigilare oportet mittere text confirmasse mittam",
	sms: "Mittere SMS",
	history: "Location History",
	mylocation: "Location meum",
	kidlocation: "Location kids",
	startpoint: ", Unde proficiscitur",
	endpoint: "Destination",
	addwatch: "addere Fabrica",
	add: "Add",
	markasread: "Ut lectum",
	morephonenumbers: "Numbers phone",
	recivesmsalert: "Alert Notification",
	setupfence: "Safezone",
	setupfence1: "Domum",
	setupfence2: "Schola",
	modifypwd: "Password modify",
	feedback: "Feedback",
	about: "About",
	back: "Back",
	imei: "IMEI",
	ownername: "Puer Name",
	petname:"Nomen pet scriptor",
	simid: "Telephone apparatu",
	simcountrycode:  "Country Code",
	soscountrycode:  "Country Code",
	phonenumbers: "Phone Numbers SOS",
	locateinterval: "Per tempusculum of Questus Kid Position (M)",
	avatartxt: "Avatar",
	historyalarm: "History Alarm",
	save: "Nisi",
	oldpwd: "Tessera seni",
	newpwd: "New password",
	submit: "Submit",
	invalidimei: "Invalid IMEI Number",
	dupaddwatch: "Addideris hac custodia",
	confirmremovedevice: "Visne tu ista custodia tollere? Non ista custodia nuntiisque Durati acciperent.",
	cancel: "Cancel",
	from: "Select Photo Source",
	fromlib: "Bridgeman",
	fromcamera: "Take a Photo",
	invalidoldpwd: "Tessera vetus non sit vera.",
	undefined: "Undefined",
	fencename: "Nomen",
	radius: "Radius",
	meter: "m",
	centerpoint: "Centrum",
	send: "Mittere",
	to: "Ad",
	text: "Text",
	sms2send: "Tuum opus mittere textum custodiam",
	cancelsend: "OK, postea mittam",
	alarmemail: "Email terror",
	viewinmap: "View in Map",
	exitnav: "Exit Navigation",
	loadingtext: "loading",
	locatefailed: "Lorem posset collocare velit occasus possit in app",
	alarm1: "Enter tutum zona",
	alarm4: "De tutum zona",
	alarm2: "Emergency Alarm",
	alarm8: "Humilis altilium terror",
	alarm32: 'Watch detached',
	alarm64: 'celeritate terror',
	noalarm: "Non tamen unread terrores",
	time: "Tempus",
	address: "Address",
	search: "Search",
	nodata: "Non Data",
	sosnumbers: "Call Numbers emergency",
	whitelistnumbers: "Whitelist potest vigilia",
	deldevice: "Delete hoc fabrica",
	editprofile: "Click to edit Profile",
	phonenumbers: "Numbers phone",
	batterymode: "Locate Mode",
	emergencymode: "Tutus Modus: V minutis Save",
	savingmode: "Excepto altilium Mode: Locate in X minutes",
	systemsetting: "System setting",
	youradvice: "consilio fit, aliqua quereris ...",
	timezone: "Timezone",
	notificationtitle: "Vigilate metum Gator",
	lastestlocation: "Latest Locate",
	device_lang:  "Watch Language",
	volume:  "Watch Volume",
	usedst:  "Daylight saving time",
	socketmodeoff:  "Power saving mode",
	childpoweroff: "Puer Power Off",
	retrieving: "Retrieving ...",
	smsbyapp: "Agens aliqua actione need to send textus brevis mandatum per disciplínam tua phone, hoc generet communicatio feodo.",
	days2exipre: " day (s) ad exspiraverit",
	exipred: "Hac custodia lapso",
	monthmsgremain: "Messages mittere potest mensis huius",
	isadding: " est addendo hac custodia, Aliquam later",
	alertsms: "Cum mittere SMS Alarm",
	verifycodemsg: "Quæras user {}, for verificare code. ipse / potest illa aperire App-> Profecti -> [Watch] -> Verify Code",
	verifycode: "Verificare Code",
	verifycodetip: "Verificare Code solebat verificare user to add hac custodia, please offer this code modo cum user iubeant.",
	version: "Version",
	ok: "OK",
	done: "done",
	cancel: "Cancel",
	msgcancelled: "Nuntius cassari",
	confirmpassword: "confirm Password",
	confirmpasswordnotequal: "Password confirmare debet idem Password",
	gps: "GPS",
	tower: "basi Station",
	wifi: "Wifi",
	phonetype0: "other",
	phonetype1: "Pater",
	phonetype2: "Mater",
	phonetype3: "avia",
	phonetype4: "Grandpa",
	phonetype5: 'classmate',
	phonetype: "Type",
	name: "Name",
	reenter: "Please reintrare",
	minichat: "voces",
	sendvoice: "Tenendas et loquere",
	pulltorefresh: "Trahere ad refocillandum",
	me: "me",
	unread: "ILLECTUS",
	holdtip: "Tenendas et loquere max longitudine X seconds",
	voicetoolarge: "Vox excedit X secundis, commodo record iterum",
	novoice: "Tonitrua tamen",
	sending: "Mittens ...",
	recording: "Recoding tempore {time}  seconds (s)",
	preparing: "Tu ergo accinge lumbos ...",
	watchalarm: "Turbato per metum",
	watchalarmdetail: "Turbato per metum Profecti",
	morning: "AM",
	afternoon: "PM",
	today: "hodie",
	everyday: "Quotidie",
	repeat: "repeat",
	day0: "Sun",
	day1: "Mon",
	day2: "Tue",
	day3: "Wed",
	day4: "Thu",
	day5: "Fri",
	day6: "Sat",
	alarm16: "New Voice",
	confirmdeletealarm: "Confirmamus delete hoc concisus clangor increpuerit",
	noalarms: "Nulla metus adhuc addere click",
	smart: "dolor",
	starttime: "Satus tempus",
	endtime: "end Time",
	contain: "continet",
	mynumber: "Mea phone number",
	appqrcode: "QR code App",
	dialbackno: "Phone numerus dial back",
	moreadvancedsetting:  "Advanced Settings",
	hideself:  "Airplane Mode",
	hideselfdetail:  "Airplane Mode Settings",
	hideselfbegin:  "Start time:",
	hideselfend:  "End time:",
	nohidetimers: "Add Airplane Mode Settings",
	invalidendtime: "End time need greater than start time",
	enable: "Open",
	twotimerconflict: "Clash with following times：",

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  "New version",
	later:  "Later",
	upgrade:  "Upgrade",
	uptodate:  "Up to date",
	checkingupdate:  "Checking update...",

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
  registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Children \ 's amicos,",
	Nameoflocator:" Locator Nomine",
	LocatorNumber:"Locator numerus",
    
    DeviceCode:"versio fabrica",
	DeviceName :"fabrica nomen",
    SpeedAlarm :"celeritate terror",
    ActivePositioningMode :"activae positus modus",
    DeviceNotFeature : "support sed haec factura non fabrica",
    RebootDevice :"reboot",
    ResetDevice :"occasus Factory restituere",
    timeInterval :"Intervallum",
    IncludingPositioning:'continet basi Station',
	Whether:'Utrum sit',
	Obtain:"Vitam",
	Device:"fabrica",
	Transmission:"missum est",
	PasswordRese:"Password Reset defecit. Quaero, iterum conare",
	GatorUseName:"",
    NameWatchShown:"Nomen ostensum est in vigilia",
    successfulActivation:"feliciter erexit",
	activationFailed: "parum prospere profectus est",
  antiTheft:"anti-furtum munus",
  
  systolic :'Systoles sanguinem pressura',
diastolic:'Diastolic sanguinem pressura',
power:'imperium',
pulseRate:'pulsus rate',
oxygenSaturation:'oxygeni satietatem',
WeakPerfusion:'Index infirma sanguinem perfusion',
temperature:'corpus temperatus',
healthSettings:'Optiones sanus',
thermometer:'thermometrum',
oximeter:'Oximeter',
sphygmomanometer:'Vesalius',
son:'filius',
daughter:'daughter',
spouse:'Maritus et uxor,',
ordinaryAlarm:'General terror',
takeMedicine:'accipere potionem;',
drinkWater:'bibere copia aquae',
sedentaryReminder:'SEDENTARIUS in commonitione',
testReminder:'test signum',
}