//荷兰语

module.exports = {
	exitconfirm: "Afsluiten bevestigen",
	noexitconfirm: "Geen meldingen meer",
	login: "Inloggen",
	loginph: "Email",
	regemail: "E-mail wordt gebruikt om in te loggen en uw wachtwoord opnieuw in te stellen",
	pwdph: "Wachtwoord",
	forgotpwd: "Wachtwoord vergeten?",
	reset: "Opnieuw wachtwoord instellen",
	resetbtn: "Opnieuw instellen",
	resetemail: "Uw geregistreerde e-mail",
	pwdreset: "Uw nieuwe wachtwoord is verstuurd naar",
	register: "Registreer als nieuwe gebruiker",
	registerbtn: "Registreer",
	invaliduser: "Onjuiste gebruikersnaam en wachtwoord",
	locate: "Thuis",
	options: "Instellingen",
	delete: "Verwijder",
	logout: "Uitloggen",
	isempty: " Verplicht veld",
	taken: " is reeds geregistreerd, gebruik ander",
	invalidusername: "Uw e-mail is ongeldig",
	failed: "Is er iets misgegaan. Probeer alstublieft opnieuw",
	success: "Succes",
	alarm: "Alarm",
	alarmtitle: "Alarmmeldingen",
	navigate: "Navigeren",
	startnav: "Start Navigeren",
	sos: "Activeren SOS modus",
	startmonitor: "Activeer spraakberichten",
	locatenow: "Traceer nu",
	confirmlocatesms: "Een sms dient gestuurd te worden om de locatie van het horloge te bepalen. Akkoord?",
	sms: " Verzent SMS ",
	history: "Locatiegeschiedenis",
	mylocation: "Mijn locatie",
	kidlocation: "Locatie kind",
	startpoint: "Startpunt",
	endpoint: "Bestemming",
	addwatch: "Dodaj urządzenie",
	add: "Toevoegen",
	markasread: "Markeer als gelezen",
	morephonenumbers: "Telefoonnummers",
	recivesmsalert: "Meldingen",
	setupfence: "Veilige Zone",
	setupfence1: "Thuis",
	setupfence2: "School",
	modifypwd: "Wachtwoord wijzigen",
	feedback: "Terugkoppeling",
	about: "Over",
	back: "Terug",
	imei: "IMEI",
	ownername: "Naam kind",
	petname:"PET - name",
	simid: "Apparaattelefoon",
	simcountrycode:  "Country Code",
	soscountrycode:  "Country Code",
	phonenumbers: "SOS Telefoonnummers",
	locateinterval: "Tijdsfrequentie voor locatie updates (M)",
	avatartxt: "Foto",
	historyalarm: "Alarmgeschiedenis ",
	save: "Opslaan",
	oldpwd: "Oud wachtwoord",
	newpwd: "Nieuw wachtwoord",
	submit: "Versturen",
	invalidimei: "Ongeldige IMEI nummer",
	dupaddwatch: "U heeft het horloge succesvol toegevoegd",
	confirmremovedevice: "Weet u zeker dat u dit horloge wilt verwijderen? U zult geen berichten meer ontvangen van dit horloge.",
	cancel: "Annuleren",
	from: "Kies foto",
	fromlib: "Foto bibliotheek",
	fromcamera: "Maak een foto",
	invalidoldpwd: "Oude wachtwoord is niet correct.",
	undefined: "Ongeldig",
	fencename: "Naam",
	radius: "Straal",
	meter: "m",
	centerpoint: "Middelpunt",
	send: "Versturen",
	to: "Naar",
	text: "Tekst",
	sms2send: "U dien een sms te sturen naar uw horloge:",
	cancelsend: "Oké, ik zal het later te versturen",
	alarmemail: "E-mail meldingen",
	viewinmap: "Bekijk op de kaart",
	exitnav: "Navigatie afsluiten",
	loadingtext: "laden",
	locatefailed: "Niet mogelijk het de telefoon te localiseren. U kunt dit wijzijgen in de instelling van de app",
	alarm1: "Binnen Veilige Zone",
	alarm4: "Buiten Veilige Zone",
	alarm2: "SOS alarm",
	alarm8: "Batterij bijna leeg",
	alarm32: 'Watch detached',
	alarm64: 'Snelheidsalarm',
	noalarm: "Geen nieuwe meldingen",
	time: "Tijd",
	address: "Adres",
	search: "Zoeken",
	nodata: "Geen Informatie",
	sosnumbers: "Noodnummers",
	whitelistnumbers: "Lijst veilige telefoonnummers",
	deldevice: "Verwijder dit apparaat",
	editprofile: "Profielinstellingen",
	phonenumbers: "Telefoonnummers",
	batterymode: "Zoek Modus",
	emergencymode: "Veilige modus: Locatiebepaling vernieuwd elke 5 minuten",
	savingmode: "Energie besparingsmodus: Locatiebepaling vernieuwd elke 10 minutenn",
	systemsetting: "Systeeminstellingen",
	youradvice: "",
	timezone: "Tijdzone (GMT)",
	notificationtitle: "Alarm horloge",
	lastestlocation: "Laatste locatie",
	device_lang:  "Watch Language",
	volume:  "Watch Volume",
	usedst:  "Open zomertijd",
	socketmodeoff:  "Open energiebesparingsmodus",
	childpoweroff: "Mogelijkheid voor kind om horloge uit te zetten",
	retrieving: "Opgehaald ...",
	smsbyapp: "Sommige functionaliteiten van de app vereisen dat us een sms dient te sturen naar het horloge. Hiervoor kunnen extra netwerkkosten van toepassinge zijn.",
	days2exipre: " dag (en) te verlopen",
	exipred: "Dit horloge is verlopen",
	monthmsgremain: "Berichten kunnen deze maand sturen",
	isadding: " is dit horloge toe aan het voegen, probeer het later",
	alertsms: "SMS melding bij SOS activatie",
	verifycodemsg: "U moet de gebruiker {}, benaderen voor verificatie code. Ga naar app-> Instellingen-> [Horloge] -> Verificatiecode",
	verifycode: "Verificatiecode",
	verifycodetip: " Gebruik verificatiecode om het horloge aan andere app gebruikers te koppelen.",
	version: "Versie",
	ok: "OK",
	done: "Voltooid",
	cancel: "Annuleer",
	msgcancelled: "Bericht geannuleerd",
	confirmpassword: "Wachtwoord bevestigen",
	confirmpasswordnotequal: "Wachtwoord komt niet overeen, probeer opnieuw",
	gps: "GPS",
	tower: "Basis station",
	wifi: "Wifi",
	phonetype0: "ander",
	phonetype1: "Papar",
	phonetype2: "Mama",
	phonetype3: "Oma",
	phonetype4: "Opa",
	phonetype5: 'medeleerling',
	phonetype: "Anders",
	name: "Naam",
	reenter: "Gelieve opnieuw in te voeren",
	minichat: "Spraakberichten",
	sendvoice: "Vasthouden voor opname",
	pulltorefresh: "Herstellen",
	me: "Ik",
	unread: "Ongelezen",
	holdtip: "Vasthouden voor opname, max 10 seconden",
	voicetoolarge: "Bericht is langer dan 10 seconden, graag opnieuw",
	novoice: "Nog geen spraakberichten",
	sending: "Versturen ...",
	recording: "Opnemen ... {tijd}, second(en)",
	preparing: "Klaar voor...",
	watchalarm: "Alarm",
	watchalarmdetail: "Instellen alarm",
	morning: "AM",
	afternoon: "P.M",
	today: "Vandaag",
	everyday: "Elke dag",
	repeat: "Herhaling",
	day0: "Zo",
	day1: "Ma",
	day2: "Di",
	day3: "Wo",
	day4: "Do",
	day5: "Vr",
	day6: "Za",
	alarm16: "Nieuw spraakbericht",
	confirmdeletealarm: "Bevestig verwijderen alarm",
	noalarms: "Nog geen alarm, klik om toe te voegen",
	smart: "Slim",
	starttime: "Starttijd",
	endtime: "Eindtijd",
	contain: "Bevat",
	mynumber: "Mijn telefoonnummer",
	appqrcode: "App QR Code",
	dialbackno: "Telefoonnummer om terug te bellen",
	notsupported:  "U horlolge ondersteund gee spraakberichting",
	moreadvancedsetting:  "Advanced Settings",
	hideself:  "Airplane Mode",
	hideselfdetail:  "Airplane Mode Settings",
	hideselfbegin:  "Start time:",
	hideselfend:  "End time:",
	nohidetimers: "Add Airplane Mode Settings",
	invalidendtime: "End time need greater than start time",
	enable: "Open",
	twotimerconflict: "Clash with following times：",

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  "New version",
	later:  "Later",
	upgrade:  "Upgrade",
	uptodate:  "Up to date",
	checkingupdate:  "Checking update...",

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
	
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',

	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Child \ 's vrienden",
	Nameoflocator:"Naam van locator",
	LocatorNumber:"Locator nummer",
    
    DeviceCode:"Apparaatversie",
	DeviceName: "apparaatnaam",
    SpeedAlarm: "Snelheidsalarm",
    ActivePositioningMode: "Actieve positioneringsmodus",
    DeviceNotFeature: "Het apparaat ondersteunt deze functie niet",
    RebootDevice: "Apparaat opnieuw opstarten",
    ResetDevice: "Fabrieksinstellingen herstellen",
    timeInterval: "interval",
	IncludingPositioning:'Bevat Basis station',
	Whether:'Of er is',
	Obtain:"Verkrijgen",
	Device:"apparaat",
	Transmission:"is verzonden naar",
	PasswordRese:"Wachtwoord resetten mislukt. Probeer het opnieuw",
	GatorUseName:"",
    NameWatchShown:"Naam weergegeven op horloge",
    successfulActivation:"succesvol opgezet",
	activationFailed: "opgezet zonder succes",
  antiTheft:"anti-diefstal functie",
  
  systolic :'Systolische bloeddruk',
diastolic:'Diastolische bloeddruk',
power:'Kracht',
pulseRate:'Polsslag',
oxygenSaturation:'Bloedzuurstofverzadiging',
WeakPerfusion:'Zwakke perfusie-index',
temperature:'Lichaamstemperatuur',
healthSettings:'Gezondheidsinstellingen',
thermometer:'Thermometer',
oximeter:'Oximeter',
sphygmomanometer:'Bloeddrukmeter',
son:'Zoon',
daughter:'Dochter',
spouse:'Man en vrouw',
ordinaryAlarm:'Gewoon alarm',
takeMedicine:'Neem medicijnen',
drinkWater:'Drink water',
sedentaryReminder:'Sedentaire herinnering',
testReminder:'Test herinnering',
}