//波兰语

module.exports = {
	exitconfirm: "Potwierdź wyjście",
	noexitconfirm: "Nie ostrzegaj ponownie",
	login: "Zaloguj się",
	loginph: "E-mail",
	regemail: "E-mail używany do logowania i resetowania hasła",
	pwdph: "Hasło",
	forgotpwd: "Zapomniałeś hasło?",
	reset: "Resetuj hasło",
	resetbtn: "Zresetować",
	resetemail: "Twój E-mail zarejestrowany",
	pwdreset: "Twoje nowe hasło zostało przesłane do",
	register: "Rejestracja nowego użytkownika",
	registerbtn: "Rejestracja",
	invaliduser: "Nieprawidłowa nazwa użytkownika i hasło",
	locate: "Dom",
	options: "Ustawienia",
	delete: "Usunąć",
	logout: "Wyloguj",
	isempty: " Nie można opróżnić",
	taken: " został zarejestrowany, spróbuj innego",
	invalidusername: "Twój e-mail jest nieprawidłowy",
	failed: "Coś nie tak, spróbuj ponownie",
	success: "Sukces",
	alarm: "Alarm",
	alarmtitle: "Komunikaty alarmowe",
	navigate: "Nawiguj",
	startnav: "Rozpocznij nawigację",
	sos: "Włącz tryb SOS",
	startmonitor: "Aktywuj monitor głosowy",
	locatenow: "Odszukaj teraz",
	confirmlocatesms: "Musimy wysłać SMS, aby uzyskać najnowszą lokalizację, potwierdzasz wysłanie?",
	sms: "Wyślij SMS",
	history: "Historia lokalizacji",
	mylocation: "Moja lokalizacja",
	kidlocation: "Położenie dziecka",
	startpoint: "Punkt startowy",
	endpoint: "Miejsce przeznaczenia",
	addwatch: "Dodaj urządzenie",
	add: "Dodaj",
	markasread: "Oznacz jako przeczytane",
	morephonenumbers: "Kontakty",
	recivesmsalert: "Powiadamianie o",
	setupfence: "Strefy",
	setupfence1: "Dom",
	setupfence2: "Szkoła",
	modifypwd: "Zmiana hasła",
	feedback: "Informacja zwrotna",
	about: "O aplikacji",
	back: "Wstecz",
	imei: "IMEI",
	ownername: "Nazwa dziecka",
	petname:"zwierzaki nazwiska",
	simid: "Telefon urządzenia",
	simcountrycode:  "Państwo",
	soscountrycode:  "Kod kraju",
	phonenumbers: "Numery telefonów SOS",
	locateinterval: "Interwał czasowy uzyskania lokalizacji dziecka",
	avatartxt: "Zdjęcie",
	historyalarm: "Historia alarmów",
	save: "Zapisz",
	oldpwd: "Stare hasło",
	newpwd: "Nowe hasło",
	submit: "Zatwierdź",
	invalidimei: "Nieprawidłowy numer IMEI",
	dupaddwatch: "Dodałeś ten zegarek",
	confirmremovedevice: "Czy na pewno chcesz usunąć ten zegarek? Nie będziesz otrzymywać żadnych wiadomości od tego zegarka.",
	cancel: "Anuluj",
	from: "Wybierz źródło zdjęcia",
	fromlib: "Biblioteka zdjęć",
	fromcamera: "Zrób zdjęcie",
	invalidoldpwd: "Stare hasło nie jest poprawne.",
	undefined: "Niezdefiniowany",
	fencename: "Nazwa",
	radius: "Promień",
	meter: "m",
	centerpoint: "Center Point",
	send: "Wysłać",
	to: "Do",
	text: "Tekst",
	sms2send: "Musisz wysłać tekst do zegarka:",
	cancelsend: "OK, wyślę później",
	alarmemail: "Email alarm",
	viewinmap: "Zobacz na mapie",
	exitnav: "Wyjście z nawigacji",
	loadingtext: "Ładowanie",
	locatefailed: "Nie można zlokalizować telefonu, proszę go włączyć w ustawieniach aplikacji",
	alarm1: "Wejście do bezpiecznej strefy ",
	alarm4: "Wyjście z bezpiecznej strefy ",
	alarm2: "Alarm SOS",
	alarm8: "Stan wyczerpania baterii",
	alarm32: 'Ściągnięto zegarek',
	alarm64: 'Alarm prędkości',
	noalarm: "Brak nowych alarmów",
	time: "Czas",
	address: "Adres",
	search: "Szukaj",
	nodata: "Brak danych",
	sosnumbers: "Alarmowe numery telefonów",
	whitelistnumbers: "Biała lista dozwolone numery telefonów",
	deldevice: "Usuń to urządzenie",
	editprofile: "Edytuj profil",
	phonenumbers: "Kontakty",
	batterymode: "Tryb lokalizacji",
	emergencymode: "Tryb bezpieczny: aktualizuj lokalizację co 5 minut",
	savingmode: "Tryb oszczędzania baterii: aktualizuj lokalizację co 10 minut",
	systemsetting: "Ustawienia systemu",
	youradvice: "Masz jakieś propozycje usprawnień ? ...",
	timezone: "Strefa czasowa",
	notificationtitle: "Alarm zegarka",
	lastestlocation: "Najnowsza lokalizacja",
	device_lang:  "Język zegarka",
	volume:  "Głośność zegarka",
	usedst:  "Czas letni",
	socketmodeoff:  "Tryb oszczędzania energii",
	childpoweroff: "Dziecko możne wyłączyć zegarek",
	retrieving: "Pobieranie ...",
	smsbyapp: "Niektóre działania wymagają wysyłania wiadomości SMS, co może generować opłaty u operatora sieci komórkowej.",
	days2exipre: "  dni do wygaśnięcia",
	exipred: "Ten zegarek wygasł",
	monthmsgremain: "Wiadomości można wysyłać w tym miesiącu",
	isadding: "  dodajesz ten zegarek, spróbuj później.",
	alertsms: "Wyślij SMS, gdy alarm SOS zostanie przesłany",
	verifycodemsg: "Należy zapytać użytkownika {}, o kod weryfikujący. Przejdź do aplikacji-> Ustawienia -> [Watch] -> Kod weryfikacyjny",
	verifycode: "Kod weryfikujący",
	verifycodetip: "Użyj kodu weryfikacyjnego, aby upoważnić innych użytkowników aplikacji Gator do dodania tego zegarka.",
	version: "Wersja",
	ok: "OK",
	done: "Gotowe",
	cancel: "Anuluj",
	msgcancelled: "Wiadomość anulowana",
	confirmpassword: "Potwierdź hasło",
	confirmpasswordnotequal: "Hasło nie zgadza się, proszę spróbować ponownie",
	gps: "GPS",
	tower: "Stacja bazowa",
	wifi: "Wifi",
	phonetype0: "Inne",
	phonetype1: "Tata",
	phonetype2: "Mama",
	phonetype3: "Babcia",
	phonetype4: "Dziadek",
	phonetype5: 'Kolega z klasy',
	phonetype: "Rodzaj",
	name: "Imię",
	reenter: "Wpisz ponownie",
	minichat: "Mini czat",
	sendvoice: "Przytrzymaj i mów",
	pulltorefresh: "Pociągnij, aby odświeżyć",
	me: "Ja",
	unread: "Nieprzeczytany",
	holdtip: "Przytrzymaj i mów, max długość 10 sekund",
	voicetoolarge: "Słowa przekracza 10 sekund, należy ponownie nagrywać",
	novoice: "Brak głosów",
	sending: "Wysyłanie...",
	recording: "Nagrywanie... {time}  sekund (s)",
	preparing: "Gotowy ...",
	watchalarm: "Alarmy",
	watchalarmdetail: "Ustawienie alarmu",
	morning: "AM",
	afternoon: "PM",
	today: "Dzisiaj",
	everyday: "Codziennie",
	repeat: "Powtarzać",
	day0: "Nie",
	day1: "Pon",
	day2: "Wto",
	day3: "Śro",
	day4: "Czw",
	day5: "Pią",
	day6: "Sob",
	alarm16: "Nowy głos",
	confirmdeletealarm: "Potwierdź, aby usunąć ten alarm",
	noalarms: "Brak alarmu, kliknij aby dodać",
	smart: "Smart",
	starttime: "Czas rozpoczęcia",
	endtime: "Czas zakończenia",
	contain: "Uwzględnij",
	mynumber: "Mój numer telefonu",
	appqrcode: "Kod QR aplikacji",
	dialbackno: "Numer telefonu do oddzwonienia",
	moreadvancedsetting:  "Ustawienia zegarka",
	hideself:  "Wyłączaj",
	hideselfdetail:  "Ustaw tryb samolotowy",
	hideselfbegin:  "Czas rozpoczęcia:",
	hideselfend:  "Czas zakończenia:",
	nohidetimers: "Dodaj ustawienia trybu samolotowego",
	invalidendtime: "Czas zakończenia ma być wcześniej niż czas rozpoczęcia",
	enable: "Aktywuj",
	twotimerconflict: "Kolizja z następującymi czasami：",

	homewifisetting: 'Strefa WiFi ustawienia',
	homewificomments: 'Wybierz punkt dostępu WiFi używany w strefie bezpiecznej. Jeśli WiFi nie jest wyświetlane na poniższej liście, kliknij \'Anuluj \'',
	accuracy: 'Precyzja',

	newappversion:  "Nowa wersja",
	later:  "Później",
	upgrade:  "Aktualizacja",
	uptodate:  "Aktualny",
	checkingupdate:  "Sprawdź aktualizację...",

	disconnectedtips: 'Łączenie z serwerem, proszę czekać...',
	uploadfailed: 'Przesyłanie nie powiodło się',
	lightbulb: 'Uwaga',
	invalid: 'Nieważny',
	phonelistisfull: 'Lista numerów jest pełna',
	serverinternalerror: 'Wewnętrzny błąd serwera',
	addwatchtimeout: 'Dodaj ograniczenie czasu',
	deletewatchtimeout: 'Usuń ograniczenie czasu',
	Pleaseconfirm:"Please confirm",
	registertimeout: 'Rejestruj ograniczenie czasu',
	registerfailed: 'Rejestracja nie powiodła się',
	failed: 'Niepowodzenie',
	timeout: 'Limit czasu',
	activedevice: 'Podłącz zegarek',
	familynumbernotfound: 'Brak numeru telefonu',
	updating: 'Aktualizacja...',

	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Przyjaciele dziecka",
	Nameoflocator:"Nazwa lokalizatora",
	LocatorNumber:"Numer lokalizatora",
    
    DeviceCode:"Wersja urządzenia",
	DeviceName: "nazwa urządzenia",
    SpeedAlarm: "Alarm przyspieszenia",
    ActivePositioningMode: "Active Positioning Mode",
    DeviceNotFeature: "Urządzenie nie obsługuje tej funkcji",
    RebootDevice: "Restart urządzenia",
    ResetDevice: "Przywróć ustawienia fabryczne",
    timeInterval: "interval",
    IncludingPositioning:'Uwzględnij Stacja bazowa',
	Whether:'Czy jest',
	Obtain:"Uzyskać",
	Device:"urządzenie",
	Transmission:"zostało wysłane do",
	PasswordRese:"Reset hasła nie powiódł się. Proszę spróbuj ponownie",
	GatorUseName:"",
    NameWatchShown:"Nazwa wyświetlana na zegarku",
    successfulActivation:"skonfigurować pomyślnie",
	activationFailed: "skonfigurować bezskutecznie",
  antiTheft:"funkcja antykradzieżowa",
  
  systolic :'Skurczowe ciśnienie krwi',
diastolic:'Rozkurczowe ciśnienie krwi',
power:'Moc',
pulseRate:'Częstość tętna',
oxygenSaturation:'Nasycenie tlenem krwi',
WeakPerfusion:'Słaby wskaźnik perfuzji',
temperature:'Temperatura ciała',
healthSettings:'Ustawienia zdrowia',
thermometer:'Termometr',
oximeter:'Pulsoksymetr',
sphygmomanometer:'Sfigmomanometr',
son:'Synu',
daughter:'Córka',
spouse:'Mąż i żona',
ordinaryAlarm:'Zwykły alarm',
takeMedicine:'Weź lek',
drinkWater:'Pić wodę',
sedentaryReminder:'Przypomnienie o siedzeniu',
testReminder:'Przypomnienie testu',
}
