//葡萄牙语

module.exports = {
	exitconfirm: "Confirmar a saída",
	noexitconfirm: "Não alertará novamente",
	login: "Login",
	loginph: "Email",
	regemail: "Email usado para fazer login e redefinir sua palavra-passe",
	pwdph: "Palavara-passe",
	forgotpwd: "Esqueceu a palavra-passe?",
	reset: "Redifinir a palavra-passe",
	resetbtn: "Reset",
	resetemail: "O seu e-mail registado",
	pwdreset: "A sua nova palavra-passe foi enviada para",
	register: "Registar novo utilizador",
	registerbtn: "Registar",
	invaliduser: "Nome de utilizador e palavra-passe",
	locate: "Início",
	options: "Definições",
	delete: "Eliminar",
	logout: "Sair",
	isempty: " não é possível esvaziar",
	taken: " já foi registado, por favor tente outro",
	invalidusername: "O seu email é inválido",
	failed: "Algo correu mal. Por favor tente novamente",
	success: "Sucesso",
	alarm: "Alarme",
	alarmtitle: "Alertas de SOS",
	navigate: "Navegar",
	startnav: "Ir",
	sos: "Ativar modo SOS",
	startmonitor: "Ativar Monitor de Voz",
	locatenow: "Localizar Agora",
	confirmlocatesms: "É necessário enviar um SMS para o relógio para atualizar a localização. Confirmar?",
	sms: "Enviar SMS",
	history: "Histórico de Localizações",
	mylocation: "A Minha Localização",
	kidlocation: "Localização das Crianças",
	startpoint: "Ponto de Partida",
	endpoint: "Destino",
	addwatch: "Adicionar dispositivo",
	add: "Adicionar",
	markasread: "Marcar como Lido",
	morephonenumbers: "Números de Telefone",
	recivesmsalert: "Notificação de alerta",
	setupfence: "Zona Segura",
	setupfence1: "Casa",
	setupfence2: "Escola",
	modifypwd: "Modificar palavra-passe",
	feedback: "Comentários",
	about: "Sobre",
	back: "Anterior",
	imei: "IMEI",
	ownername: "Nome da Criança",
	petname:"Nome da estimação",
	simid: "Telefone do dispositivo",
	simcountrycode:  "Country Code",
	soscountrycode:  "Country Code",
	phonenumbers: "Números de Telefone SOS",
	locateinterval: "Intervalo de tempo para Atualizações da Localização (min)",
	avatartxt: "Foto",
	historyalarm: "Histórico de Alarmes",
	save: "Gravar",
	oldpwd: "Palavra-passe Antiga",
	newpwd: "Nova Palavra-passe",
	submit: "Submeter",
	invalidimei: "IMEI inválido",
	dupaddwatch: "Relógio adicionado com sucesso",
	confirmremovedevice: "Tem a certeza que deseja remover este relógio? Não receberá mais nenhumas mensagens deste relógio.",
	cancel: "Cancelar",
	from: "Selecione Origem da Foto",
	fromlib: "Biblioteca de Fotos",
	fromcamera: "Tirar uma Foto",
	invalidoldpwd: "Palavra-passe Antiga está incorreta",
	undefined: "Indefinido",
	fencename: "Nome",
	radius: "Raio",
	meter: "m",
	centerpoint: "Ponto Central",
	send: "Enviar",
	to: "Para",
	text: "Texto",
	sms2send: "É necessário enviar um SMS para o relógio:",
	cancelsend: "OK, enviarei mais tarde",
	alarmemail: "Alertas de Email",
	viewinmap: "Ver no Mapa",
	exitnav: "Sair da Navegação",
	loadingtext: "A carregar",
	locatefailed: "Não foi possível localizar o telefone, por favor ative-o nas definições da aplicação",
	alarm1: "Entrar na Zona de Segurança",
	alarm4: "Fora da Zona de Segurança",
	alarm2: "Alerta de SOS",
	alarm8: "Bateria fraca",
	alarm32: 'Watch detached',
	alarm64: 'Alarme de velocidade',
	noalarm: "Nenhum alerta novo",
	time: "Tempo",
	address: "Morada",
	search: "Pesquisa",
	nodata: "Sem Dados",
	sosnumbers: "Números de Emergência",
	whitelistnumbers: "Números Autorizados",
	deldevice: "Excluir este dispositivo",
	editprofile: "Ir Para Editar Perfil",
	phonenumbers: "Números de Telefone",
	batterymode: "Modo de Localização",
	emergencymode: "Modo de Segurança: Atualizações da Localização a Cada 5 minutos",
	savingmode: "Modo de Economia de Bateria: Atualizações da Localização a Cada 5 minutos",
	systemsetting: "Definição de Sistema",
	youradvice: "qualquer conselho, qualquer queixa ...",
	timezone: "Fuso Horário",
	notificationtitle: "Alarme de Relógio Gator",
	lastestlocation: "Última Localização",
	device_lang:  "Watch Language",
	volume:  "Watch Volume",
	usedst:  "Daylight saving time",
	socketmodeoff:  "Power saving mode",
	childpoweroff: "Permitir à Criança Desligar o Relógio",
	retrieving: "A Recuperar...",
	smsbyapp: "Algumas funções na aplicação requerem o envio de mensagens para o relógio. Tal pode implicar custos adicionais.",
	days2exipre: " dia(s) para expirar",
	exipred: "Este relógio expirou",
	monthmsgremain: "As mensagens podem enviar este mês",
	isadding: " está a adicionar este relógio, por favor tente mais tarde",
	alertsms: "Enviar SMS quando o SOS estiver ativado",
	verifycodemsg: "Deve perguntar ao utilizador {}, pelo código de verificação. Ir a app-> Definições -> [Relógio] -> Código de Verificação",
	verifycode: "Código de Verificação",
	verifycodetip: "Use o Código de Verificação para autorizar outros utilizadores da Aplicação Gator a adicionar este relógio",
	version: "Versão",
	ok: "OK",
	done: "Concluído",
	cancel: "Cancelar",
	msgcancelled: "Mensagem cancelada",
	confirmpassword: "Confirmar a Palavra-Passe",
	confirmpasswordnotequal: "A confirmação da Palavra-passe deve ser igual à Palavra-passe",
	gps: "GPS",
	tower: "Estação Base",
	wifi: "Wi-Fi",
	phonetype0: "De outros",
	phonetype1: "Pai",
	phonetype2: "Mãe",
	phonetype3: "Avó",
	phonetype4: "vovô",
	phonetype5: 'Colega de Classe',
	phonetype: "Tipo",
	name: "Nome",
	reenter: "Por favor, volte a introduzir",
	minichat: "vozes",
	sendvoice: "Segure e Speak",
	pulltorefresh: "Puxe para refrescar",
	me: "Eu",
	unread: "UnRead",
	holdtip: "Segure e Fala, max comprimento 10 segundos",
	voicetoolarge: "Voz excede 10 segundos, por favor, registre novamente",
	novoice: "Ainda não há vozes",
	sending: "Enviando ...",
	recording: "Recodificação ... {time}  segundo (s)",
	preparing: "Prepare-se...",
	watchalarm: "Alarme",
	watchalarmdetail: "definição de alarme",
	morning: "AM",
	afternoon: "PM",
	today: "Hoje",
	everyday: "Todos os dias",
	repeat: "Repita",
	day0: "Sol",
	day1: "Mon",
	day2: "Tue",
	day3: "Wed",
	day4: "Thu",
	day5: "Fri",
	day6: "Sentou",
	alarm16: "nova Voz",
	confirmdeletealarm: "Confirmar para excluir este alarme",
	noalarms: "Nenhum alarme ainda, clique para adicionar",
	smart: "Inteligente",
	starttime: "start Time",
	endtime: "Fim do tempo",
	contain: "contém",
	mynumber: "Meu número de telefone",
	appqrcode: "App QR Code",
	dialbackno: "Número de telefone para discar para trás",

	moreadvancedsetting:  "Advanced Settings",
	hideself:  "Airplane Mode",
	hideselfdetail:  "Airplane Mode Settings",
	hideselfbegin:  "Start time:",
	hideselfend:  "End time:",
	nohidetimers: "Add Airplane Mode Settings",
	invalidendtime: "End time need greater than start time",
	enable: "Open",
	twotimerconflict: "Clash with following times：",

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  "New version",
	later:  "Later",
	upgrade:  "Upgrade",
	uptodate:  "Up to date",
	checkingupdate:  "Checking update...",

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Amigos da criança",
	Nameoflocator:"Nome do localizador",
	LocatorNumber:"Número do localizador",
    
    DeviceCode:"Versão do dispositivo",
	DeviceName: "nome do dispositivo",
    SpeedAlarm: "Alarme de aceleração",
    ActivePositioningMode: "Modo de Posicionamento Ativo",
    DeviceNotFeature: "O dispositivo não suporta este recurso",
    RebootDevice: "Reinício do dispositivo",
    ResetDevice: "Restaurar configurações de fábrica",
    timeInterval: "intervalo",
    IncludingPositioning:'contém Estação Base',
	Whether:'Se existe',
	Obtain:"Obtivermos",
	Device:"dispositivo",
	Transmission:"foi enviado para",
	PasswordRese:"Falha na redefinição da senha. Por favor, tente novamente",
	GatorUseName:"",
    NameWatchShown:"Nome mostrado no relógio",
    successfulActivation:"configurar com sucesso",
	activationFailed: "configurar sem sucesso",
  antiTheft:"função anti-roubo",
  
  systolic :'Pressão arterial sistólica',
diastolic:'Pressão arterial diastólica',
power:'Poder',
pulseRate:'Taxa de pulso',
oxygenSaturation:'Saturação de oxigênio no sangue',
WeakPerfusion:'Índice de perfusão fraco',
temperature:'Temperatura corporal',
healthSettings:'Configurações de saúde',
thermometer:'Termômetro',
oximeter:'Oxímetro',
sphygmomanometer:'Esfigmomanômetro',
son:'Filho',
daughter:'Filha',
spouse:'Marido e mulher',
ordinaryAlarm:'Alarme comum',
takeMedicine:'Tomar remédio',
drinkWater:'Beber água',
sedentaryReminder:'Lembrete sedentário',
testReminder:'Lembrete de teste',
}