//罗马尼亚语

module.exports = {
	exitconfirm: "Confirma ieșire",
	noexitconfirm: "Alerta obiceiul din nou",
	login: "Log In",
	loginph: "Email",
	regemail: "Email folosit pentru autentificare și a reseta parola",
	pwdph: "Parolă",
	forgotpwd: "Ați uitat parola?",
	reset: "Reseteaza parola",
	resetbtn: "Restabili",
	resetemail: "Dvs. de email înregistrată",
	pwdreset: "Parola nouă a fost trimis la",
	register: "Inregistrare nou utilizator",
	registerbtn: "Inregistrare",
	invaliduser: "Nume de utilizator și parolă incorectă",
	locate: "Acasă",
	options: "Setări",
	delete: "Șterge",
	logout: "Logout",
	isempty: " Nu pot gol",
	taken: " a fost înregistrată, vă rugăm să încercați un alt",
	invalidusername: "Adresa dvs. de email nu este validă",
	failed: "E ceva în neregulă, vă rugăm să încercați din nou",
	success: "succes",
	alarm: "Alarmă",
	alarmtitle: "Mesaje de alarmă",
	navigate: "Navigați",
	startnav: "Start Navigare",
	sos: "Activați modul SOS",
	startmonitor: "Activa Monitor Voice",
	locatenow: "Găsiți acum",
	confirmlocatesms: "Avem nevoie de a trimite mesaje text pentru a viziona pentru a obține cele mai recente locație, confirma pentru a trimite?",
	sms: "Trimite SMS",
	history: "Istoricul locațiilor",
	mylocation: "Locația mea",
	kidlocation: "Copii Locație",
	startpoint: "Punct De Start",
	endpoint: "Destinație",
	addwatch: "Adăugați dispozitiv",
	add: "Adăuga",
	markasread: "Marcheaza Ca Citit",
	morephonenumbers: "Numere de telefon",
	recivesmsalert: "Notificare Alert",
	setupfence: "Safezone",
	setupfence1: "Acasă",
	setupfence2: "Școală",
	modifypwd: "Modifică parola",
	feedback: "Feedback",
	about: "Despre",
	back: "Înapoi",
	imei: "IMEI",
	ownername: "Nume copil",
	petname:"Nume animale",
	simid: "Dispozitiv telefon",
	simcountrycode:  "Country Code",
	soscountrycode:  "Country Code",
	phonenumbers: "SOS numere de telefon",
	locateinterval: "Timp Interval de a avea poziție Kid (M)",
	avatartxt: "Avatar",
	historyalarm: "Istoria de alarmă",
	save: "Salvați",
	oldpwd: "Parola Veche",
	newpwd: "Parola Noua",
	submit: "Prezenta",
	invalidimei: "Numărul IMEI invalid",
	dupaddwatch: "Ați adăugat acest ceas",
	confirmremovedevice: "Sigur doriți să eliminați acest ceas? Tu nu va primi niciun mesaj de la acest ceas.",
	cancel: "Anula",
	from: "Selectați Photo Source",
	fromlib: "Photo Library",
	fromcamera: "Fă o poză",
	invalidoldpwd: "Old Password nu este corect.",
	undefined: "Nedefinit",
	fencename: "Nume",
	radius: "Rază",
	meter: "m",
	centerpoint: "Center Point",
	send: "Trimite",
	to: "La",
	text: "Text",
	sms2send: "Aveți nevoie pentru a trimite un text la ceas:",
	cancelsend: "OK, voi trimite mai târziu",
	alarmemail: "Alarma Email",
	viewinmap: "Vezi în Map",
	exitnav: "Navigare ieșire",
	loadingtext: "încărcare",
	locatefailed: "Imposibil pentru a localiza telefonul, vă rugăm să activați în setările aplicației",
	alarm1: "Introduceți zonă de siguranță",
	alarm4: "Din zona de siguranță",
	alarm2: "Alarmă de urgență",
	alarm8: "Alarma de baterie descărcată",
	alarm32: 'Watch detached',
	alarm64: 'Alarma de viteză',
	noalarm: "Nu este alarmă necitite încă",
	time: "Timp",
	address: "Adresa",
	search: "Căutare",
	nodata: "Nu Există Date",
	sosnumbers: "Numere de urgență apel",
	whitelistnumbers: "Albă poate apela ceas",
	deldevice: "Ștergeți acest dispozitiv",
	editprofile: "Clic pentru a edita profilul",
	phonenumbers: "Numere de telefon",
	batterymode: "Localizați Mode",
	emergencymode: "Safe Mode: Localizați în 5 minute",
	savingmode: "Mod de economisire a bateriei: Localizați în 10 minute",
	systemsetting: "Setare sistem",
	youradvice: "orice sfat, orice plâng ...",
	timezone: "Fus Orar",
	notificationtitle: "Gator Watch Alarm",
	lastestlocation: "Cele mai recente Localizați",
	device_lang:  "Watch Language",
	volume:  "Watch Volume",
	usedst:  "Daylight saving time",
	socketmodeoff:  "Power saving mode",
	childpoweroff: "Copil poate alimenta Off",
	retrieving: "Preluarea ...",
	smsbyapp: "Unele măsuri trebuie să trimită comenzi text scurt pentru a viziona de telefon, aceasta poate genera taxă de comunicare.",
	days2exipre: " zi (le) pentru a expirat",
	exipred: "Acest ceas a expirat",
	monthmsgremain: "Mesajele pot trimite în această lună",
	isadding: " este adăugarea acest ceas, vă rugăm să încercați mai târziu",
	alertsms: "Trimite SMS Când Alarm",
	verifycodemsg: "Ar trebui să ceară de utilizator {}, pentru a verifica cod. el / ea poate deschide App> Setare -> [Watch] -> Verificați codul",
	verifycode: "Verifica Codul",
	verifycodetip: "Verificați codul folosit pentru a verifica utilizator pentru a adăuga acest ceas, va rugam sa ofere acest cod doar atunci când utilizatorul identificat.",
	version: "versiune",
	ok: "BINE",
	done: "făcut",
	cancel: "Anulare",
	msgcancelled: "mesajul anulat",
	confirmpassword: "Confirmă parola",
	confirmpasswordnotequal: "Confirmați parola ar trebui la fel ca Password",
	gps: "GPS",
	tower: "Base Station",
	wifi: "Wifi",
	phonetype0: "Alte",
	phonetype1: "tată",
	phonetype2: "Mamă",
	phonetype3: "bunică",
	phonetype4: "bunic",
	phonetype5: 'coleg de clasă',
	phonetype: "Tip",
	name: "Nume",
	reenter: "Reintroduceți",
	minichat: "voci",
	sendvoice: "Deține și Vorbește",
	pulltorefresh: "Trageți pentru a reîmprospăta",
	me: "Pe mine",
	unread: "necitite",
	holdtip: "Deține și Vorbește, max lungime de 10 secunde",
	voicetoolarge: "Voce depășește 10 secunde, vă rugăm să înregistra din nou",
	novoice: "Nu există voci încă",
	sending: "Se trimite ...",
	recording: "Recoding ... {time}  secunde (s)",
	preparing: "Pregateste-te...",
	watchalarm: "Alarma",
	watchalarmdetail: "Setarea alarmei",
	morning: "AM",
	afternoon: "PM",
	today: "Astăzi",
	everyday: "In fiecare zi",
	repeat: "Repeta",
	day0: "Soare",
	day1: "mon",
	day2: "Marti",
	day3: "Mie",
	day4: "Joi",
	day5: "Vi",
	day6: "Sat",
	alarm16: "vocală nouă",
	confirmdeletealarm: "Confirmare pentru a șterge această alarmă",
	noalarms: "Nu este alarmă încă, faceți clic pentru a adăuga",
	smart: "Inteligent",
	starttime: "Timpul de începere",
	endtime: "Ora de terminare",
	contain: "Conține",
	mynumber: "Numărul meu de telefon",
	appqrcode: "App QR Code",
	dialbackno: "Număr de telefon formați înapoi",


	moreadvancedsetting:  "Advanced Settings",
	hideself:  "Airplane Mode",
	hideselfdetail:  "Airplane Mode Settings",
	hideselfbegin:  "Start time:",
	hideselfend:  "End time:",
	nohidetimers: "Add Airplane Mode Settings",
	invalidendtime: "End time need greater than start time",
	enable: "Open",
	twotimerconflict: "Clash with following times：",

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  "New version",
	later:  "Later",
	upgrade:  "Upgrade",
	uptodate:  "Up to date",
	checkingupdate:  "Checking update...",

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Prietenii copilului",
	Nameoflocator:"Numele locatorului",
	LocatorNumber:"Numărul locatorului",
    
    DeviceCode:"Dispozitiv versiune",
	DeviceName: "nume dispozitiv",
    SpeedAlarm: "accelerarea alarmei",
    ActivePositioningMode: "Mod de poziționare activă",
    DeviceNotFeature: "Dispozitivul nu acceptă această caracteristică",
    RebootDevice: "Repornire dispozitiv",
    ResetDevice: "Restaurați setările din fabrică",
    timeInterval: "interval",
	IncludingPositioning:'Conține Base Station',
	Whether:'Fie că există',
	Obtain:"Obține",
	Device:"dispozitiv",
	Transmission:"a fost trimis la",
	PasswordRese:"Resetarea parolei eșuată Vă rugăm să încercați din nou",
	GatorUseName:"",
    NameWatchShown:"Numele afișat în ceas",
    successfulActivation:"configurați cu succe",
	activationFailed: "configurați fără succes",
	antiTheft:"funcție anti-furt",
}