//俄语

module.exports = {
  exitconfirm: "Подтвердить выход",
  noexitconfirm: "Не показывать снова",
  login: "Войти",
  loginph: "Email",
  regemail: "Email для входа в систему и сброса пароля",
  pwdph: "Пароль",
  forgotpwd: "Забыли пароль?",
  reset: "Сброс пароля",
  resetbtn: "Сбросить",
  resetemail: "Ваш Email",
  pwdreset: "Ваш новый пароль отправлен ",
  register: "Регистрация",
  registerbtn: "Зарегистрировать",
  invaliduser: "Неверное имя пользователя или пароль",
  locate: "Главная",
  options: "Настройки",
  delete: "Удалить",
  logout: "Выйти",
  isempty: "отсутствует",
  taken: " уже существует, попробуйте другой",
  invalidusername: "Неверный Email",
  failed: "Ошибка, попробуйте еще раз",
  success: "успешно",
  alarm: "Оповещения",
  alarmtitle: "Журнал",
  navigate: "Навигатор",
  startnav: "Начать",
  sos: "Следить онлайн",
  startmonitor: "Скрытый звонок",
  locatenow: "Найти сейчас",
  confirmlocatesms: "Нужно отправить SMS, чтобы обновить местоположение, подтвердить отправку?",
  sms: "SMS",
  history: "История ",
  mylocation: "Мое местоположение",
  kidlocation: "Местоположение часов",
  startpoint: "Отправная точка",
  endpoint: "Пункт назначения",
  addwatch: "Добавить устройство",
  add: "Добавить",
  markasread: "Пометить как прочитанное",
  morephonenumbers: "Контакты",
  recivesmsalert: "Push-уведомления",
  setupfence: "Безопасная зона",
  setupfence1: "Дом",
  setupfence2: "Школа",
  modifypwd: "Изменить пароль",
  feedback: "Обратная связь",
  about: "О приложении",
  back: "Назад",
  imei: "IMEI",
  ownername: "Имя ребенка",
  petname: "Имя животное",
  simid: "Телефон устройства",
  simcountrycode: "Код страны",
  soscountrycode: "Код страны",
  phonenumbers: "Номера SOS",
  locateinterval: "Интервал обновления местоположения (м)",
  avatartxt: "Фотография",
  historyalarm: "История ",
  save: "Сохранить",
  oldpwd: "Действующий пароль",
  newpwd: "Новый пароль",
  submit: "Подтвердить",
  invalidimei: "Неверный IMEI",
  dupaddwatch: "Часы добавлены",
  confirmremovedevice: "Вы уверены, что хотите удалить часы? Вы больше не сможете получать оповещения от часов.",
  cancel: "Отмена",
  from: "Выберите фотографию",
  fromlib: "Из галереи",
  fromcamera: "Сделать снимок",
  invalidoldpwd: "Неверный действующий пароль.",
  undefined: "Не указано",
  fencename: "Название",
  radius: "Радиус",
  meter: "м",
  centerpoint: "Центральная точка",
  send: "Отправить",
  to: "Кому",
  text: "Текст",
  sms2send: "Отправьте сообщение на часы",
  cancelsend: "Хорошо, отправлю позже",
  alarmemail: "Email оповещения",
  viewinmap: "Посмотреть на карте",
  exitnav: "Выход из навигатора",
  loadingtext: "загрузка",
  locatefailed: "Не удалось обнаружить часы, пожалуйста, добавьте их в настройках приложения",
  alarm1: "Вход в зону",
  alarm4: "Выход из зоны",
  alarm2: "Сигнал тревоги SOS",
  alarm8: "Низкий заряд батареи",
  alarm32: 'Watch detached',
  alarm64: 'Сигнал скорости',
  noalarm: "Не прочитанных нет",
  time: "Время",
  address: "Адрес",
  search: "Поиск",
  nodata: "Нет данных",
  sosnumbers: "Экстренные телефонные номера",
  whitelistnumbers: "Разрешенные телефонные номера",
  deldevice: "Удалить это устройство",
  editprofile: "Редактировать профиль",
  phonenumbers: "Телефонные номера",
  batterymode: "Интервал слежения",
  emergencymode: "Безопасный",
  savingmode: "Экономичный",
  systemsetting: "Системные настройки",
  youradvice: "Ваши вопросы или пожелания…",
  timezone: "Часовой пояс",
  notificationtitle: "Оповещение от Gator",
  lastestlocation: "Обновлено",
  device_lang: "часы язык",
  volume: "часы звук",
  usedst: "Daylight saving time",
  socketmodeoff: "Power saving mode",
  childpoweroff: "Разрешить выключать часы",
  retrieving: "Получение…",
  smsbyapp: "При настройке определенных функций необходимо будет отправить с Вашего мобильного устройства SMS сообщения, за которые может взиматься плата по тарифам оператора.",
  days2exipre: "дня (ей) до истечения срока действия",
  exipred: "Время ожидания истекло",
  monthmsgremain: "В этом месяце можно отправить сообщений",
  isadding: "добавляет эти часы, пожалуйста, попробуйте позже",
  alertsms: "SMS оповещение",
  verifycodemsg: "Узнайте у пользователя код верификации. (В приложении: Настройки -> [Часы] -> Код верификации)",
  verifycode: "Код верификации",
  verifycodetip: "Чтобы открыть доступ к часам другому пользователю, пожалуйста, предоставьте данный код.",
  version: "Версия",
  ok: "OK",
  done: "Готово",
  cancel: "Отмена",
  msgcancelled: "Сообщение отменено",
  version: "версия",
  ok: "OK",
  done: "Готово",
  cancel: "Отмена",
  msgcancelled: "Сообщение отменено",
  confirmpassword: "Подтвердите Пароль",
  confirmpasswordnotequal: "Подтвердите Пароль",
  gps: "GPS",
  tower: "Базовая станция",
  wifi: "Wi-Fi",
  phonetype0: "Другие",
  phonetype1: "Папа",
  phonetype2: "Мама",
  phonetype3: "Бабушка",
  phonetype4: "Дедушка",
  phonetype5: 'одноклассник',
  phonetype: "Тип",
  name: "Ваше имя",
  reenter: "Пожалуйста, введите еще раз",
  minichat: "Чат",
  sendvoice: "Удерживайте и говорите",
  pulltorefresh: "Потяните, чтобы обновить",
  me: "мне",
  unread: "Не прочитано",
  holdtip: "Удерживайте и говорите, максимальная длительность записи - 10 секунд",
  voicetoolarge: "Если запись превышает 10 секунд, запишите снова",
  novoice: "Голосовых сообщений нет",
  sending: "Отправка ...",
  recording: "Запись...{время} в секундах (s)",
  preparing: "Приготовьтесь...",
  watchalarm: "Будильник",
  watchalarmdetail: "Установка будильника",
  morning: "ДНЯ",
  afternoon: "ВЕЧЕРА",
  today: "Cегодня",
  everyday: "Каждый день",
  repeat: "Повторение",
  day0: "Вс",
  day1: "Пн",
  day2: "Вт",
  day3: "Ср",
  day4: "Чт",
  day5: "Пт",
  day6: "Сб",
  alarm16: "Новое голосовое сообщение",
  confirmdeletealarm: "Подтвердите удаление будильника",
  noalarms: "Будильник не установлен, нажмите для установки будильника",
  smart: "интеллектуальная",
  starttime: "Время начала",
  endtime: "Время окончания",
  contain: "Содержит",
  mynumber: "Мой номер телефона",
  appqrcode: "QR код приложения",
  dialbackno: "Обратный вызов на номер",

  moreadvancedsetting: "Advanced Settings",
  hideself: "Airplane Mode",
  hideselfdetail: "Airplane Mode Settings",
  hideselfbegin: "Start time:",
  hideselfend: "End time:",
  nohidetimers: "Add Airplane Mode Settings",
  invalidendtime: "End time need greater than start time",
  enable: "Open",
  twotimerconflict: "Clash with following times：",

  homewifisetting: 'Zone WiFi Settings',
  homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
  accuracy: 'Accuracy',

  newappversion: "New version",
  later: "Later",
  upgrade: "Upgrade",
  uptodate: "Up to date",
  checkingupdate: "Checking update...",

  disconnectedtips: 'Connecting to server, please wait...',
  uploadfailed: 'Upload failed',
  lightbulb: 'Light bulb',
  invalid: 'Invalid',
  phonelistisfull: 'The phone number list is full',
  serverinternalerror: 'Server internal error',
  addwatchtimeout: 'Add watch timeout',
  deletewatchtimeout: 'Delete watch timeout',
  registertimeout: 'Register timeout',
  registerfailed: 'Register failed',
  failed: 'failed',
  timeout: 'timeout',
  activedevice: 'connect watch',
  familynumbernotfound: 'phone number not found',
  updating: 'Updating...',

  disablewifilocation: 'Disable WiFi location',
  locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
  confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
  inputfencename: 'Enter Safezone Name',

  Pleaseconfirm: "Please confirm",
  agreeprivacypolicy: 'You hereby agree to ',
  privacypolicytitle: 'Privacy Policy',
  commonsecret: 'The password is the same, please retype',
  passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
  passworderror: 'password error!',
  passworderror5: 'Account locked as password incorrect. Please wait 1 minutes and try again.',

  addAccount: 'Add administrator permissions',
  notAccount: 'No authority!',
  overlimitNumber: 'Add number overlimit',

  friends: "Друзья ребёнка",
  Nameoflocator: "Имя локатора",
  LocatorNumber: "Номер локатора",

  DeviceCode: "Версия устройства",
  DeviceName: "имя устройства",
  SpeedAlarm: "Ускорение сигнала тревоги",
  ActivePositioningMode: "Режим активного позиционирования",
  DeviceNotFeature: "Устройство не поддерживает эту функцию",
  RebootDevice: "Перезапуск устройства",
  ResetDevice: "Восстановить заводские настройки",
  timeInterval: "интервал",
  IncludingPositioning: 'Содержит Базовая станция',
  Whether: 'Есть ли',
  Obtain: "получать",
  Device: "устройство",
  Transmission: "был отправлен",
  PasswordRese: "Сброс пароля не выполнен. Пожалуйста, попробуйте еще раз",
  GatorUseName: "",
  NameWatchShown: "Имя показывается на часах",
  successfulActivation: "успешно настроен",
  activationFailed: "настроить неудачно",
  antiTheft: "противоугонная функция",

  systolic: 'Систолическое артериальное давление',
  diastolic: 'Диастолическое артериальное давление',
  power: 'мощность',
  pulseRate: 'Частота пульса',
  oxygenSaturation: 'Насыщение крови кислородом',
  WeakPerfusion: 'Индекс слабой перфузии',
  temperature: 'Температура тела',
  healthSettings: 'Настройки здоровья',
  thermometer: 'термометр',
  oximeter: 'оксигемометр',
  sphygmomanometer: 'сфигмоманометр',
  son: 'сын',
  daughter: 'дочь',
  spouse: 'Муж и жена',
  ordinaryAlarm:'Обычная тревога',
  takeMedicine:'Принимать лекарства',
  drinkWater:'Пить воду',
  sedentaryReminder:'Сидячий напоминание',
  testReminder:'Тестовое напоминание',
}