//斯洛伐克语

module.exports = {
	exitconfirm: "Potvrdiť ukončenie",
	noexitconfirm: "Znovu upozorniť",
	login: "Prihlásiť sa",
	loginph: "Email",
	regemail: "E-mail slúži na prihlásenie a resetovanie hesla",
	pwdph: "Heslo",
	forgotpwd: "Zabudol si heslo?",
	reset: "Obnoviť heslo",
	resetbtn: "Obnoviť",
	resetemail: "Váš e-mail registrovaný",
	pwdreset: "Vaše nové heslo bolo zaslané",
	register: "Registrácia nového užívateľa",
	registerbtn: "Register",
	invaliduser: "Nesprávne používateľské meno a heslo",
	locate: "Domov",
	options: "Nastavenie",
	delete: "Vymazať",
	logout: "Odhlásiť sa",
	isempty: " nemôže byť prázdne",
	taken: " bola zaregistrovaná, prosím, skúste to s inou",
	invalidusername: "Váš e-mail je neplatný",
	failed: "Niečo sa deje, skúste to prosím znova",
	success: "úspech",
	alarm: "Poplach",
	alarmtitle: "Poplašné správy",
	navigate: "Navigovať",
	startnav: "Začiatok Navigácia",
	sos: "Aktivácia režimu SOS",
	startmonitor: "Aktivácia hlasového Monitoru",
	locatenow: "Vyhľadajte teraz",
	confirmlocatesms: "Musíme poslať textovú správu, aby sme zistili posledné miesto polohy, poslať?",
	sms: "Pošlite SMS",
	history: "Miesto histórie",
	mylocation: "Moja poloha",
	kidlocation: "Umiestnenie detí",
	startpoint: "Východiskový bod",
	endpoint: "Destinácia",
	addwatch: "Pridať zariadenie",
	add: "Pridať",
	markasread: "Označiť ako prečítané",
	morephonenumbers: "Telefónne čísla",
	recivesmsalert: "Oznámenia o upozorneniach",
	setupfence: "Bezpečné zóny",
	setupfence1: "Domov",
	setupfence2: "Škola",
	modifypwd: "Zmeniť heslo",
	feedback: "Spätná väzba",
	about: "O aplikácii",
	back: "Späť",
	imei: "IMEI",
	ownername: "Meno dieťaťa",
	petname:"Názov Petu",
	simid: "Zariadenie telefónu",
	simcountrycode:  "Kód krajiny",
	soscountrycode:  "Kód krajiny",
	phonenumbers: "Telefónne čísla pre volania SOS",
	locateinterval: "Časový interval pre získanie polohy dieťaťa (M)",
	avatartxt: "Foto dieťaťa",
	historyalarm: "História alarmov",
	save: "Uložiť",
	oldpwd: "Staré Heslo",
	newpwd: "Nové Heslo",
	submit: "Predložiť",
	invalidimei: "Neplatné číslo IMEI",
	dupaddwatch: "Pridali ste tieto hodinky",
	confirmremovedevice: "Ste si istí, že chcete odstrániť tieto hodinky? Po odstránení nebudete dostávať žiadne správy z týchto hodiniek.",
	cancel: "Zrušiť",
	from: "Vyberte Zdroj fotografií",
	fromlib: "Foto galéria",
	fromcamera: "Odfoťte",
	invalidoldpwd: "Staré heslo nie je správne.",
	undefined: "Nedefinované",
	fencename: "Názov",
	radius: "Rádius",
	meter: "m",
	centerpoint: "Centrálny bod",
	send: "Poslať",
	to: "Na",
	text: "Text",
	sms2send: "Musíte poslať textovú správu na hodinky:",
	cancelsend: "OK, pošlem ju neskôr",
	alarmemail: "Alarm email",
	viewinmap: "Zobraziť na mape",
	exitnav: "Výstup z navigácie",
	loadingtext: "nakladanie",
	locatefailed: "Nemôžme nájsť telefón, prosím, povoľte jeho hľadanie v nastavení aplikácie",
	alarm1: "Vstup do bezpečnej zóny ",
	alarm4: "Mimo bezpečnej zóny ",
	alarm2: "Núdzový Alarm",
	alarm8: "Upozornenie na vybitú batériu",
	alarm32: 'Hodinky odpojené',
	alarm64: 'Alarm rýchlosti',
	noalarm: "Zatiaľ žiadne neprečítané upozornenia",
	time: "Doba",
	address: "Adresa",
	search: "Vyhľadávanie",
	nodata: "Žiadne údaje",
	sosnumbers: "Čísla tiesňového volania",
	whitelistnumbers: "Zoznam čísel, ktoré môžu volať hodinky",
	deldevice: "Odstráňte toto zariadenie",
	editprofile: "Kliknite pre upravenie profilu",
	phonenumbers: "Telefónne čísla",
	batterymode: "Vyhľadajte mód",
	emergencymode: "Bezpečný mód: Nájsť za 5 minút",
	savingmode: "Úsporný režim batérie: Nájsť za 10 minút",
	systemsetting: "Nastavenie systému",
	youradvice: "Napíšte nejakú radu, akúkoľvek sťažnosť...",
	timezone: "Časové pásmo",
	notificationtitle: "Upozornenie z hodiniek GATOR",
	lastestlocation: "Vyhľadajte najnovšie",
	device_lang:  "Jazyk hodiniek",
	volume:  "Hlasitosť hodiniek",
	usedst:  "Zapnutie letného času",
	socketmodeoff:  "Úsporný režim",
	childpoweroff: "Dieťa môže vypnúť hodinky",
	retrieving: "Načítanie ...",
	smsbyapp: "Pre niektoré akcie potrebujete poslať krátku textovú správu pre sledovanie na vašom telefóne, to môže vytvoriť zvýšené poplatky.",
	days2exipre: " deň (y), aby vypršala",
	exipred: "vypršala pre tieto hodinky",
	monthmsgremain: "Správy môžu posielať tento mesiac",
	isadding: " pridanie týchto hodiniek, skúste to prosím neskôr",
	alertsms: "Pre Alarm pošlite SMS",
	verifycodemsg: "Mali by ste sa opýtať používateľa {} pre overenie kódu. on / ona môže otvoriť app-> Nastavenia -> [hodinky] -> Kód overenia",
	verifycode: "Kód overenia",
	verifycodetip: "Tento kód slúži na overenie užívateľa pre pridenie hodiniek v inom mobilnom telefóne, tento kód je dôverný a neodporúčame poskytovať ho verejne. Chránťe ho pred zenužitím!",
	version: "verzia",
	ok: "OK",
	done: "hotové",
	cancel: "Zrušiť",
	msgcancelled: "správa zrušená",
	confirmpassword: "Potvrďte heslo",
	confirmpasswordnotequal: "Potvrdené heslo musí byť rovnaké ako heslo",
	gps: "GPS",
	tower: "Mobilná BTS",
	wifi: "Wifi bod",
	phonetype0: "iné",
	phonetype1: "Otec",
	phonetype2: "Mamka",
	phonetype3: "Babka",
	phonetype4: "Dedko",
	phonetype5: 'spolužiak',
	phonetype: "Typ osoby",
	name: "Názov",
	reenter: "Prosím, zadajte znova",
	minichat: "Hlasové správy",
	sendvoice: "Držte a hovorte",
	pulltorefresh: "Stlačte pre obnovenie",
	me: "Odo mňa",
	unread: "Neprečítané",
	holdtip: "Držte a hovorte, max dĺžka 10 sekúnd",
	voicetoolarge: "Hlasová správa je dlhšia ako 10 sekúnd, zopakujte znova",
	novoice: "Zatiaľ žiadne hlasové správy",
	sending: "Odosielanie ...",
	recording: "Prekódovanie ... {time}  sekúnd (y)",
	preparing: "Pripraviť sa...",
	watchalarm: "alarm",
	watchalarmdetail: "nastavenie alarmu",
	morning: "dopoludnia",
	afternoon: "popoludní",
	today: "dnes",
	everyday: "Každý deň",
	repeat: "opakovanie",
	day0: "nedeľa",
	day1: "pondelok",
	day2: "utorok",
	day3: "streda",
	day4: "štvrtok",
	day5: "Piatok",
	day6: "sobota",
	alarm16: "nová správa",
	confirmdeletealarm: "Potvrďte odstránenie tohto upozornenia",
	noalarms: "Zatiaľ žiadne upozornenia, kliknite na tlačidlo Pridať",
	smart: "inteligentné",
	starttime: "doba spustenia",
	endtime: "čas ukončenia",
	contain: "obsahuje",
	mynumber: "Moje telefónne číslo",
	appqrcode: "QR kód aplikácie",
	dialbackno: "vytočiť späť telefónne číslo",
	moreadvancedsetting:  "Pokročilé nastavenia",
	hideself:  "Letový mód",
	hideselfdetail:  "Nastavenie letového módu",
	hideselfbegin:  "Čas začiatku:",
	hideselfend:  "Čas ukončenia:",
	nohidetimers: "Pridať nastavenie letového módu",
	invalidendtime: "Čas ukončenia je vyšší ako čas začiatku",
	enable: "Povoliť",
	twotimerconflict: "Nastaviť s nasledujúcimi časmi：",

	homewifisetting: 'Nastavenie domácej WiFi siete',
	homewificomments: 'Prosím vyberte WiFi sieť, ktorú používate doma pre pripojenie. Ak vaša WiFi sieť nie je v zozname, potom zvoľte \'Ukončiť\'',
	accuracy: 'Presnosť',

	newappversion:  "Nová verzia",
	later:  "Neskôr",
	upgrade:  "Aktualizácia",
	uptodate:  "Aktuálna",
	checkingupdate:  "Kontrolujeme aktualizácie...",

	disconnectedtips: 'Pripájame sa na server, prosím čakajte...',
	uploadfailed: 'Poslať súbor',
	lightbulb: 'Žiarovka - svetlo',
	invalid: 'Neplatný',
	phonelistisfull: 'Zoznam telefónnych čísel je plný',
	serverinternalerror: 'Interná chyba servera',
	addwatchtimeout: 'Pridať časový limit sledovania',
	deletewatchtimeout: 'Vymazať časový limit sledovania',
	registertimeout: 'Časový limit registrácie',
	registerfailed: 'Registrácia zlyhala',
	failed: 'chyba',
	timeout: 'čas vypršal',
	activedevice: 'Hodinky pripojené',
	familynumbernotfound: 'telefónne číslo nenájdené',
	updating: 'Aktualizuje sa...',

	disablewifilocation: 'Zakázať WiFi lokalizáciu',
	locatenowtips: 'Stlačením tlačidla aktualizujete polohu používateľa. To bude vyžadovať poslanie SMS do hodiniek.',
	confirmsendsmstoactive: 'Hodinky sa dočasne odpojili od servera. Pošlite SMS, aby ste spustili okamžité hlásenie polohy',
	inputfencename: 'Zadajte názov bezpečnej zóny',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
    commonsecret: 'The password is the same, please retype',
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Priatelia dieťaťa",
	Nameoflocator:"Názov lokátora",
	LocatorNumber:"Číslo lokátora",
    
    DeviceCode:"Verzia zariadenia",
	DeviceName: "názov zariadenia",
    SpeedAlarm: "Urýchlenie alarmu",
    ActivePositioningMode: "Režim aktívneho určovania polohy",
    DeviceNotFeature: "Zariadenie túto funkciu nepodporuje",
    RebootDevice: "Reštart zariadenia",
    ResetDevice: "Obnoviť pôvodné nastavenia",
    timeInterval: "interval",
	IncludingPositioning:'obsahuje Mobilná BTS',
	Whether:'Či už existuje',
	Obtain:"obdržať",
	Device:"zariadenie",
	Transmission:"Bol odoslaný na adresu",
	PasswordRese:"Zlyhalo resetovanie hesla. Prosím skúste znova",
	GatorUseName:"",
    NameWatchShown:"Názov zobrazený na hodinkách",
    successfulActivation:"úspešne",
	activationFailed: "neúspešne",
	antiTheft:"funkcia proti krádeži",
}