//泰语

module.exports = {
	exitconfirm: "ยืนยันทางออก",
	noexitconfirm: "แจ้งเตือนเคยชินอีกครั้ง",
	login: "เข้าสู่ระบบ",
	loginph: "อีเมล์",
	regemail: "อีเมล์ที่ใช้ในการเข้าสู่ระบบและการตั้งค่ารหัสผ่านของคุณ",
	pwdph: "รหัสผ่าน",
	forgotpwd: "ลืมรหัสผ่าน?",
	reset: "รีเซ็ตรหัสผ่าน",
	resetbtn: "ตั้งใหม่",
	resetemail: "อีเมล์ที่ลงทะเบียนไว้",
	pwdreset: "รหัสผ่านใหม่ของคุณถูกส่งไปยัง",
	register: "ลงทะเบียนผู้ใช้ใหม่",
	registerbtn: "สมัครสมาชิก",
	invaliduser: "ชื่อผู้ใช้และรหัสผ่านที่ไม่ถูกต้อง",
	locate: "บ้าน",
	options: "การตั้งค่า",
	delete: "ลบ",
	logout: "ออกจากระบบ",
	isempty: " ไม่สามารถที่ว่างเปล่า",
	taken: " ได้รับการจดทะเบียนโปรดลองอีก",
	invalidusername: "อีเมล์ของคุณไม่ถูกต้อง",
	failed: "บางสิ่งบางอย่างที่ไม่ถูกต้องโปรดลองอีกครั้ง",
	success: "ความสำเร็จ",
	alarm: "ปลุก",
	alarmtitle: "ปลุกข้อความ",
	navigate: "นำทาง",
	startnav: "เริ่มต้นนำทาง",
	sos: "เปิดใช้งานโหมด SOS",
	startmonitor: "เปิดใช้งานการตรวจสอบเสียง",
	locatenow: "ค้นหาตอนนี้",
	confirmlocatesms: "เราจำเป็นต้องส่งข้อความไปดูจะได้รับตำแหน่งใหม่ล่าสุดยืนยันที่จะส่ง?",
	sms: "ส่งข้อความ",
	history: "ประวัติสถานที่",
	mylocation: "ตำแหน่งของฉัน",
	kidlocation: "เด็กที่อยู่",
	startpoint: "จุดเริ่ม",
	endpoint: "ปลายทาง",
	addwatch: "เพิ่มอุปกรณ์",
	add: "เพิ่ม",
	markasread: "ทำเครื่องหมายว่าอ่านแล้ว",
	morephonenumbers: "หมายเลขโทรศัพท์",
	recivesmsalert: "ประกาศแจ้งเตือน",
	setupfence: "SafeZone",
	setupfence1: "บ้าน",
	setupfence2: "โรงเรียน",
	modifypwd: "ปรับเปลี่ยนรหัสผ่าน",
	feedback: "ข้อเสนอแนะ",
	about: "เกี่ยวกับ",
	back: "กลับ",
	imei: "IMEI",
	ownername: "ชื่อเด็ก",
	petname:"ชื่อสัตว์เลี้ยง",
	simid: "โทรศัพท์อุปกรณ์",
	simcountrycode:  "Country Code",
	soscountrycode:  "Country Code",
	phonenumbers: "SOS หมายเลขโทรศัพท์",
	locateinterval: "ช่วงเวลาของการเดินทางของตำแหน่งเด็ก (M)",
	avatartxt: "สัญลักษณ์",
	historyalarm: "ปลุกประวัติศาสตร์",
	save: "บันทึก",
	oldpwd: "รหัสผ่านเก่า",
	newpwd: "รหัสผ่านใหม่",
	submit: "เสนอ",
	invalidimei: "หมายเลข IMEI ไม่ถูกต้อง",
	dupaddwatch: "คุณได้เพิ่มนาฬิกาเรือนนี้",
	confirmremovedevice: "คุณแน่ใจหรือว่าต้องการที่จะเอานาฬิกาเรือนนี้? คุณจะไม่ได้รับข้อความใด ๆ จากนาฬิกาเรือนนี้",
	cancel: "ยกเลิก",
	from: "เลือกแหล่งที่มาของภาพ",
	fromlib: "ภาพห้องสมุด",
	fromcamera: "จับภาพ",
	invalidoldpwd: "รหัสผ่านเก่าไม่ถูกต้อง",
	undefined: "ไม่ได้กำหนด",
	fencename: "ชื่อ",
	radius: "รัศมี",
	meter: "ม.",
	centerpoint: "จุดศูนย์",
	send: "ส่ง",
	to: "ไปยัง",
	text: "ข้อความ",
	sms2send: "คุณจำเป็นต้องส่งข้อความไปยังนาฬิกาของคุณ:",
	cancelsend: "ตกลงฉันจะส่งได้ในภายหลัง",
	alarmemail: "อีเมล์ปลุก",
	viewinmap: "ดูในแผนที่",
	exitnav: "ออกจากการเดินเรือ",
	loadingtext: "โหลด",
	locatefailed: "ไม่สามารถหาโทรศัพท์ที่กรุณาเปิดใช้งานได้ในการตั้งค่าแอพพลิเค",
	alarm1: "ใส่โซนปลอดภัย",
	alarm4: "ออกจากโซนปลอดภัย",
	alarm2: "เตือนภัยฉุกเฉิน",
	alarm8: "ปลุกแบตเตอรี่ต่ำ",
	alarm32: 'Watch detached',
	alarm64: 'ปลุกความเร็ว',
	noalarm: "ไม่มีการเตือนภัยที่ยังไม่ได้อ่านเลย",
	time: "เวลา",
	address: "ที่อยู่",
	search: "ค้นหา",
	nodata: "ไม่มีข้อมูล",
	sosnumbers: "เบอร์โทรฉุกเฉิน",
	whitelistnumbers: "Whitelist สามารถเรียกดู",
	deldevice: "ลบอุปกรณ์นี้",
	editprofile: "คลิกเพื่อแก้ไขข้อมูลส่วนตัว",
	phonenumbers: "หมายเลขโทรศัพท์",
	batterymode: "โหมดค้นหา",
	emergencymode: "เซฟโหมด: ค้นหาใน 5 นาที",
	savingmode: "โหมดประหยัดแบตเตอรี่: ค้นหาในเวลา 10 นาที",
	systemsetting: "การตั้งค่าระบบ",
	youradvice: "คำแนะนำใด ๆ บ่น ...",
	timezone: "เขตเวลา",
	notificationtitle: "นาฬิกาปลุก Gator",
	lastestlocation: "ค้นหาล่าสุด",
	device_lang:  "Watch Language",
	volume:  "Watch Volume",
	usedst:  "Daylight saving time",
	socketmodeoff:  "Power saving mode",
	childpoweroff: "เด็กสามารถปิด",
	retrieving: "เรียก ...",
	smsbyapp: "การกระทำบางอย่างจำเป็นต้องส่งคำสั่งข้อความสั้นที่จะดูจากโทรศัพท์ของคุณนี้อาจสร้างค่าการสื่อสาร",
	days2exipre: " วัน (s) ที่หมดอายุ",
	exipred: "นาฬิกาเรือนนี้ได้หมดอายุแล้ว",
	monthmsgremain: "ข้อความที่สามารถส่งในเดือนนี้",
	isadding: " เพิ่มเป็นนาฬิกาเรือนนี้โปรดลองใหม่ภายหลัง",
	alertsms: "ส่ง SMS เมื่อปลุก",
	verifycodemsg: "คุณควรจะขอให้ผู้ใช้ {}, สำหรับตรวจสอบรหัส เขา / เธอสามารถเปิด app-> ตั้งค่า -> [นาฬิกา] -> ตรวจสอบรหัส",
	verifycode: "ตรวจสอบรหัส",
	verifycodetip: "ตรวจสอบรหัสที่ใช้ในการตรวจสอบผู้ใช้เพิ่มนาฬิกานี้โปรดให้รหัสนี้เฉพาะเมื่อผู้ใช้ที่ระบุ",
	version: "รุ่น",
	ok: "ตกลง",
	done: "เสร็จสิ้น",
	cancel: "ยกเลิก",
	msgcancelled: "ข้อความยกเลิก",
	confirmpassword: "ยืนยันรหัสผ่าน",
	confirmpasswordnotequal: "ยืนยันรหัสผ่านควรจะเป็นเช่นเดียวกับรหัสผ่าน",
	gps: "จีพีเอส",
	tower: "สถานีฐาน",
	wifi: "Wifi",
	phonetype0: "คนอื่น ๆ",
	phonetype1: "พ่อ",
	phonetype2: "แม่",
	phonetype3: "ยาย",
	phonetype4: "คุณปู่",
	phonetype5: 'เพื่อนร่วมชั้น',
	phonetype: "ประเภท",
	name: "ชื่อ",
	reenter: "กรุณาใส่ใหม่",
	minichat: "เสียง",
	sendvoice: "ค้างไว้และพูด",
	pulltorefresh: "ดึงเพื่อฟื้นฟู",
	me: "ผม",
	unread: "ไม่ได้อ่าน",
	holdtip: "ค้างไว้และพูดความยาวสูงสุด 10 วินาที",
	voicetoolarge: "เสียงเกิน 10 วินาทีโปรดบันทึกอีกครั้ง",
	novoice: "เสียงยังไม่มี",
	sending: "กำลังส่ง ...",
	recording: "recoding ... {time}  เวลาวินาที (s)",
	preparing: "เตรียมพร้อม...",
	watchalarm: "สัญญาณเตือนภัย",
	watchalarmdetail: "การตั้งปลุก",
	morning: "AM",
	afternoon: "PM",
	today: "วันนี้",
	everyday: "ทุกวัน",
	repeat: "ทำซ้ำ",
	day0: "อาทิตย์",
	day1: "จันทร์",
	day2: "อังคาร",
	day3: "พุธ",
	day4: "พฤหัสบดี",
	day5: "ศุกร์",
	day6: "เสาร์",
	alarm16: "เสียงใหม่",
	confirmdeletealarm: "ยืนยันการลบเตือนภัยนี้",
	noalarms: "การเตือนภัยที่ยังไม่มีคลิกเพื่อเพิ่ม",
	smart: "ฉลาด",
	starttime: "เวลาเริ่มต้น",
	endtime: "เวลาสิ้นสุด",
	contain: "ประกอบด้วย",
	mynumber: "เบอร์โทรศัพท์ของฉัน",
	appqrcode: "App QR Code",
	dialbackno: "หมายเลขโทรศัพท์เพื่อโทรกลับ",

	moreadvancedsetting:  "Advanced Settings",
	hideself:  "Airplane Mode",
	hideselfdetail:  "Airplane Mode Settings",
	hideselfbegin:  "Start time:",
	hideselfend:  "End time:",
	nohidetimers: "Add Airplane Mode Settings",
	invalidendtime: "End time need greater than start time",
	enable: "Open",
	twotimerconflict: "Clash with following times：",

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',
	
	newappversion:  "New version",
	later:  "Later",
	upgrade:  "Upgrade",
	uptodate:  "Up to date",
	checkingupdate:  "Checking update...",

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',

	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	commonsecret: 'The password is the same, please retype',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"เพื่อนของเด็ก",
	Nameoflocator:"ชื่อ locator",
	LocatorNumber:"หมายเลข Locator",
	
    DeviceCode:"เวอร์ชันอุปกรณ์",
	DeviceName: "ชื่ออุปกรณ์",
    SpeedAlarm: "ปลุกความเร็ว",
    ActivePositioningMode: "โหมดตำแหน่งที่ใช้งานอยู่",
    DeviceNotFeature: "อุปกรณ์ไม่สนับสนุนคุณลักษณะนี้",
    RebootDevice: "รีสตาร์ทอุปกรณ์",
    ResetDevice: "เรียกคืนการตั้งค่าโรงงาน",
    timeInterval: "ระยะห่าง",
    IncludingPositioning:'ประกอบด้วย สถานีฐาน', 
	Whether:'ไม่ว่าจะมี',
	Obtain:"ได้รับ",
	Device:"เครื่อง",
	Transmission:"ได้ถูกส่งไปที่",
	PasswordRese:"การรีเซ็ตรหัสผ่านล้มเหลว กรุณาลองอีกครั้ง",
	GatorUseName:"",
    NameWatchShown:"ชื่อที่แสดงบนนาฬิกา",
    successfulActivation:"ตั้งค่าเรียบร้อยแล้ว",
	activationFailed: "tậng kh̀ā mị̀ s̄ảrĕc",
  antiTheft:"ฟังก์ชั่นป้องกันการโจรกรรม",
  
  systolic :'ความดันโลหิตซิสโตลิก',
diastolic:'ความดันโลหิต Diastolic',
power:'อำนาจ',
pulseRate:'อัตราชีพจร',
oxygenSaturation:'ความอิ่มตัวของออกซิเจนในเลือด',
WeakPerfusion:'ดัชนีการกระจายที่อ่อนแอ',
temperature:'อุณหภูมิร่างกาย',
healthSettings:'การตั้งค่าสุขภาพ',
thermometer:'เครื่องวัดอุณหภูมิ',
oximeter:'oximeter',
sphygmomanometer:'sphygmomanometer',
son:'บุตรชาย',
daughter:'ลูกสาว',
spouse:'สามีและภรรยา',
ordinaryAlarm:'สัญญาณเตือนสามัญ',
takeMedicine:'กินยา',
drinkWater:'ดื่มน้ำ',
sedentaryReminder:'เตือนความจำประจำ',
testReminder:'เตือนการทดสอบ',
}