//菲律宾

module.exports = {
	exitconfirm: "Kumpirmahin ang exit",
	noexitconfirm: "Muli sanay alert",
	login: "Login",
	loginph: "Email",
	regemail: "Email ginagamit upang mag-login at i-reset ang iyong password",
	pwdph: "Password",
	forgotpwd: "Nakalimutan ang password?",
	reset: "I-reset ang password",
	resetbtn: "I-reset ang",
	resetemail: "Ang iyong nakarehistrong email address",
	pwdreset: "Ang iyong bagong password ay ipapadala sa",
	register: "Magrehistro bagong user",
	registerbtn: "Magrehistro",
	invaliduser: "Maling username at password",
	locate: "Tahanan",
	options: "Mga Setting",
	delete: "Alisin",
	logout: "Logout",
	isempty: " maaaring hindi na walang laman",
	taken: " ay nakarehistro, mangyaring subukan ang iba",
	invalidusername: "Ang iyong email ay hindi wasto",
	failed: "May mali, mangyaring subukan muli",
	success: "tagumpay",
	alarm: "Alarma",
	alarmtitle: "Messages Alarm",
	navigate: "Mag-navigate",
	startnav: "Start-navigate",
	sos: "Buhayin SOS mode",
	startmonitor: "Buhayin Voice Monitor",
	locatenow: "Hanapin Now",
	confirmlocatesms: "Kailangan namin upang magpadala ng mga text na panoorin upang makakuha ng pinakabagong lokasyon, kumpirmahin magpadala?",
	sms: "Magpadala ng SMS",
	history: "Kasaysayan ng Lokasyon",
	mylocation: "Aking Lokasyon",
	kidlocation: "Kids Lokasyon",
	startpoint: "Simula Point",
	endpoint: "Destinasyon",
	addwatch: "Magdagdag ng device",
	add: "Magdagdag",
	markasread: "Markahan Bilang Magbasa",
	morephonenumbers: "Mga Numero ng Telepono",
	recivesmsalert: "Notification Alert",
	setupfence: "Safezone",
	setupfence1: "Tahanan",
	setupfence2: "Paaralan",
	modifypwd: "Baguhin ang Password",
	feedback: "Feedback",
	about: "Tungkol sa",
	back: "Likod",
	imei: "IMEI",
	ownername: "Pangalan ng Bata",
	petname:"pangalan ng alaga",
	simid: "Telepono ng device",
	simcountrycode:  "Country Code",
	soscountrycode:  "Country Code",
	phonenumbers: "SOS Mga Numero ng Telepono",
	locateinterval: "Time Palugit ng Pagkuha Kid Position (M)",
	avatartxt: "Awatara",
	historyalarm: "Alarm History",
	save: "I-save ang",
	oldpwd: "Lumang Password",
	newpwd: "Bagong Password",
	submit: "Ibigay",
	invalidimei: "Di-wastong Numero ng IMEI",
	dupaddwatch: "Ikaw ay idinagdag relos na ito",
	confirmremovedevice: "Sigurado ka bang gusto mong alisin ang relos na ito? Hindi ka makakatanggap ng anumang mga mensahe mula relos na ito.",
	cancel: "Kanselahin",
	from: "Piliin Source Photo",
	fromlib: "Photo Library",
	fromcamera: "Huminga ng Litrato",
	invalidoldpwd: "Lumang Password ay hindi tama.",
	undefined: "Hindi naipalilawanag",
	fencename: "Pangalan",
	radius: "Radius",
	meter: "m",
	centerpoint: "Center Point",
	send: "Magpadala",
	to: "Sa",
	text: "Teksto",
	sms2send: "Kailangan mong magpadala ng isang text sa iyong mga relo:",
	cancelsend: "OK, ako ay magpadala ng mga ito mamaya",
	alarmemail: "Alarm Email",
	viewinmap: "Tingnan sa Mapa",
	exitnav: "Exit Navigation",
	loadingtext: "pagkarga",
	locatefailed: "Hindi mahanap ang telepono, Mangyaring paganahin ito sa mga setting ng app",
	alarm1: "Ipasok Safe Zone",
	alarm4: "Sa labas ng Safe Zone",
	alarm2: "Emergency Alarm",
	alarm8: "Mababang baterya alarma",
	alarm32: 'Watch detached',
	alarm64: 'Bilis ng alarma',
	noalarm: "Wala pang mga hindi pa nababasang mga alarma",
	time: "Oras",
	address: "Tirahan",
	search: "Paghahanap",
	nodata: "Walang Data",
	sosnumbers: "Numero Emergency Call",
	whitelistnumbers: "Whitelist ay maaaring tumawag relos",
	deldevice: "Tanggalin ang aparatong ito",
	editprofile: "I-click Upang I-edit ang Profile",
	phonenumbers: "Mga Numero ng Telepono",
	batterymode: "Hanapin Mode",
	emergencymode: "Safe Mode: Hanapin sa 5 minuto",
	savingmode: "Tagal Saving Mode: Hanapin sa loob ng 10 minuto",
	systemsetting: "Setting ng System",
	youradvice: "anumang mga payo, anumang magreklamo ...",
	timezone: "Timezone",
	notificationtitle: "Gator Watch Alarm",
	lastestlocation: "Pinakabagong Hanapin",
	device_lang:  "Watch Language",
	volume:  "Watch Volume",
	usedst:  "Daylight saving time",
	socketmodeoff:  "Power saving mode",
	childpoweroff: "Child Maaari Power Off",
	retrieving: "Binabawi ...",
	smsbyapp: "Ang ilang mga aksyon na kailangan upang magpadala ng maiikling text command upang panoorin sa pamamagitan ng iyong telepono, ito ay maaaring makabuo ng mga fee sa komunikasyon.",
	days2exipre: " (s) sa araw-expired",
	exipred: "Relos na ito ay napaso na",
	monthmsgremain: "Ang mga mensahe ay maaaring magpadala ng buwan na ito",
	isadding: " ay pagdaragdag ng relos na ito, mangyaring subukan mamaya",
	alertsms: "Magpadala ng SMS kapag Alarm",
	verifycodemsg: "Dapat mong tanungin ang user {}, para mapatunayan code. siya / siya ay maaaring buksan ang app-> Setting -> [Watch] -> I-verify ang Code",
	verifycode: "Patunayan ang Code",
	verifycodetip: "Patunayan ang Code na ginagamit upang i-verify ang user na idagdag ang relos na ito, mangyaring mag-alok ang code na ito lamang kapag kinilala user.",
	version: "bersyon",
	ok: "OK",
	done: "Tapos",
	cancel: "kanselahin",
	msgcancelled: "kinansela ng Mensahe",
	confirmpassword: "kumpirmahin ang Password",
	confirmpasswordnotequal: "Kumpirmahin ang Password parehong dapat bilang Password",
	gps: "GPS",
	tower: "base Station",
	wifi: "wifi",
	phonetype0: "Iba",
	phonetype1: "Ama",
	phonetype2: "Ina",
	phonetype3: "Lola",
	phonetype4: "Lolo",
	phonetype5: 'Classmate',
	phonetype: "Uri",
	name: "pangalan",
	reenter: "Mangyaring ipasok muli ang",
	minichat: "Tinig",
	sendvoice: "Pindutin ng matagal at ang Magsalita",
	pulltorefresh: "Hilahin upang i-refresh",
	me: "sa akin",
	unread: "hindi pa nababasa",
	holdtip: "Pindutin ng matagal at ang Magsalita, max na haba ng 10 segundo",
	voicetoolarge: "Lumampas Voice 10 segundo, paki-record muli",
	novoice: "Wala pang mga tinig",
	sending: "Nagpapadala ...",
	recording: "Recoding ... {time}  segundo (s)",
	preparing: "Maghanda...",
	watchalarm: "Alarm",
	watchalarmdetail: "Setting Alarm",
	morning: "AM",
	afternoon: "PM",
	today: "sa araw na ito",
	everyday: "Araw-araw",
	repeat: "Ulitin",
	day0: "Sun",
	day1: "Mon",
	day2: "Tue",
	day3: "Wed",
	day4: "Huwebes",
	day5: "Biyernes",
	day6: "Sat",
	alarm16: "New Voice",
	confirmdeletealarm: "Kumpirmahin tanggalin alarm na ito",
	noalarms: "Walang mga alarma pa, i-click upang magdagdag ng",
	smart: "Smart",
	starttime: "Oras ng Simula",
	endtime: "Katapusan ng oras",
	contain: "naglalaman",
	mynumber: "Ang numero ng aking telepono",
	appqrcode: "QR Code App",
	dialbackno: "Ang numero ng telepono upang i-dial muli",
	moreadvancedsetting:  "Advanced Settings",
	hideself:  "Airplane Mode",
	hideselfdetail:  "Airplane Mode Settings",
	hideselfbegin:  "Start time:",
	hideselfend:  "End time:",
	nohidetimers: "Add Airplane Mode Settings",
	invalidendtime: "End time need greater than start time",
	enable: "Open",
	twotimerconflict: "Clash with following times：",

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  "New version",
	later:  "Later",
	upgrade:  "Upgrade",
	uptodate:  "Up to date",
	checkingupdate:  "Checking update...",

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',

	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	commonsecret: 'The password is the same, please retype',
	passworderror:'password error!',
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Mga kaibigan ng bata",
	Nameoflocator:"Pangalan ng tagahanap",
	LocatorNumber:"Numero ng tagahanap",
	
    DeviceCode:"Bersyon ng device",
	DeviceName: "pangalan ng device",
    SpeedAlarm: "Speeding Alarm",
    ActivePositioningMode: "Active Positioning Mode",
    DeviceNotFeature: "Hindi sinusuportahan ng aparato ang tampok na ito",
    RebootDevice: "I-restart ang device",
    ResetDevice: "Ibalik ang mga setting ng pabrika",
    timeInterval: "agwat",
    IncludingPositioning:'naglalaman base Station',
	Whether:'Kung mayroon man',
	Obtain:"Makuha",
	Device:"aparato",
	Transmission:"Naipadala sa",
	PasswordRese:"Nabigo ang pag-reset ng password. Ulitin mo ulit",
	GatorUseName:"",
    NameWatchShown:"Pangalan na ipinapakita sa panonood",
    successfulActivation:"set up matagumpay",
	activationFailed: "mag-set up ng hindi matagumpay",
  antiTheft:"function na anti-pagnanakaw",
  
systolic :'Ang presyon ng dugo ng systolic',
diastolic:'Diastolic pressure sa dugo',
power:'Kapangyarihan',
pulseRate:'Rate ng pulso',
oxygenSaturation:'Saturation ng oxygen sa dugo',
WeakPerfusion:'Mahina na Perfusion Index',
temperature:'Temperatura ng katawan',
healthSettings:'Mga setting ng kalusugan',
thermometer:'Thermometer',
oximeter:'Oximeter',
sphygmomanometer:'Sphygmomanometer',
son:'Anak',
daughter:'Anak na babae',
spouse:'Asawa at asawa',
ordinaryAlarm:'Ordinaryong alarma',
takeMedicine:'Uminom ng gamot',
drinkWater:'Uminom ng tubig',
sedentaryReminder:'Sedentary na paalala',
testReminder:'Paalala sa pagsubok',
}