//土耳其

module.exports = {
	exitconfirm: "Uygulamayı kapatmak istiyor musunuz",
	noexitconfirm: "Uyarıyı tekrar gösterme",
	login: "Oturum Aç",
	loginph: "E-posta",
	regemail: "E-posta adresinizi yazınız",
	pwdph: "Parola",
	forgotpwd: "Şifre sıfırlama",
	reset: "Şifre sıfırlama",
	resetbtn: "Sıfırla",
	resetemail: "Kayıtlı E-posta",
	pwdreset: "Yeni şifreniz gönderildi",
	register: "Yeni kullanıcı kaydı",
	registerbtn: "Kayıt",
	invaliduser: "Hatalı kullanıcı adı ve şifre",
	locate: "Harita",
	options: "Ayarlar",
	delete: "Sil",
	logout: "Çıkış Yap",
	isempty: " Boş bırakılamaz",
	taken: " başka bir kullanıcı tarafından kullanılıyor, farklı bir e-posta kullanınız.",
	invalidusername: "E-posta geçersiz",
	failed: "Sorun oluştu, lütfen tekrar deneyin",
	success: "Başarılı",
	alarm: "Alarm",
	alarmtitle: "Alarm Mesajları",
	navigate: "Gezinme",
	startnav: "Başlangıça ​​gidin",
	sos: "SOS modunu etkinleştirin",
	startmonitor: "Ses izleme etkinleştirin",
	locatenow: "Şimdi bulun",
	confirmlocatesms: "Yeni konum için SMS göndermek gerekiyor, onaylıyor musunuz?",
	sms: "SMS gönder",
	history: "Konum Geçmişi",
	mylocation: "Benim Yerim",
	kidlocation: "Çocuğun Yeri",
	startpoint: "Başlangıç ​​Noktası",
	endpoint: "Hedef",
	addwatch: "Cihaz ekle",
	add: "Ekle",
	markasread: "Okundu olarak işaretle",
	morephonenumbers: "Telefon Numaraları",
	recivesmsalert: "Uyarıları Bildir",
	setupfence: "Güvenli Bölge",
	setupfence1: "Ev",
	setupfence2: "Okul",
	modifypwd: "Şifre Değiştirme",
	feedback: "Bize Yazın",
	about: "Hakkımda",
	back: "Geri",
	imei: "IMEI",
	ownername: "Çocuk Adı",
	petname:"Evcil hayvanın adı",
	simid: "Cihaz telefonu",
	simcountrycode:  "Country Code",
	soscountrycode:  "Country Code",
	phonenumbers: "Acil Durum telefon numaraları",
	locateinterval: "Çocuk pozisyonu alınıyor Zaman Aralığı (M)",
	avatartxt: "Profil Resmi",
	historyalarm: "Eski Alarmlar",
	save: "Kaydet",
	oldpwd: "Eski Şifre",
	newpwd: "Yeni Şifre",
	submit: "Gönder",
	invalidimei: "Geçersiz IMEI Numarası",
	dupaddwatch: "Bu saati başarıyla eklediniz",
	confirmremovedevice: "Bu saati kaldırmak istediğinizden emin misiniz? Bu saati kaldırırsanız bundan sonra mesaj almayacaksınız. ",
	cancel: "İptal",
	from: "Fotoğraf Kaynağını Seç",
	fromlib: "Fotoğraf Galerisi",
	fromcamera: "Fotoğraf Çek",
	invalidoldpwd: "Eski Şifre hatalıdır.",
	undefined: "Tanımlanmamış",
	fencename: "İsim",
	radius: "Yarıçap",
	meter: "m",
	centerpoint: "Orta Nokta",
	send: "Gönder",
	to: "to",
	text: "Metin",
	sms2send: "İzlemek için SMS göndermen gerekmektedir:",
	cancelsend: "Tamam, daha sonra göndereceğim",
	alarmemail: "E-mail Alarmlar",
	viewinmap: "Harita Görünümü",
	exitnav: "Çıkış Navigasyon",
	loadingtext: "Yükleniyor",
	locatefailed: "Telefonun konumu bulunamıyor, lütfen uygulamalardan konum servisini çalıştırın",
	alarm1: "Güvenli Bölge Girişi",
	alarm4: "Güvenli Bölge Çıkışı",
	alarm2: "Acil Durum Alarmı",
	alarm8: "Düşük Pil Uyarısı",
	alarm32: 'Watch detached',
	alarm64: 'Hız alarmı',
	noalarm: "Yeni Alarm Yok",
	time: "Zaman",
	address: "Adres",
	search: "Arama",
	nodata: "Veri Yok",
	sosnumbers: "Acil Çağrı Numaraları",
	whitelistnumbers: "Arama için izin verilen numaralar",
	deldevice: "Bu cihazı sil",
	editprofile: "Profili Düzenlemek için tıklayın",
	phonenumbers: "Telefon Numaraları",
	batterymode: "Mod bulun",
	emergencymode: "Güvenli Mod: 5 dakika içinde bulun",
	savingmode: "Pil Tasarruf Modu: 10 dakika içinde bulun",
	systemsetting: "Sistem Ayarları",
	youradvice: "Görüş veya şikayetlerinizi buraya yazabilirsiniz.",
	timezone: "Saat Dilimi",
	notificationtitle: "Gator Saat Alarmı",
	lastestlocation: "Son Konum",
	device_lang:  "Watch Language",
	volume:  "Watch Volume",
	usedst:  "Yaz Saati Uygulaması Kullanılıyor",
	socketmodeoff:  "Güç Tasarrufu Modunu Aç",
	childpoweroff: "Çocuğun saati kapatmasına izin ver",
	retrieving: "Alınıyor ...",
	smsbyapp: "Uygulamayı kullanabilmek için internet bağlantınızın olması gerekmektedir. Bazı durumlarda sms göndermeniz gerekebilir.",
	days2exipre: " gün sonra aboneliğiniz dolacak",
	exipred: "Abonelik süreniz dolmuştur",
	monthmsgremain: "Mesajları bu ay gönderebilirsiniz",
	isadding: " bu saati ekleyerek olduğunu lütfen daha sonra tekrar deneyiniz.",
	alertsms: "Sos tuşuna basıldığında SMS gönder",
	verifycodemsg: "Bu saati ekleme için {}, kullanıcısından doğrulama kodunu öğrenmelisiniz.",
	verifycode: "Doğrulama Kodu",
	verifycodetip: "Diğer kullanıcıların bu saati izlemesi için bu doğrulama kodunu kullanabilirsiniz.",
	version: "Sürüm",
	ok: "Tamam",
	done: "Bitti",
	cancel: "İptal",
	msgcancelled: "Mesaj İptal Edildi",
	confirmpassword: "Şifreyi Onayla",
	confirmpasswordnotequal: "Parolalar eşleşmedi, lütfen yeniden deneyiniz.",
	gps: "GPS",
	tower: "Baz İstasyonu",
	wifi: "Wi-Fi",
	phonetype0: "Diğer",
	phonetype1: "Baba",
	phonetype2: "Anne",
	phonetype3: "Nine",
	phonetype4: "Dede",
	phonetype5: 'sınıf arkadaşı',
	phonetype: "Yakınlık",
	name: "İsim",
	reenter: "Lütfen tekrar giriniz",
	minichat: "Sesli Mesaj",
	sendvoice: "Tutun ve konuşun",
	pulltorefresh: "Yenilemek için çekin",
	me: "Bana",
	unread: "Okunmamış",
	holdtip: ", Tutun ve konuşun, maksimum 10 saniye iletebilirsiniz.",
	voicetoolarge: "Sesli mesaj 10 saniyeyi aştı, yeniden deneyiniz.",
	novoice: "Henüz mesaj yok",
	sending: "Gönderiliyor ...",
	recording: "Kayıt yapılıyor ... {time}  saniye (s)",
	preparing: "Hazırlanıyor...",
	watchalarm: "Alarm",
	watchalarmdetail: "Alarm Ayarı",
	morning: "AM",
	afternoon: "PM",
	today: "Bugün",
	everyday: "Her gün",
	repeat: "Tekrarlama",
	day0: "Pazar",
	day1: "Pazartesi",
	day2: "Salı",
	day3: "Çarşamba",
	day4: "Perşembe",
	day5: "Cuma",
	day6: "Cumartesi",
	alarm16: "Yeni Ses",
	confirmdeletealarm: "Bu alarmı silmek için onaylayınız",
	noalarms: "Henüz hiç alarm yok, ayarlamak için tıklayınız.",
	smart: "Akıllı",
	starttime: "Başlama zamanı",
	endtime: "Bitiş zamanı",
	contain: "İçeriyor",
	mynumber: "Telefon numaram",
	appqrcode: "App QR Kodu",
	dialbackno: "Telefon numaranızı giriniz",
	notsupported:  "Saat sesli iletişimi desteklemiyor",
	moreadvancedsetting:  "Advanced Settings",
	hideself:  "Airplane Mode",
	hideselfdetail:  "Airplane Mode Settings",
	hideselfbegin:  "Start time:",
	hideselfend:  "End time:",
	nohidetimers: "Add Airplane Mode Settings",
	invalidendtime: "End time need greater than start time",
	enable: "Open",
	twotimerconflict: "Clash with following times：",

	homewifisetting: 'Zone WiFi Settings',
	homewificomments: 'Please select the WiFi access point used in your safe zone. If the WiFi is not shown in the list below, please click \'Cancel\'',
	accuracy: 'Accuracy',

	newappversion:  "New version",
	later:  "Later",
	upgrade:  "Upgrade",
	uptodate:  "Up to date",
	checkingupdate:  "Checking update...",

	disconnectedtips:  'Connecting to server, please wait...',
	uploadfailed: 'Upload failed',
	lightbulb: 'Light bulb',
	invalid: 'Invalid',
	phonelistisfull: 'The phone number list is full',
	serverinternalerror: 'Server internal error',
	addwatchtimeout: 'Add watch timeout',
	deletewatchtimeout: 'Delete watch timeout',
	registertimeout: 'Register timeout',
	registerfailed: 'Register failed',
	failed: 'failed',
	timeout: 'timeout',
	activedevice: 'connect watch',
	familynumbernotfound: 'phone number not found',
	updating: 'Updating...',

	disablewifilocation: 'Disable WiFi location',
	locatenowtips: 'Press to update the location of the user. This will require you to send an SMS to the watch.',
	confirmsendsmstoactive: 'Watch has temporarily disconnected from the server. Send an SMS to trigger it to report location immediately',
	inputfencename: 'Enter Safezone Name',
    
    Pleaseconfirm:"Please confirm",
	agreeprivacypolicy: 'You hereby agree to ',
	privacypolicytitle: 'Privacy Policy',
   
	passwordruletips: 'Password needs to be at least 8 characters and must include one digit, one lower case letter and one upper case letter ',
	commonsecret: 'The password is the same, please retype',
	passworderror:'password error!', 
	passworderror5:'Account locked as password incorrect. Please wait 1 minutes and try again.',

	addAccount:'Add administrator permissions',
	notAccount:'No authority!',
	overlimitNumber: 'Add number overlimit',

	friends:"Çocuğun arkadaşları",
	Nameoflocator:"Yerleştiricinin adı",
	LocatorNumber:"Bulucu numarası",
	DeviceCode:"Cihaz sürümü",
	DeviceName: "cihaz adı",
    SpeedAlarm: "Hız Alarmı",
    ActivePositioningMode: "Aktif Konumlandırma Modu",
    DeviceNotFeature: "Cihaz bu özelliği desteklemiyor",
    RebootDevice: "Cihaz yeniden başlat",
    ResetDevice: "Fabrika ayarlarını geri yükle",
    timeInterval: "aralık",
    IncludingPositioning:'İçeriyor Baz İstasyonu',
	Whether:'Var yada',
	Obtain:"elde etmek",
	Device:"cihaz",
	Transmission:"Gönderildi",
	PasswordRese:"Parola sıfırlama başarısız oldu. Lütfen tekrar deneyin",
	GatorUseName:"",
    NameWatchShown:"Saatte gösterilen isim",
    successfulActivation:"başarıyla kuruldu",
	activationFailed: "başarısız olarak kuruldu",
	antiTheft:"hırsızlık önleme işlevi"
}