module.exports = {
	exitconfirm: '确认退出',
	noexitconfirm: '不再提示',
	login: '登录',
	loginph: '邮箱帐号',
	regemail: '登录和找回密码的邮箱',
	pwdph: '密码',
	forgotpwd: '忘记密码',
	reset: '密码复位',
	resetbtn: '复位',
	resetemail: '注册使用邮箱',
	pwdreset: '新的密码已经发送至 ',
	register: '新用户注册',
	registerbtn: '注册',
	invaliduser: '用户名密码不匹配',
	locate: '主页',
	options: '设置',
	delete: '删除',
	logout: '注销',
	isempty: '不能为空',
	emailinvalid: ' 邮箱格式不正确',
	loginfailed: ' 登录失败',
	taken: ' 已经被占用',
	invalidusername: '邮箱无效',
	failed: '貌似出了点问题',
	success: '成功',
	alarm: '报警',
	alarmtitle: '报警消息',
	navigate: '导航',
	startnav: '开始导航',
	sos: '激活紧急模式',
	startmonitor: '语音监听',
	locatenow: '立即定位',
	confirmlocatesms: '立即定位需要手机发送一条短信给手表，是否确认?',
	sms: '发送短信',
	history: '历史位置',
	mylocation: '我的位置',
	kidlocation: '小孩位置',
	startpoint: '始发地',
	endpoint: '目的地',
	addwatch: '添加设备',
	add: '添加',
	markasread: '标记为已读',
	morephonenumbers: '电话号码',
	recivesmsalert: '报警通知推送',
	setupfence: '安全区域',
	setupfence1: '家',
	setupfence2: '学校',
	modifypwd: '修改密码',
	feedback: '反馈',
	about: '关于',
	back: '返回',
	imei: 'IMEI',
	ownername: '爱娃姓名',
	petname: "爱宠姓名",
	simid: '设备手机号',
	simcountrycode: '国家代码',
	soscountrycode: '国家代码',
	phonenumbers: '紧急呼叫电话',
	locateinterval: '自动更新位置时间(分钟)',
	avatartxt: '头像',
	historyalarm: '历史报警',
	save: '保存',
	oldpwd: '旧密码',
	newpwd: '新密码',
	submit: '提交',
	invalidimei: 'IMEI号不正确',
	dupaddwatch: '已经添加过该手表',
	confirmremovedevice: '确定移除这个手表?移除手表将收不到任何手表发送的消息',
	cancel: '取消',
	from: '选择照片来源',
	fromlib: '照片库',
	fromcamera: '拍照',
	invalidoldpwd: '原密码不正确.',
	undefined: '未指定',
	fencename: '名称',
	radius: '半径',
	meter: 'm',
	centerpoint: '中心点',
	send: '发送',
	to: '收件人',
	text: '内容',
	sms2send: '需要发送短信给手表:',
	cancelsend: '稍后自行发送',
	alarmemail: '报警邮件',
	viewinmap: '在地图中查看',
	exitnav: '退出导航',
	loadingtext: '正在加载',
	locatefailed: '手机定位失败,请在系统设置中允许app定位',
	alarm1: '进入',
	alarm4: '走出',
	alarm2: '紧急报警',
	alarm8: '电量低',
	alarm32: '手表脱离',
	alarm64: '超速报警',
	noalarm: '没有未读消息',
	time: '时间',
	address: '地址',
	search: '搜索',
	nodata: '没有数据',
	sosnumbers: '按SOS键呼叫号码',
	whitelistnumbers: '白名单(手表可接听的号码)',
	deldevice: '停止关注该设备',
	editprofile: '点击修改信息',
	phonenumbers: '电话簿',
	batterymode: '定位模式',
	emergencymode: '安全模式:5分钟上传一次位置',
	savingmode: '省电模式:10分钟上传一次位置',
	systemsetting: '系统设置',
	youradvice: '各种建议，各种吐槽...',
	timezone: '时区',
	notificationtitle: 'Gator手表告警',
	lastestlocation: '最近定位',
	device_lang: '手表语言',
	volume: '手表音量',
	usedst: '开启夏时令',
	socketmodeoff: '开启省电模式',
	childpoweroff: '爱娃可以关机',
	retrieving: '正在获取...',
	smsbyapp: '某些操作需要发送短信命令给手表方能生效，这将会产生通信费用。',
	days2exipre: ' 天后手表过期',
	exipred: '此手表已经过期',
	monthmsgremain: '本月还可发送短信数量',
	isadding: ' 正在添加该手表，请稍后再试',
	alertsms: '报警发送手机短信',
	verifycodemsg: '需要从用户{},获取验证码并验证. 他/她可以打开app->设置->[手表]->验证码 查看',
	verifycode: '验证码',
	verifycodetip: '验证码用于验证其他用户添加该手表，请确认身份后才能提供验证码',
	version: '版本',
	ok: '确认',
	done: '确认',
	cancel: '取消',
	msgcancelled: '短信发送被取消，设置不会生效',
	confirmpassword: '确认密码',
	confirmpasswordnotequal: '两次密码输入不相同',
	gps: '卫星定位',
	tower: '基站定位',
	wifi: 'Wifi定位',
	phonetype0: '其他',
	phonetype1: '爸爸',
	phonetype2: '妈妈',
	phonetype3: '奶奶',
	phonetype4: '爷爷',
	phonetype5: '同学',
	phonetype: '关系',
	name: '姓名',
	reenter: '请重新输入',
	minichat: '微聊',
	sendvoice: '按住 说话',
	pulltorefresh: '下拉加载更多',
	me: '我',
	unread: '未读',
	holdtip: '请长按录音，最长10秒',
	voicetoolarge: '语音录制时间超过10s,请重新录制。',
	novoice: '还没有任何微聊消息',
	sending: '正在发送...',
	recording: '录音中...{time} 秒',
	preparing: '请准备...',
	watchalarm: '闹铃',
	watchalarmdetail: '闹铃设置',
	morning: '上午',
	afternoon: '下午',
	today: '今天',
	everyday: '每天',
	repeat: '重复',
	day0: '周日',
	day1: '周一',
	day2: '周二',
	day3: '周三',
	day4: '周四',
	day5: '周五',
	day6: '周六',
	alarm16: '有新的微聊信息',
	confirmdeletealarm: '确认删除该闹铃',
	noalarms: '还未设置任何闹铃，点击添加闹铃',
	smart: '智能定位',
	starttime: '开始时间',
	endtime: '结束时间',
	contain: '包含',
	mynumber: '我的电话号码',
	appqrcode: 'app下载二维码',
	dialbackno: '回拨号码',
	notsupported: '此手表不支持微聊',
	hideself: '上课禁用',
	hideselfdetail: '上课禁用设置',
	hideselfbegin: '开始时间:',
	hideselfend: '结束时间:',
	nohidetimers: '点击添加上课禁用设置',
	invalidendtime: '结束时间须大于开始时间',
	enable: '开启',
	twotimerconflict: '与以下时间段冲突：',
	moreadvancedsetting: '高级设置',

	homewifisetting: '区域WiFi设置',
	homewificomments: '请选择此安全区域的WiFi热点,如WiFi热点不在列表中,请点击\'取消\'',
	accuracy: '精确度',

	newappversion: '新版本',
	/*.watchprivilegetitle: '手表权限',*/
	/*.watchprivilegeadmin: '管理员',*/
	later: '稍后再说',
	upgrade: '升级',
	uptodate: '已是最新',
	checkingupdate: '检查更新中...',

	disconnectedtips: '正在连接服务器, 请稍候...',
	uploadfailed: '上传失败',
	lightbulb: '闪光灯',
	invalid: '不正确',
	phonelistisfull: '亲情号码列表已满',
	serverinternalerror: '服务器内部错误',
	addwatchtimeout: '添加手表超时',
	deletewatchtimeout: '删除手表超时',
	registertimeout: '注册超时',
	registerfailed: '注册失败',
	failed: '失败',
	timeout: '超时',
	activedevice: '激活手表连接',
	familynumbernotfound: '未找到亲情号码',
	updating: '更新中...',
	//updatedonetips: '更新完毕!请',
	disablewifilocation: '禁用WiFi定位',
	locatenowtips: '此功能会触发手表立即上报一条最新定位数据。如果手表此时与服务器断开连接,则需要通过向手表发送一条短信来触发手表上报最新定位。',
	confirmsendsmstoactive: '手表暂时与服务器断开连接, 是否发送短信触发手表立即定位',
	inputfencename: '请输入安全区域名字',

	Pleaseconfirm: "请确认",
	agreeprivacypolicy: '注册代表你同意',
	privacypolicytitle: '隐私条款',

	passwordruletips: '密码至少需要8个字符，必须包括一个数字、一个小写字母和一个大写字母。',
	commonsecret: '密码相同，请重新输入',
	passworderror: '密码错误!',
	passworderror5: '密码输入错误超限,请等一分钟重新输入!',

	addAccount: '添加管理员权限',
	notAccount: '没有权限!',
	overlimitNumber: '添加号码超限',

	friends: "爱娃的好友",
	friendslist: "爱娃好友",

	Nameoflocator: "定位器名字",
	LocatorNumber: "定位器号码",

	DeviceName: "设备名字",
	SpeedAlarm: "超速报警",
	DeviceCode: "设备版本号",
	ActivePositioningMode: "主动定位模式",
	DeviceNotFeature: "设备不支持此功能",
	RebootDevice: "设备重启",
	ResetDevice: "恢复出厂设置",
	timeInterval: "时间间隔",
	IncludingPositioning: '包含基站定位',
	Whether: '是否有',
	Obtain: "获取",
	Device: "设备",
	Transmission: "已经发送到",
	PasswordRese: "密码重置失败。请再试一次",
	GatorUseName: "",
	NameWatchShown: "手表上显示的名称",
	successfulActivation: "成功设置 ",
	activationFailed: "设置不成功",



  antiTheft:"防盗功能",


systolic :'收缩压',
diastolic:'舒张压',
power:'电量',
pulseRate:'脉率',
oxygenSaturation:'血氧饱和度',
WeakPerfusion:'血流弱灌注指数',
temperature:'体温',
healthSettings:'健康设置',
thermometer:'体温计',
oximeter:'血氧仪',
sphygmomanometer:'血压计',
son:'儿子',
daughter:'女儿',
spouse:'夫妻',
ordinaryAlarm:'普通闹铃',
takeMedicine:'吃药',
drinkWater:'喝水',
sedentaryReminder:'久坐提醒',
testReminder:'测量提醒',




}